#!/bin/bash

echo2() { echo "$@" >&2; }
DIE() {
    local progname=${0##*/}
    echo2 "$progname: error: $1"
    exit 1
}

Main() {
    local progname=${0##*/}
    case "$1" in
        -h | --help) echo2 "Usage: $progname [-h | --help] pkg-name [field-name]"; return 0 ;;
    esac
    local pkgname="$1"
    local fieldname="$2"      # optional, default: URL
    [ "$fieldname" ] || fieldname=URL
    local helper=paru
    [ -x /bin/$helper ] || helper=yay
    [ -x /bin/$helper ] || helper=pacman
    local data=$(LANG=C $helper -Sii "$pkgname" 2>/dev/null)
    [ "$data" ] || DIE "$pkgname info not found"
    local info=$(echo "$data" | grep -w "^$fieldname" | sed -E "s|^$fieldname[ ]+:[ ]+||")
    [ "$info" ] || DIE "field-name '$fieldname' not found"
    echo2 "$info"
    case "$fieldname" in
        URL | "AUR URL") setsid xdg-open "$info" &>/dev/null ;;
    esac
}

Main "$@"
