#!/bin/bash

echo2() { echo "$@" >&2; }
DIE() {
    local progname=${0##*/}
    echo2 "$progname: error: $1"
    Main --help
    exit 1
}

Main() {
    local progname=${0##*/}
    local pkg_name="$1"
    local fieldname="$2"      # optional, default: URL
    shift 2

    if false ; then
        while [ "$1" ] ; do
            case "$1" in
                -p=* | --pkg=*)   pkg_name=${1#*=} ;;
                -f=* | --field=*) fieldname=${1#*=} ;;
                -h | --help)
                    cat <<EOF >&2
Usage:   $progname [options]
Options:
    -h,   --help        This help.

If no options and if a PKGBUILD file exists in the current folder, its URL is used.
EOF
                    return 0
                    ;;
            esac
            shift
        done
    else
        case "$1" in
            -h | --help)
                    cat <<EOF >&2
Usage:   $progname [options] [pkg-name [field-name]]
Parameters:
    pkg-name         Name of a package.
    field-name       Name of the field in the output of 'yay -Sii <pkg-name>'.
                     Default: URL
                     Field-name is in English.
Options:
    -h,   --help        This help.

If no parameters/options and if a PKGBUILD file exists in the current folder,
its URL will be used.
If the field-name is one of
    URL
    AUR URL
the url will be opened in the web browser.
EOF
                return 0
                ;;
        esac
    fi

    [ "$fieldname" ] || fieldname=URL

    local helper=paru
    [ -x /bin/$helper ] || helper=yay
    [ -x /bin/$helper ] || DIE "no supported AUR helper (paru, yay) found"

    if [ -z "$pkg_name" ] ; then
        if [ -e PKGBUILD ] ; then
            source PKGBUILD
            pkg_name="$pkgname"
        else
            DIE "no option nor PKGBUILD"
        fi
    fi

    local opt="-Sii"

    case "$fieldname" in
        "AUR URL") opt+=" --aur" ;;
    esac

    local data=$(LANG=C pacman $opt "$pkg_name" 2>/dev/null)
    [ "$data" ] || data=$(LANG=C $helper $opt "$pkg_name" 2>/dev/null)
    [ "$data" ] || DIE "$pkg_name info not found"
    local info=$(echo "$data" | grep -w "^$fieldname" | sed -E "s|^$fieldname[ ]+:[ ]+||")
    [ "$info" ] || DIE "field-name '$fieldname' not found"

    echo2 "$info"
    case "$fieldname" in
        URL | "AUR URL") setsid xdg-open "$info" &>/dev/null ;;
    esac
}

Main "$@"
