#!/bin/bash
#
# Author: manuel (see https://forum.endeavouros.com)
#
# 'pkexec' wrapper.
# Executes the command retaining the $PWD instead of changing to /root.
#

Main()
{
    local xx
    local prompt="Elevated privileges required:"
    local cmds="cd '$PWD' ;"

    for xx in "$@" ; do
        if [ "${xx/ /}" = "$xx" ] || [ "${xx/	/}" = "$xx" ] ; then
            cmds+=" $xx"     # includes no white spaces
        else
            cmds+=" '$xx'"
        fi
    done

    echo "$prompt" >&2
    /usr/bin/pkexec bash -c "$cmds"
}

Main "$@"
