#!/bin/bash
#
# 'pkexec' wrapper.
# Executes the command retaining the $PWD instead of changing to /root.
#

Main()
{
    local xx
    local cmds="cd '$PWD' ;"

    for xx in "$@" ; do
        cmds+=" '$xx'"
    done

    /usr/bin/pkexec bash -c "$cmds"
}

Main "$@"
