#!/bin/bash

# arch-audit with structured output.
# Packages needed:
#    arch-audit
#    bat

Main() {
    local data=$(/usr/bin/arch-audit)
    local names=()
    local msgs=()
    local verdicts=()
    local ix count
    local namelen=0 msglen=0
    local trim=yes                 # yes = skips "is affected by" from output

    readarray -t names    <<< $(echo "$data" | awk '{print $1}')
    readarray -t verdicts <<< $(echo "$data" | sed 's|^.*\. \(.*\)|\1|')
    if [ "$trim" = "yes" ] ; then
        readarray -t msgs <<< $(echo "$data" | sed 's|^.*is affected by \([^\.]*\).*|\1|')
    else
        readarray -t msgs <<< $(echo "$data" | sed 's|^.*\(is affected by [^\.]*\).*|\1|')
    fi

    # calculate string lengths to make shorter output lines
    count=${#names[@]}
    for ((ix=0; ix<count; ix++)) ; do
        [ ${#names[ix]} -gt $namelen ] && namelen=${#names[ix]}
        [ ${#msgs[ix]}  -gt $msglen  ] && msglen=${#msgs[ix]}
    done

    for ((ix=0; ix<count; ix++)) ; do
        printf "%-*s  %-*s  %s\n" "$namelen" "${names[ix]}" "$msglen" "${msgs[ix]}" "${verdicts[ix]}"
    done | /usr/bin/bat --style numbers,grid
}

Main "$@"
