#!/bin/bash

# Show a glimpse of the "testing" updates in a "stable" system.

HasRepo() { echo "$repos" | grep "^$1$" >/dev/null ; }

AddRepo() {
    local before_repo="${1#--before=}"
    local repo_to_add="$2"
    local repoentry="[$repo_to_add]\n"
    repoentry+="Include = /etc/pacman.d/mirrorlist\n"
    sed -i "$testconf" -e "/^\[$before_repo\]/i \ \n$repoentry"   # add testing repo before its stable repo
}

glimpse-testing-updates() {
    local testconf="$(mktemp)"
    local repo
    local repos=$(pacconf --repo-list)

    rm -f "$testconf"
    cp /etc/pacman.conf "$testconf"
    chmod go-rwx "$testconf"

    [ "$XDG_CURRENT_DESKTOP" = "KDE" ] && AddRepo --before=core kde-unstable

    for repo in core extra multilib ; do
        if HasRepo $repo ; then
            HasRepo ${repo}-testing || AddRepo --before=$repo ${repo}-testing
        fi
    done

    echo "Updating testing database."
    sudo pacman --config "$testconf" -Sy

    pacman --config "$testconf" -Qu | column -t
    rm -f "$testconf"
}

glimpse-testing-updates "$@"
