#!/bin/bash

Run() {
    if [ "$1" ] ; then
        echo "==> $*" >&2
        sleep 1
        bash -c "$*"
    fi
}

Main() {
    local -r mode=${0##*/}
    local cmd=""

    case "$mode" in
        hibernate | disksleep)
            if [ "$(lsblk -o FSTYPE | grep -w swap)" ] ; then
                cmd="sync && systemctl hibernate"
            else
                echo "swap is unavailable for '$mode'." >&2
                return 1
            fi
            ;;
        logoff)   # logout
            if [ -x /bin/xfce4-session-logout ] ; then
                cmd="sync && xfce4-session-logout --logout"
            else
                echo "sorry, $mode needs package xfce4-session" >&2
                return 1
            fi
            ;;
        poweroff | bye)
            which logstuff &> /dev/null && cmd="logstuff off && "
            cmd+="sync && systemctl poweroff"
            ;;
        reboot | restart)
            cmd="sync && systemctl reboot"
            ;;
        ramsleep)    # suspend
            cmd="sync && systemctl suspend"
            ;;
    esac
    Run "$cmd"
}

Main "$@"
