#!/bin/bash
#
# Show info about pacman history.
#

DIE() {
    echo "Error: $@" >&2
    Usage
    exit 1
}

Usage() {
    local progname="$(basename $0)"
    cat <<EOF >&2

$progname: shows history information about package operations.

Usage: $progname [operation] [package]

    operation      One of: $(Main --operations).
                   Tip: press the Tab key to complete the word!

    package        Package name (optional). If no package name is given,
                   show all packages experienced the given operation.

Note: bash command completion is available.

Examples:
    pahis --upgraded firefox
    pahis --installed
    pahis geany

EOF
}

Main()
{
    local op="$1"
    local pkg="$2"
    local output
    local pacmanlog=/var/log/pacman.log

    case "$op" in
        --operations)   # supports bash command completion
            echo "--upgraded --downgraded --installed --removed --reinstalled"
            return
            ;;
        --upgraded | --downgraded | --installed | --removed | --reinstalled)
            op=${op:2}
            ;;
        "" | -h | --help)
            Usage
            return
            ;;
        -*)
            DIE "unsupported operation '$op'"
            ;;
        *)
            # $op must be a pkg or an unknown operation
            if [ -z "$pkg" ] ; then
                # Maybe pkg should be in $1? Then show all operations for the package.
                pkg="$op"   # $op is not empty
                op=""
            else
                DIE "unsupported operation '$op'"
            fi
            ;;
    esac

    test -n "$pkg" && {
        pacman -Si "$pkg" >& /dev/null || DIE "package '$pkg' does not exist."
    }

    if [ -z "$pkg" ] ; then
        output="$(grep " \[ALPM\] $op " $pacmanlog)"
    else
        if [ -z "$op" ] ; then
            output="$(grep " \[ALPM\] [a-z]*ed $pkg " $pacmanlog)"
        else
            output="$(grep " \[ALPM\] $op $pkg " $pacmanlog)"
        fi
    fi

    test -n "$output" && {
        echo "$output" | tac | less
    } || {
        echo "Requested info is not available."
        echo "Probable reasons:"
        echo "  - '$pkg' was never installed"
        if [ "$op" != "installed" ] ; then
            echo "  - '$pkg' was never $op"
        fi
        echo "  - '$pkg' was installed while installing the system"
    }
}

Main "$@"
