#!/bin/bash

echo2()       { echo "$@" >&2; }
DIE()         { echo2 -e "==> $progname: error:\n    $1"; Usage; exit 1; }
WARN()        { echo2 -e "==> $progname: warning: $1"; }

GetCurrentCountry() { cc="$(show-location-info country)"; [ "$cc" ] ; }

GetContinentOfCountry() {
    local countrycode="${1^^}"   # uppercase
    GetContinentsData
    local out=$(echo "$countries_continents" | grep -w "$countrycode" | awk '{print $2}')
    echo "$out"
}
GetContinentsData() {
    [ "$countries_continents" ] || countries_continents=$(location list-countries --show-continent)
}
ShowContinents() {
    [ "$continents" ] || GetContinentsData
    echo "$countries_continents" | awk '{print $NF}' | sort -u
}
ShowContinentsCountries() {
    local continents="$1"
    local continent=""
    local tmp=$(
    for continent in $continents ; do
        ShowContinentCountries "$continent" code
    done)
    tmp=$(echo $tmp | tr ' ' '\,' | sed 's|\,\,|\,|g')
    echo "$tmp"
}
ShowContinentCountries() {
    local continent="$1"
    local show="$2"       # name or code
    if [ -x /bin/location ] ; then
        [ "$cc" ] || GetCurrentCountry
        GetContinentsData
        local cont_country_codes=$(echo "$countries_continents" | grep "$continent" | awk '{print $1}')
        local code 
        GetCountriesData
        case "$show" in
            code)
                # echo "$cont_country_codes"
                local out
                for code in $cont_country_codes ; do
                    out=$(echo "$reflector_list_countries" | grep "$code" | awk '{print $(NF-1)}')
                    if [ "$IGNORED_COUNTRY_CODES" ] ; then
                        echo "$out" | grep -Pv "$IGNORED_COUNTRY_CODES"
                    else
                        echo "$out"
                    fi
                done
                ;;
            name)
                local name
                for code in $cont_country_codes ; do
                    name=$(echo "$reflector_list_countries" | grep "$code" | sed -E 's|([A-Z].+[a-z]) .*|"\1"|')
                    [ "$name" ] && echo "$name"
                done
                ;;
        esac
        return 0
    else
        WARN "package 'python-location' is required for this operation"
        return 1
    fi
}
ListCountryCodes() {
    GetCountriesData
    echo "$reflector_list_countries" | awk '{print $(NF-1)}'
    exit 0
}
ListCountryNames() {
    GetCountriesData
    echo "$reflector_list_countries" | sed -E 's|([A-Z].+[a-z]) .*|"\1"|'
    exit 0
}
GetCountriesData() {
    local timeinfo="$HOME/.cache/$progname/timeinfo.txt"
    local now=$(date +%j)
    
    if [ -z "$reflector_list_countries" ] || [ "$(< "$timeinfo")" != "$now" ] ; then
        reflector_list_countries=$(reflector --list-countries) || DIE "cannot get list of countries"
        reflector_list_countries=$(echo "$reflector_list_countries" | tail -n +3)
    fi
}

TraverseMirrors-parallel() {
    echo2 "==> $progname: ranking mirrors in parallel"
    local timeout_rank=10
    local mirrors_with_statefiles=$(echo "$mirrors" | sed "s|/\$repo/os/\$arch|/$syncfile|")
    echo "$mirrors_with_statefiles" | parallel "eos-mr-rank-mirror {} $timeout_rank $distro $time_as_datetime"
}

TraverseMirrors-sequential() {
    echo2 "==> $progname: ranking mirrors in sequence"
    local timeout_rank=10
    local mirror
    local ix=1
    local count=$(echo "$mirrors" | wc -l)

    for mirror in $mirrors ; do
        mirror="${mirror%%/\$repo/os/\$arch}/$syncfile"
        printf "\r==> ranking %s/$count" $((ix++)) >&2
        eos-mr-rank-mirror "$mirror" $timeout_rank $distro $time_as_datetime
    done
    echo2 ""
}

DumpOptions() {
    if [ "$lopts" ] ; then
        lopts=${lopts//:/}          # remove all : chars
        lopts="--${lopts//,/ --}"   # make all words as options with prefix "--"
    fi
    if [ "$sopts" ] ; then
        sopts=${sopts//:/}          # remove all : chars
        sopts=${sopts//?/ -&}       # make all letters as options with prefix "-"
        sopts=${sopts:1}            # remove the first space
    fi

    [ "$lopts$sopts" ] && echo $lopts $sopts
}

Usage() {
#Usage: $progname [options] [URLs]
#URLs:                          URL(s) of mirrors to rank.
#    --list-country-codes           Show available country codes. See also: 'reflector --list-countries'.
#    --list-country-names           Show available country names. See also: 'reflector --list-countries'.
#    --show-continent-countries     Show the country codes of a continent based on given country code.
    cat <<EOF
Rank Arch mirrors and display them.

Usage: $progname [options]

Options:
    -h, --help                     This help.
    -A, --all                      Rank all available mirrors on all continents.
    -C, --continent                Rank all available countries of the current continent.
    -c, --country <country-list>   A comma separated list of country code(s) for ranking their mirrors.
                                   Codes are case insensitive. Example: "--country de,gb".
    -l, --country-current          Add current country code for mirrors to rank.
    -r, --ranking-data             Show ranking data too.
EOF
}
Options() {
    local opts
    local lopts="all,continent,country:,country-current,distro:,dump-completion-files,dump-options,help"
    lopts+=",list-country-codes,list-country-names,ranking-data"
    lopts+=",reset-completion-files,show-continent-countrycodes:,show-continent-countrynames:"
    lopts+=",show-current-continent-countrycodes,show-current-continent-countrynames"
    # lopts+=",save:"
    local sopts="ACc:d:hlrt"

    opts="$(/usr/bin/getopt -o=$sopts --longoptions $lopts --name "$progname" -- "$@")" || DIE "getopt error"
    eval set -- "$opts"

    while true ; do
        case "$1" in
            --)                                     shift; break ;;
            -h | --help)                            Usage; exit 0 ;;
            -A | --all)                             local tmp1=$(ShowContinentsCountries "$all_continents")
                                                    Options -c $tmp1
                                                    ;;
            -C | --continent)                       Options -c $(echo $(Options --show-current-continent-countrycodes) | tr ' ' ',') ;;
            -c | --country)                         local tmp="${2^^}"; countries+=( ${tmp//,/ } ); shift ;;   # must be country codes!
            -l | --country-current)                 GetCurrentCountry && countries+=($cc) ;;
            -d | --distro)                          distro="$2"; shift ;;
            -r | --ranking-data)                    ranking_data=yes ;;
            --dump-options)                         DumpOptions; exit 0 ;;
            --dump-completion-files)                ShowCompletionFiles; exit 0 ;;
            --reset-completion-files)               ResetCompletionFiles; exit 0 ;;
            --list-country-codes)                   ListCountryCodes; exit 0 ;;
            --list-country-names)                   ListCountryNames; exit 0 ;;
            --show-continent-countrycodes)          ShowContinentCountries "$2" code; exit ;;
            --show-continent-countrynames)          ShowContinentCountries "$2" name; exit ;;
            --show-current-continent-countrycodes)  GetCurrentCountry && ShowContinentCountries "$(GetContinentOfCountry $cc)" code; exit ;;
            --show-current-continent-countrynames)  GetCurrentCountry && ShowContinentCountries "$(GetContinentOfCountry $cc)" name; exit ;;
            # --save)                                 savefile="$2"; shift ;;
        esac
        shift
    done
    urls+=("$@")
}

ShowCompletionFiles() {
    local -r dir="$HOME/.cache/$progname"
    echo "$dir" "$dir/timeinfo.txt" "$dir/countrycodes.txt" "$dir/countrynames.txt" "$dir/optionsfile.txt" \
         "${all_continents// /,}"   # ShowContinents
}
ResetCompletionFiles() {
    local xx=($(ShowCompletionFiles))
    rm -f ${xx[0]}/*.txt
}

Main() {
    local -r progname=${0##*/}
    local distro=""             # arch or endeavouros
    local urls=() url
    local timeout=10
    local syncfile=""
    local mirrors
    local mirrorlist=""
    local time_as_datetime=no
    local ranking_data=no
    local countries=()          # contains only uppercase country codes
    local cc=""                 # current country
    local countries_continents=""
    local tmp
    local savefile=""              # not supported currently, if ever
    local suffix=""
    local reflector_list_countries=""
    local has_parallel=yes
    local IGNORED_COUNTRY_CODES=""
    local -r conf=$HOME/.config/$progname.conf
    local -r all_continents="AF AN AS EU NA OC SA"

    [ -e "$conf" ] && source "$conf"

    [ -x /bin/parallel ] || has_parallel=no # DIE "package 'parallel' is required"

    Options "$@"

    case "$distro" in
        "" | arch)
            distro=arch
            if [ ${#countries[@]} -eq 0 ] ; then
                echo2 "==> option --country not used -> automatically adding the current country for ranking, if possible"
                GetCurrentCountry && countries+=($cc) && echo2 "==> added: $cc" || DIE "no countries given for ranking."
            fi
            mirrorlist=/etc/pacman.d/mirrorlist
            syncfile=lastupdate
            time_as_datetime=yes
            suffix='/$repo/os/$arch'
            url="https://archlinux.org/mirrorlist/?protocol=https&ip_version=4&use_mirror_status=on"
            for tmp in "${countries[@]}" ; do
                url+="&country=$tmp"
            done
            mirrors=$(curl -Lsm $timeout "$url" | grep "^#Server = " | awk '{print $NF}')
            ;;
        endeavouros)
            DIE "sorry, waiting for implementation!"
            mirrorlist=/etc/pacman.d/endeavouros-mirrorlist
            syncfile=state
            suffix='/$repo/$arch'
            # TODO: fetch endeavouros-mirrorlist !!
            mirrors=$(grep "^Server[ \t]*=[ \t]*" "$mirrorlist" | awk '{print $NF}')
            ;;
        *)  DIE "distro $distro not supported." ;;
    esac

    local msg=""
    case "$has_parallel" in
        yes) result=$(TraverseMirrors-parallel); msg="in parallel" ;;
        no)  result=$(TraverseMirrors-sequential); msg="sequentially" ;;
    esac

    local ranked=$(echo "$result" | column -t -s'|' | LC_ALL=C sort -k2rb,2 -k3b,3)   # sort: age

    CreateMirrorlistFile "$@"

    #if [ -z "$savefile" ] ; then
    #    CreateMirrorlistFile "${args[@]}"
    #elif [ -w ${savefile%/*} ] && [ -w "$savefile" ] ; then
    #    CreateMirrorlistFile "${args[@]}" | tee "$savefile"
    #else
    #    CreateMirrorlistFile "${args[@]}" | sudo tee "$savefile"
    #fi
}

CreateMirrorlistFile() {
    ShowMirrorlist    "\n### ${distro^} mirror list, ranked $msg by command:\n### $progname $*\n"
    ShowRankingResult "\n### Ranking data:"
}

ShowMirrorlist()    { echo -e "$1"; echo "$ranked" | awk '{print $1}' | sed -E "s|(.*)|Server = \1$suffix|"; }
ShowRankingResult() { [ $ranking_data = yes ] && { echo -e "$1"; echo "$ranked" | sed -E "s|^([^ ]+)|### \1$suffix|"; } ; }

Main "$@"
