#!/bin/bash
#
# Copy built packages from old repo to new repo.

DIE() {
    echo "Error: $1" >&2
    Usage
    exit 1
}

GitUpdate() {
    echo "Adding files to github:" >&2
    git add "$(basename "$dstdir")"
    git commit -m "."          # dummy commit message
    git push
}

Main()
{
    local gitdir="$PWD"                                       # has .git folder
    local reponame="$(basename "$PWD")"
    local srcdir="$PWD/../_BUILD_/$reponame"
    local dstdir="$PWD/repo"
    local diffval=0

    test -d "$gitdir"/.git   || DIE "folder '$gitdir/.git' not found!"
    test -d "$srcdir"        || DIE "folder '$srcdir' not found!"
    test -d "$dstdir"        || DIE "folder '$dstdir' not found!"

    diff "$srcdir" "$dstdir" \
         -x 'assets.conf*' \
         -x .git \
         -x PKGBUILDS \
         -x PKGBUILDs \
         -x .vscode
    diffval=$?

    if [ $diffval -ne 0 ] ; then
        echo "" >&2
        read -p "Files differ. Copy assets (y/n)? " >&2
        case "$REPLY" in
            [yY]*)
                rm -f "$dstdir"/*.{db,files,sig,xz,zst}
                cp    "$srcdir"/*.{db,files,sig,xz,zst} "$dstdir"

                cd "$gitdir"
                GitUpdate
                ;;
        esac
    else
        echo "No changes." >&2
    fi
}


Main "$@"
