#!/bin/bash

DIE() {
    echo "Error: $1" >&2
    exit 1
}

MainXbacklight()
{
    local esc="$(printf "\033")"

    local right="$esc[C"
    local left="$esc[D"
    local up="$esc[A"
    local down="$esc[B"
    local ctrl_up="$esc[1;5A"
    local ctrl_down="$esc[1;5B"
    local alt_up="$esc[1;3A"
    local alt_down="$esc[1;3B"

    local longest_key_length=6  # see key values above
    local key
    local bright="$(bcround "$(xbacklight -get)" 0)"

    while true ; do
        read -s -n $longest_key_length -t 0.2 key
        case "$key" in
            $up)        ((bright += 1)) ;;
            $down)      ((bright -= 1)) ;;
            $alt_up)    ((bright += 5)) ;;
            $alt_down)  ((bright -= 5)) ;;
            $ctrl_up)   ((bright += 10)) ;;
            $ctrl_down) ((bright -= 10)) ;;
            $left)      bright=1 ;;
            $right)     bright=100 ;;
            q)
                echo "quit"
                break
                ;;
        esac
        test $bright -le   1 && bright=1
        test $bright -ge 100 && bright=100
        test -n "$key" && echo "New brightness value: $bright"
        xbacklight =$bright
    done
}

Main() {
    if [ -d /sys/class/backlight/intel_backlight ] ; then
        brightness-intel "$@"
    else
        brightness-xrandr "$@"

        #case "$(device-info --graphics)" in
        #    *NVIDIA*) brightness-xrandr "$@" ;;
        #    *)        MainXbacklight "$@" ;;
        #esac
    fi
}

Main "$@"
