#!/bin/bash

# Manager for manual interventions.

echo2() { echo -e "$@" >&2; }
WARN()  { echo2 "$progname: warning: $1"; }
DIE()   { echo2 "$progname: error: $1"; exit 1; }

RUN() {
    echo2 "   ->" "$@"
    if "$@" ; then
        return 0
    else
        DIE "'$*' failed."
        exit 1
    fi
}

MarkOk() {
    echo2 "  ==> marking '$1' as handled"
    echo "$1" | sudo tee -a "$handled_fixes" >/dev/null
}
IsOk() { grep "^$1$" "$handled_fixes" &>/dev/null; }

FetchHotfixFile() {
    echo2 "\n###### TODO: fetch the latest recipe file! ######\n"
    if [ -e "$mifile" ] ; then
        sudo chmod -w "$mifile"
        source "$mifile"
    fi
}

RunFixesIfNeeded() {
    local count=${#MI_func_names[@]}
    local ix mifunc descr

    for ((ix=0; ix < count; ix+=2)) ; do
        mifunc="${MI_func_names[$ix]}"
        descr="${MI_func_names[$((ix+1))]}"
        if IsOk "$mifunc" ; then
            echo2 "$mifunc:\talready OK"
        else
            echo2 "$mifunc: $descr"
            if $mifunc ; then
                MarkOk "$mifunc"
            else
                return 1
            fi
        fi
    done
}

Prepare() {
    sudo mkdir -p "$dir"
}
NewsPage() {
    local bb
    for bb in exo-open kde-open xdg-open firefox ; do
        if [ -x /bin/$bb ] ; then
            /bin/$bb https://archlinux.org/news &
            break
        fi
    done
    [ "$1" ] && exit $1
}
Help() {
    cat <<EOF >&2
Purpose: Execute and manage essential manual interventions.
Usage:   $progname [options]
Options: -h, --help            This help.
         -n, --show-arch-news  Show the Arch news page in a browser.
EOF
    [ "$1" ] && exit $1
}

Options() {
    local arg
    for arg in "$@" ; do
        case "$arg" in
            -h | --help)           Help 0 ;;
            -n | --show-arch-news) NewsPage 0 ;;
        esac
    done
}

Main() {
    local -r progname=${0##*/}
    local -r dir=/etc/$progname
    local -r mifile="$dir/$progname.interventions"
    local -r handled_fixes="$dir/handled.txt"
    local MI_func_names=()

    Options "$@"
    Prepare
    FetchHotfixFile
    RunFixesIfNeeded
}

Main "$@"
