#!/bin/bash
#
# Helper for the 'su -c' command
# (understands spaces in command parameters).

Usage() {
    echo "Usage: $(basename $0) command-with-parameters" >&2
}

DIE() {
    Usage
    echo "Error: $1" >&2
    exit 1
}

Main() {
    local xx
    local command=()

    test -z "$1" && DIE "command missing"

    for xx in "$@" ; do
        command+=("'$xx'")
    done
    /usr/bin/su -c "${command[*]}" # || DIE "invalid command"
}

Main "$@"
