#!/bin/bash

# Enables bash debugging for vscodium (using bashdb).
# The parameters for the debuggee will be delivered via 'args' of the launch configuration in settings.json.

GetParams() {
    # convert parameters suitable for 'args'
    local arg
    for arg in "$@" ; do
        params+=",\"$arg\""
    done
    params=${params#,}
}

IdeDebugBash() {
    local -r bash_file_to_debug="$1"
    local -r settings_file="$HOME/.config/$appconfdir/User/settings.json"
    local -r special_string="# 'bide' will overwrite only the parameter list on this line"
    local params=""

    shift

    GetParams "$@"

    if [ ! -e "$settings_file" ] ; then
        # File settings.json does not exist, so create the initial version.
        cat <<EOF > "$settings_file"
{
    "launch": {
        "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug",
            "cwd": "\${env:PWD}",
            "program": "\${file}",
            "args": [$params]            $special_string
        }
        ]
    },
    "editor.minimap.enabled":            false,
    "editor.fontFamily":                 "'Liberation Mono', 'Droid Sans Mono', 'monospace', monospace",
    "editor.fontSize":                   12,
    "editor.inlineSuggest.enabled":      false,
    "files.autoSave":                    "afterDelay",
    "git.openRepositoryInParentFolders": "never",
    "workbench.startupEditor":           "none",
        "editor.unicodeHighlight.allowedCharacters": {
        "ä": true,
        "ö": true,
        "Ä": true,
        "Ö": true
    }
}
EOF
    else
        # File settings.json exists, so check 'bide' compatibility first.
        grep "$special_string" "$settings_file" >/dev/null || DIE "sorry, '$settings_file' does not contain the special bashdb launch configuration"
        # Add parameters via the 'args' field in settings.json.
        sed -i "$settings_file" -E -e "s|^([ ]+\"args\":[ ]+)\[[^]]*\]|\1[$params]|"
    fi
    # Run vscodium.
    $app --wait "$bash_file_to_debug"
    return $?
}

InstanceCheck() { ps -C $app >/dev/null && DIE "'$progname' supports only one instance of '$app'." ; }

DIE() {
    echo "$progname: error: $1" >&2
    exit 1
}

Main() {
    # Vscodium that supports bash debugging.
    # Delivers app parameters by changing 'args' in settings.json.
    # Usage:
    #    bide "bash-script-file-to-debug" parameters-for-the-bash-script

    local -r progname=${0##*/}
    local -r app=codium
    local -r appconfdir=VSCodium

    InstanceCheck
    IdeDebugBash "$@"
}

Main "$@"
