#!/bin/bash

# Enables bash debugging for vscodium (using bashdb).
# The parameters for the debuggee will be delivered via 'args' of the launch configuration in settings.json.

GetParams() {
    # convert parameters suitable for 'args'
    local arg
    for arg in "$@" ; do
        params+=",\"$arg\""
    done
    params=${params#,}
}

AddOwnSettings() {
    local -r own_settings_file="$HOME/.config/$appconfdir/User/own-settings.json"
    if [ -e "$own_settings_file" ] ; then
        cat "$own_settings_file" >> "$settings_file"
    fi
}

CreateSettingsJson() {
    [ -e "$settings_file" ] && return   # don't overwrite existing settings.json

    cat <<EOF > "$settings_file"
{
    "launch": {
        "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug a script",
            "cwd": "\${env:PWD}",
            "program": "\${file}",
            "args": [$params]            $special_string
        }
        ]
    }
EOF
    AddOwnSettings                   # Add your own settings from own-settings.json
    echo "}" >> "$settings_file"     # Finalize the settings.json file.
}

AddNewParameters() {
    GetParams "$@"

    # File settings.json exists, so check 'bide' compatibility first.
    grep "$special_string" "$settings_file" >/dev/null || DIE "sorry, '$settings_file' does not contain the special bashdb launch configuration"

    # Add parameters via the 'args' field in settings.json.
    sed -i "$settings_file" -E -e "s|^([ ]+\"args\":[ ]+)\[[^]]*\]|\1[$params]|"

    # Run vscodium.
    $app --wait "$bash_file_to_debug"
    return $?
}

IdeDebugBash() {
    local -r bash_file_to_debug="$1" ; shift
    local -r settings_file="$HOME/.config/$appconfdir/User/settings.json"
    local -r special_string="# 'bide' will overwrite only the parameter list on this line"
    local params=""

    CreateSettingsJson
    AddNewParameters "$@"
}

InstanceCheck() { ps -C $app >/dev/null && DIE "'$progname' supports only one instance of '$app'." ; }

DIE() {
    echo "$progname: error: $1" >&2
    exit 1
}

Main() {
    # Vscodium that supports bash debugging.
    # Delivers app parameters by changing 'args' in settings.json.
    # Usage:
    #    bide "bash-script-file-to-debug" parameters-for-the-bash-script

    local -r progname=${0##*/}
    local -r app=codium
    local -r appconfdir=VSCodium

    InstanceCheck
    IdeDebugBash "$@"
}

Main "$@"
