#!/bin/bash

# Starts vscodium for bash scripts, supports bashdb usage.

DIE() {
    echo "$progname - error: $1" >&2
    exit 1
}

GetVscodium() {
    local app
    for app in codium codium-insiders ; do
        if [ -x "/bin/$app" ] ; then
            vscodium="$app"
            return 0
        fi
    done
    DIE "codium (or alternative) not available"
}

IdeDebugBash() {
    # Change the 'args' contents in settings.json and call vscodium.

    local bash_file_to_debug="$1"
    shift
    local src=($HOME/.config/VSCod*/User/settings.json.ref)     # we have a reference file
    local params=""
    local arg
    local jsonfile ref

    # make parameters suitable for 'args'
    for arg in "$@" ; do
        if [ -z "$params" ] ; then
            params="\"$arg\""
        else
            params+=",\"$arg\""
        fi
    done

    # We have a settings.json.ref and we copy its contents to settings.json.
    # Then we change settings.json, and call vscodium.
    # Finally make settings.json back to how it was.

    for ref in "${src[@]}" ; do
        if [ -r "$ref" ] ; then
            # found the reference file
            jsonfile=${ref%.ref}

            rm -f "$jsonfile"
            cp "$ref" "$jsonfile"

            # now we can modify 'args' in settings.json

            sed -E -i "$jsonfile" -e "s|^([ ]*\"args\":).*|\1 [$params]|"

            $vscodium --wait "$bash_file_to_debug"

            # save json file(s) in case we need the changes later

            local weekday="$(date +%a)"
            rm -f "$jsonfile.$weekday"
            mv "$jsonfile" "$jsonfile.$weekday"
            cp "$ref" "$jsonfile"
            return
        fi
    done
    DIE "‰FUNCNAME: reference file for 'settings.json' not found."
}

Main() {
    # Vscodium that supports bash debugging.
    # Delivers app parameters by changing 'args' in settings.json.
    # Usage:
    #    ide {--bashdb | -b} "bash-script-file-to-debug" parameters-for-the-bash-script
    #    ide files-to-edit

    local debug=no

    case "$1" in
        --bashdb | -b) debug=yes; shift ;;     # forces debug
    esac

    local vscodium=""
    GetVscodium vscodium

    case "$debug" in
        yes) IdeDebugBash "$@" ;;    # adjust parameters for the debugger
        no)  $vscodium    "$@" ;;    # nothing to change about parameters
    esac
}

Main "$@"
