#!/bin/bash

# Starts vscodium for bash scripts, supports bashdb usage.

DIE() {
    echo "$progname - error: $1" >&2
    exit 1
}

# Supported tools:

APPS=(
    codium
    codium-insiders
)
declare -A APPINFOS=(
    # app-name        config-folder
    # -----------------------------
    codium            "$HOME/.config/VSCodium/User"
    codium-insiders   "$HOME/.config/VSCodium - Insiders/User"    # check this path !!
)

GetVscodium() {
    local app
    for app in "${APPS[@]}" ; do
        if [ -x "/bin/$app" ] ; then
            vscodium="$app"
            return 0
        fi
    done
    DIE "codium (or alternative) not available"
}

IdeDebugBash() {
    # Change the 'args' contents in settings.json and call vscodium.

    local bash_file_to_debug="$1"
    shift
    local refs=()
    local params=""
    local arg
    local jsonfile ref

    for arg in "${APPS[@]}" ; do
        ref="${APPINFOS[$arg]}"/settings.json.ref
        [ -e "$ref" ] && refs+=("$ref")
    done

    # convert parameters suitable for 'args'
    for arg in "$@" ; do
        params+=",\"$arg\""
    done
    params=${params#,}

    # We have a settings.json.ref and we copy its contents to settings.json.
    # Then we change settings.json, and call vscodium.
    # Finally make settings.json back to how it was.

    for ref in "${refs[@]}" ; do
        if [ -r "$ref" ] ; then                                                      # found the reference file, will use it as settings.json
            jsonfile=${ref%.ref}                                                     # get the reference settings file name
            /bin/mv -f "$jsonfile" "$jsonfile".previous                              # save current for restoring it below
            /bin/cp -f "$ref" "$jsonfile"                                            # use the reference settings file
            sed -E -i "$jsonfile" -e "s|^([ ]*\"args\":).*|\1 [$params]|"            # modify 'args' in settings.json

            $vscodium --wait "$bash_file_to_debug"                                   # start vscodium

            local monthday="$(date +%d)"                                             # get the day number of the month
            /bin/mv -f "$jsonfile" "$jsonfile.$monthday"                             # save used json files (for a month) in case they contain useful changes
            /bin/mv -f "$jsonfile".previous "$jsonfile"                              # restore previously saved settings.json
            return                                                                   # all done here
        fi
    done
    DIE "$FUNCNAME: reference file for 'settings.json' not found."
}

Main() {
    # Vscodium that supports bash debugging.
    # Delivers app parameters by changing 'args' in settings.json.
    # Usage:
    #    ide {--bashdb | -b} "bash-script-file-to-debug" parameters-for-the-bash-script
    #    ide files-to-edit

    local debug=no

    case "$1" in
        --bashdb | -b) debug=yes; shift ;;     # forces debug
    esac

    local vscodium=""
    GetVscodium vscodium

    case "$debug" in
        yes) IdeDebugBash "$@" ;;    # adjust parameters for the debugger
        no)  $vscodium    "$@" ;;    # nothing to change about parameters
    esac
}

Main "$@"
