#!/bin/bash

Help() {
    cat <<EOF >&2
Usage:
      $progname "id"
Parameters:
      id     A string of characters that is unique among ids used with this app.
EOF
    [ "$1" ] && exit $1
}

DIE() { echo -e "==> $progname: error: $1\n" >&2 ; Help 2; }

OncePerBootSession() {
    local id="$1"
    local progname=${0##*/} 

    [ "$id" ] || DIE "missing parameter 'id'"

    local marker="/tmp/tmp.$id"                          # folder under /tmp
    if [ -r "$marker" ] ; then
        return 1
    else
        mkdir -m go-rwx -p "$marker"
        return 0
    fi
}

OncePerBootSession "$@"
