#!/bin/bash

DIE() {
    echo "$progname: error: $1" >&2
    exit 1
}

IsTextFile() {
    case "$(xdg-mime query filetype "$1" 2>/dev/null)" in
        application/x-shellscript) return 0 ;;
        text/plain) return 0 ;;
    esac
    # local info=$(file "$1")
    # case "$info" in
    #     *"ASCII text"*)    return 0 ;;
    #     *"Unicode text"*)  return 0 ;;
    #     *"UTF-8 text"*)    return 0 ;;
    #     *"symbolic link"*) IsTextFile $(echo "$info" | awk '{print $NF}') && return 0 ;;
    # esac
    return 1
}

Main()
{
    local progname=${0##*/}
    local files=()
    local arg path
    local openers=(/bin/exo-open /bin/kde-open /bin/xdg-open)
    local opener

    # check which of the opener apps are available
    for opener in "${openers[@]}" ; do
        [ -x $opener ] && break
    done
    [ -x $opener ] || DIE "general mime app for editing files not found"

    for arg in "$@" ; do
        case "$arg" in
            -*) DIE "unknown arg '$arg'" ;;
            *)
                if IsTextFile "$arg" ; then
                    files+=("$arg")
                else
                    path=$(which "$arg" 2>/dev/null)
                    if [ "$path" ] && IsTextFile "$path" ; then
                        files+=("$path")
                    else
                        files+=("$arg")
                    fi
                fi
                ;;
        esac
    done
    if [ ${#files[@]} -gt 0 ] ; then
        case "${opener##*/}" in
            exo-open)
                setsid "$opener" "${files[@]}" &>/dev/null
                ;;
            *)
                for arg in "${files[@]}" ; do
                    setsid "$opener" "$arg" &>/dev/null
                done
                ;;
        esac
    else
        DIE "==> nothing to open."
    fi
}

Main "$@"
