#!/bin/bash

# Wrapper for some power related commands.
# Adds:
#   - sync
#   - warning about missing swap for hibernate

DIE() {
    local msg="$1"
    echo "$progname: error: $msg" >&2
    exit 1
}

_power_routines() {
    local progname="$(basename "$0")"
    local mode="$1"

    case "$mode" in
        poweroff | reboot | suspend) ;;
        hibernate)
            [ -z "$(lsblk -o FSTYPE | grep -w swap)" ] && DIE "swap is unavailable for '$mode'." ;;
        *)
            cat <<EOF >&2
Usage: $FUNCNAME <mode>
<mode>:
    suspend    Suspend system.
    hibernate  Hibernate system.
    reboot     Restart system.
    poweroff   Power off system.
EOF
            return 1
            ;;
    esac

    local cmd="/usr/bin/systemctl $mode"
    sync && sleep 0.5 && echo "==> $cmd" >&2 && sleep 0.5 && $cmd
}

_power_routines "$@"
