#!/bin/bash

# Wrapper for some power and session related commands.
# Adds:
#   - sync
#   - warning about missing swap for hibernate

MSG() {
    local -r msg="$1"
    local type="$2"
    [ "$type" ] || type=error
    echo "$progname: $type: $msg" >&2
}
DIE() { MSG "$1" error; exit 1; }

Usage() {
    cat <<EOF >&2
Usage: $progname  <mode>
<mode>:
    logout     Logout current session.
    suspend    Suspend system.
    hibernate  Hibernate system.
    reboot     Restart system.
    poweroff   Power off system.
EOF
    [ "$1" ] && exit $1
}

_power_routines() {
    local progname="${0##*/}"
    local mode
    # local silent=no

    while [ "$1" ] ; do
        case "$1" in
            -*)            MSG "option $1 not supported"; Usage 1 ;;
            *)             mode="$1" ;;
        esac
        shift
    done

    local cmd="/bin/systemctl $mode"

    case "$mode" in
        logout | logoff)
            [ -x /bin/xfce4-session-logout ] || DIE "logout needs package xfce4-session"
            sync && xfce4-session-logout --logout
            ;;
        poweroff | reboot | suspend)
            sync && sleep 0.5 && echo "==> $cmd" >&2 && sleep 0.5 && /bin/systemctl $mode
            ;;
        hibernate)
            [ -z "$(lsblk -o FSTYPE | grep -w swap)" ] && DIE "swap is unavailable for '$mode'."
            sync && sleep 0.5 && echo "==> $cmd" >&2 && sleep 0.5 && /bin/systemctl $mode
            ;;
        *)
            Usage 1
            ;;
    esac

    # case "$silent" in
    #     yes) sync && sleep 0.5 && $cmd ;;
    #     *)   sync && sleep 0.5 && echo "==> $cmd" >&2 && sleep 0.5 && $cmd ;;
    # esac
}

_power_routines "$@"
