#!/bin/bash

Main() {
    local -r appname=${0##*/}
    local cmd=""

    case "$appname" in
        hibernate | disksleep | logoff | poweroff | "bye" | reboot | restart | ramsleep)
            /usr/local/bin/STOP "$@" ;;
        dolphin | eog | firefox-developer-edition | gitk | kate | konsole | libreoffice | parole | \
        ristretto | soffice | virtualbox | vivaldi | xed | xfce4-screenshooter | \
        xreader | adie | xplayer)
            if [ -x "/bin/$appname" ] ; then
                echo2 "==> setsid /bin/$appname" "$@"
                setsid "/bin/$appname" "$@" 2>/dev/null
            else
                echo2 "==> /bin/$appname is not found"
            fi
            ;;
    esac
}

echo2() { echo -e "$@" >&2; }

Main "$@"
