#!/bin/bash

# Provide a simple sudo-like app for all users.

Verbose() {
    [ $verbose = yes ] && echo "==> $1" >&2
}

Main() {
    local verbose=no
    local app

    case "$1" in
        --verbose-sudo)
            verbose=yes
            shift
            ;;
    esac

    if [ "$(/bin/groups | /bin/grep -w wheel)" ] && [ -x /bin/sudo ]; then
        Verbose "running as a wheel group member"
        /bin/sudo "$@"
        exit $?
    fi

    if [ $EUID -eq 0 ] || [ "$(whoami)" = "root" ] ; then
        Verbose "running as root"
        "$@"
        exit $?
    fi

    Verbose "running as a non-privileged user"
    for app in su-c_wrapper "pkexec --keep-cwd" ; do
	if [ -x /usr/bin/${app%% *} ] ; then
            /usr/bin/$app "$@"
            exit $?
	fi
    done

    exit 1  # failed, no sudo-like app found
}

Main "$@"
