#!/bin/bash

DIE() {
    local progname="$(basename "$0")"
    echo "$progname: error: $@"
    exit 0
}

Execute() {
    echo "==>" "$@" >&2
    "$@" || DIE "$@"
}

Main() {
    local config_file=/etc/grub-install-parameters-local.conf
    local GRUB_INSTALL_PARAMETERS=()

    if [ -r $config_file ] ; then
        Execute source $config_file
        if [ ${#GRUB_INSTALL_PARAMETERS[@]} -gt 0 ] ; then
            if [ "${GRUB_INSTALL_PARAMETERS[0]}" = "NOTHING" ] ; then
                Execute grub-install                                    # reserved word NOTHING was used
            else
                Execute grub-install "${GRUB_INSTALL_PARAMETERS[@]}"
            fi
            Execute grub-mkconfig -o /boot/grub/grub.cfg
        fi
    fi
}

Main "$@"
