#!/bin/bash

DIE() {
    local progname="$(basename "$0")"
    echo "$progname: error: $@"
    exit 0
}

Execute() { "$@" || DIE "$@" ; }

Main() {
    local conf=/etc/grub-install-parameters-local.conf
    local GRUB_INSTALL_PARAMETERS=()

    if [ -r $conf ] ; then
        Execute source $conf
        if [ ${#GRUB_INSTALL_PARAMETERS[@]} -gt 0 ] ; then
            Execute grub-install "${GRUB_INSTALL_PARAMETERS[@]}"
            Execute grub-mkconfig -o /boot/grub/grub.cfg
        fi
    fi
}

Main "$@"
