#!/bin/bash

BannerLine() {
    local str="$1"
    local count="$2"
    local nl="$3"   # optional, "no" prevents newline

    printf "%0.s$str" $(seq 1 $count)

    [ "$nl" != "no" ] && echo ""
}

Main()
{
    local pkgnames="$*"                      # as parameters
    [ -n "$pkgnames" ] || pkgnames="$(cat)"  # piped
    [ -n "$pkgnames" ] || return

    local out=$(expac -Q '%n|%d' $pkgnames | /bin/column -t -s'|')
    local maxlen=$(echo "$out" | wc -L)

    BannerLine '=' $maxlen
    echo "$out"
    BannerLine '=' $maxlen
}

Main "$@"
