#!/bin/bash

BannerLine() {
    local str="$1"
    local count="$2"

    [ -n "$str" ] || return

    printf "%0.s$str" $(seq $count)
    echo ""
}

Main()
{
    local pkgnames="$*"                  # as parameters
    if [ -z "$pkgnames" ] ; then
        pkgnames="$(pacman -Quq)"        # assume pacman -Sy executed
        [ -z "$pkgnames" ] && return
    fi

    local out maxlen

    out=$(expac -Q '%n|%d' $pkgnames | /bin/column -t -s'|')
    maxlen=$(echo "$out" | wc -L)

    BannerLine '=' $maxlen
    echo "$out"
    BannerLine '=' $maxlen
}

Main "$@"
