#!/bin/bash

# Show a line of $count $str strings catenated.
# A newline is added, unless the third arg is "no".
# Useful for adding lines like:
#  ==========================================

Main()
{
    local str="$1"
    local count="$2"
    local nl="$3"   # optional, "no" prevents newline

    printf "%0.s$str" $(seq 1 $count)

    [ "$nl" != "no" ] && echo ""
}

Main "$@"
