#!/bin/bash

# Emacs with a read-only support.

emacs_readonly() {
    local arg old_chmod="" chmods=() files=() mode=""
    local ix file
    for arg in "$@" ; do
        case "$arg" in
            -*) ;;
            *)  if [ -f "$arg" ] ; then
                    old_chmod=$(/bin/ls -l "$arg" | awk '{print $1}')
                    old_chmod=${old_chmod:2:1}${old_chmod:5:1}${old_chmod:8:1}
                    chmod -w "$arg" 2>/dev/null || pkexec --keep-cwd chmod -w "$arg"
                    files+=("$arg")
                    chmods+=("$old_chmod")
                fi
                ;;
        esac
    done

    /bin/emacs --reverse-video "$@"

    for ((ix=0; ix<${#chmods[@]}; ix++)) ; do
        old_chmod=${chmods[$ix]}
        file=${files[$ix]}

        [ ${old_chmod:0:1} = w ] && mode+="u+w"
        [ ${old_chmod:1:1} = w ] && mode+=",g+w"
        [ ${old_chmod:2:1} = w ] && mode+=",o+w"
        [ "${mode:0:1}" = "," ]  && mode=${mode:1}

        chmod "$mode" "$file" 2>/dev/null || pkexec --keep-cwd chmod "$mode" "$file"
    done
}

emacs_readonly "$@"
