#!/bin/bash

# Enables bash debugging for Visual Studio Code (vscodium or code).
# The debugger is bashdb.
# The parameters for the debuggee will be delivered via 'args' of the launch configuration in settings.json.

GetParams() {
    # convert parameters $@ suitable for 'args'
    printf -v params ',"%s"' "$@"
    params=${params#,}
}

AddOwnSettings() {
    [ -e "$own_settings_file" ] && cat "$own_settings_file" >> "$settings_file"
}

MakeSureSettingsJsonExists() {
    [ -e "$settings_file" ] && return   # don't overwrite existing settings.json

    cat <<EOF > "$settings_file"
{
    "launch": {
        "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug a script",
            "cwd": "\${env:PWD}",
            "program": "\${file}",
            "args": []                   $special_string
        }
        ]
    },
    "bashIde.explainshellEndpoint":      "http://localhost:5000"
EOF
    AddOwnSettings                   # Add your own settings from own-settings.json
    echo "}" >> "$settings_file"     # Finalize the settings.json file.
}

AddNewParameters() {
    [ "$1" ] || return

    GetParams "$@"

    # File settings.json exists, so check 'bide' compatibility first.
    grep "$special_string" "$settings_file" >/dev/null || DIE "sorry, '$settings_file' does not contain the special bashdb launch configuration"

    # Add parameters via the 'args' field in settings.json.
    # sed -i "$settings_file" -E -e "s|^([ ]+\"args\":[ ]+)\[[^]]*\]|\1[$params]|"
    ModifyParameters "$params"
}

CleanUp() { ModifyParameters "" ; }

ModifyParameters() {
    local para="$1"
    local sep

    for sep in "|" "_" "?" "/" ; do
        case "$para" in
            *"$sep"*) ;;
            *) sed -i "$settings_file" -E -e "s$sep^([ ]+\"args\":[ ]+)\[[^]]*\]$sep\1[$para]$sep"
               return 0
               ;;
        esac
    done
    DIE "parameter problem!"
}

IdeDebugBash() {
    AddNewParameters "$@"

    # Run vscodium.
    local params=(--password-store=basic)                   # needed?
    [ "$1" ] && params+=(--wait)                            # wait for the debugging session to end
    [ "$bash_file_to_debug" ] || params+=(--new-window)
    [ "$bash_file_to_debug" ] && params+=("$bash_file_to_debug")
    $app "${params[@]}"                                     # no parameters, just start vscodium
    return $?
}

InstanceCheck() { ps -C $app >/dev/null && DIE "sorry, '$progname' supports only one instance of '$app'." ; }

echo2()  { echo -e "$@" >&2 ; }
Color2() { local color="$1"; shift; echo2 "${!color}""$@""${RESET}"; }
DIE()    { Color2 RED "==> $progname: error: $1\n"; Usage 1; }
Exit()   { CleanUp; exit "$1"; }

Usage() {
    echo2 -n "$GREEN"
    cat <<EOF >&2
$progname - bash IDE integrating:
    * code or vscodium
    * bashdb
    * bash-ide extension
    * shellcheck
Usage: $progname [$progname-options] [--] script-file [script-parameters]
where
  ${progname}-options:
    -c, --config        Create a new settings.json file.
                        Note: the existing settings.json is automatically backed up.
    -h, --help          This help.
  script-file:          The bash script to be debugged.
  script-parameters:    Parameters for the script-file.

Tip: Use '--' before script-file to stop detecting $progname-options.

EOF
    echo2 -n "$RESET"
    [ "$1" ] && Exit "$1"
}

BideParameters() {
    local args=("$@")
    while true ; do
        case "$1" in
            -c | --config)
                dom=$(date +%d)
                if [ -e "$settings_file" ] ; then
                    echo2 "==> Backup: $settings_file  ->  $settings_file.$dom.bak"
                    rm -f "$settings_file".$dom.bak
                    mv "$settings_file" "$settings_file".$dom.bak
                fi
                MakeSureSettingsJsonExists
                ;;
            --cleanup)
                Exit 0
                ;;
            --no-instance-check)     # internal
                instance_check=no
                ;;
            --dump-options)          # internal
                echo "-c --config --cleanup --no-instance-check --dump-options -h --help"
                Exit 0
                ;;
            -h | --help)
                Usage 0
                ;;
            --)
                shift
                [ "$1" ] || DIE "command line '$0 ${args[*]}' includes no bash script to debug!"
                bash_file_to_debug="$1"
                shift
                prog_args=("$@")
                break
                ;;
            -*)
                DIE "unsupported option '$1'"
                ;;
            *)
                bash_file_to_debug="$1"
                shift
                prog_args=("$@")
                break
                ;;
        esac
        shift
    done
}

Main() {
    # Vscodium that supports bash debugging.
    # Delivers app parameters by changing 'args' in settings.json.

    local -r progname=${0##*/}

    local -r RED=$'\e[0;91m'         # starts this foreground text color
    local -r GREEN=$'\e[0;92m'
    local -r RESET=$'\e[0m'          # back to normal colors

    local app=""
    local appconfdir=""

    # Currently only these apps are supported:
    local APPS_SUPPORTED=(
        code
        codium
    )
    declare -A APP_CONFIGDIRS=(
        [code]="Code - OSS"
        [codium]="VSCodium"
    )
    [ -e "/etc/$progname.conf" ] && source "/etc/$progname.conf"

    for app in "${APPS_SUPPORTED[@]}" ; do
        if [ -x "/bin/$app" ] ; then
            appconfdir="${APP_CONFIGDIRS[$app]}"
            break
        fi
    done
    [ "$appconfdir" ] || DIE "none of '${APPS_SUPPORTED[*]}' is installed?"

    local -r settings_file="$HOME/.config/$appconfdir/User/settings.json"
    local -r own_settings_file="$HOME/.config/$appconfdir/User/own-settings.json"
    local -r special_string="# 'bide' will overwrite only the parameter list on this line"
    local dom=""
    local params=""
    local instance_check=yes
    local bash_file_to_debug=""           # the bash script to debug
    local prog_args=()                    # parameters for $bash_file_to_debug

    MakeSureSettingsJsonExists
    CleanUp
    BideParameters "$@"
    [ $instance_check = yes ] && InstanceCheck
    IdeDebugBash "${prog_args[@]}"

    Exit $?
}

Main "$@"
