#!/bin/bash

# Enables bash debugging for Visual Studio Code (vscodium or code).
# The debugger is bashdb.
# The parameters for the debuggee will be delivered via 'args' of the launch configuration in settings.json.

GetParams() {
    # convert parameters suitable for 'args'
    local arg
    for arg in "$@" ; do
        params+=",\"$arg\""
    done
    params=${params#,}
}

AddOwnSettings() {
    if [ -e "$own_settings_file" ] ; then
        cat "$own_settings_file" >> "$settings_file"
    fi
}

CreateSettingsJson() {
    [ -e "$settings_file" ] && return   # don't overwrite existing settings.json

    cat <<EOF > "$settings_file"
{
    "launch": {
        "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug a script",
            "cwd": "\${env:PWD}",
            "program": "\${file}",
            "args": [$params]            $special_string
        }
        ]
    },
    "bashIde.explainshellEndpoint":      "http://localhost:5000"
EOF
    AddOwnSettings                   # Add your own settings from own-settings.json
    echo "}" >> "$settings_file"     # Finalize the settings.json file.
}

AddNewParameters() {
    [ "$1" ] || return

    GetParams "$@"

    # File settings.json exists, so check 'bide' compatibility first.
    grep "$special_string" "$settings_file" >/dev/null || DIE "sorry, '$settings_file' does not contain the special bashdb launch configuration"

    # Add parameters via the 'args' field in settings.json.
    # sed -i "$settings_file" -E -e "s|^([ ]+\"args\":[ ]+)\[[^]]*\]|\1[$params]|"
    ModifyParameters "$params"
}

CleanUp() { ModifyParameters "" ; }

ModifyParameters() {
    sed -i "$settings_file" -E -e "s|^([ ]+\"args\":[ ]+)\[[^]]*\]|\1[$1]|"
}

IdeDebugBash() {
    CreateSettingsJson
    AddNewParameters "$@"

    # Run vscodium.
    local opts=""
    [ "$1" ] && opts="--wait"                           # wait for the debugging session to end
    [ "$bash_file_to_debug" ] || opts+=" --new-window"

    if [ "$bash_file_to_debug" ] ; then
        $app $opts "$bash_file_to_debug"
    else
        $app $opts                                      # no parameters, just start vscodium
    fi
    return $?
}

InstanceCheck() { ps -C $app >/dev/null && DIE "sorry, '$progname' supports only one instance of '$app'." ; }

echo2()  { echo -e "$@" >&2 ; }
Color2() { local color="$1"; shift; echo2 "${!color}""$@""${RESET}"; }
DIE()    { Color2 RED "==> $progname: error: $1\n"; Usage 1; }
Exit()   { CleanUp; exit "$1"; }

Usage() {
    echo2 -n "$GREEN"
    cat <<EOF >&2
$progname - bash IDE integrating:
    * vscodium or code
    * bashdb
    * bash-ide extension
    * shellcheck
Usage: $progname [$progname-options] script-file [script-parameters]
where
  ${progname}-options:
    -c, --config        Create a new settings.json file.
                        Note: the existing settings.json is automatically backed up.
    -h, --help          This help.
  script-file:          The bash script to be debugged.
  script-parameters:    Parameters for the script-file.
EOF
    echo2 -n "$RESET"
    [ "$1" ] && Exit "$1"
}

Main() {
    # Vscodium that supports bash debugging.
    # Delivers app parameters by changing 'args' in settings.json.

    local -r progname=${0##*/}

    local -r RED=$'\e[0;91m'         # starts this foreground text color
    local -r GREEN=$'\e[0;92m'
    local -r RESET=$'\e[0m'          # back to normal colors

    local app=""
    local appconfdir=""

    # Currently only these apps are supported:
    local APPS_SUPPORTED=(codium code)
    declare -A APP_CONFIGDIRS=(
        [codium]="VSCodium"
        [code]="Code - OSS"
    )
    [ -e "/etc/$progname.conf" ] && source "/etc/$progname.conf"

    for app in "${APPS_SUPPORTED[@]}" ; do
        if [ -x "/bin/$app" ] ; then
            appconfdir="${APP_CONFIGDIRS[$app]}"
            break
        fi
    done
    [ "$appconfdir" ] || DIE "none of '${APPS_SUPPORTED[*]}' is installed?"

    local -r settings_file="$HOME/.config/$appconfdir/User/settings.json"
    local -r own_settings_file="$HOME/.config/$appconfdir/User/own-settings.json"
    local -r special_string="# 'bide' will overwrite only the parameter list on this line"
    local bash_file_to_debug=""
    local dom=""
    local params=""

    CleanUp

    while true ; do
        case "$1" in
            -c | --config)
                dom=$(date +%d)
                if [ -e "$settings_file" ] ; then
                    echo2 "==> Backup: $settings_file  ->  $settings_file.$dom.bak"
                    rm -f "$settings_file".$dom.bak
                    mv "$settings_file" "$settings_file".$dom.bak
                fi
                CreateSettingsJson
                ;;
            --cleanup)
                Exit 0
                ;;
            -h | --help)
                Usage 0
                ;;
            -*)
                DIE "unsupported option '$1'"
                ;;
            *)
                bash_file_to_debug="$1"
                shift
                break
                ;;
        esac
        shift
    done

    InstanceCheck
    IdeDebugBash "$@"

    Exit $?
}

Main "$@"
