#!/bin/bash

Main() {
    # Like pacman, but use sudo only if needed.

    # Bash completion: add the following lines (uncommented!) to
    # file /usr/share/bash-completion/completions/pacman-sudo-internal:
    #    source /usr/share/bash-completion/completions/pacman
    #    complete -F _pacman pacman-sudo-internal

    local root_needed="error: you cannot perform this operation unless you are root."
    local out
    local retval

    out=$(LANG=C /usr/bin/pacman "$@" 2>&1)
    retval=$?

    case "$out" in
        "$root_needed") sudo /usr/bin/pacman "$@" ;;
        "")             return $retval ;;
        *)              printf "%s\n" "$out" ; return $retval ;;
    esac
}

Main "$@"
