#!/bin/bash

# A pacman with additionalfeatures for update, and downgrade support.

echo2() { echo "$@" >&2 ; }
DIE()   { echo2 "$progname: error: $1" ; Usage 1 ; }
WARN()  { echo2 "$progname: warning: $1" ; MayExit "$2" ; }
MayExit() { [ -n "$1" ] && exit $1 ; }

Usage() {
    cat <<EOF

Usage:
   $progname
   $progname <special-option>
   $progname <special-option2>
   $progname <pacman-options>

<special-option>:
   -Syu                Updates packages with additional features.
   -Syyu               Like -Syu, with extra --refresh (see 'man pacman').
   --paru              Like -Syu, also updates AUR packages using paru.
   --yay               Like -Syu, also updates AUR packages using yay.
   --aur               Like --paru or --yay (tried in this order).

Notes:
   - If no arguments are provided, -Syu is assumed.
   - The <special-option> $msgtail
   - Otherwise works like 'pacman <pacman-options>' *without* any additional features.

<special-option2>:
   --wait-enter        Waits for user to press the Enter key to continue.
   --dg, --downgrade   (Experimental) Downgrades given Arch or EndeavourOS packages.

Notes2:
   - Options --downgrade and --dg require one or more package names.

EOF
    MayExit "$1"
}

normal_pacman_cmd()      { /usr/bin/pacman-sudo-internal "$@" ; }
special_update_helper()  { helper="/usr/bin/sudo -u $LOGNAME $helper" ; special_update ; }

eos-virtualbox-check() {
    # if installed, check versions of virtualbox-ext-oracle vs. virtualbox
    local versions ver_app ver_ext
    readarray -t versions <<< $(LANG=C paru -Si virtualbox virtualbox-ext-oracle | grep "^Version" | awk '{print $NF}')
    if [ ${#versions[@]} -eq 2 ] ; then
        ver_app=${versions[0]%-*}
        ver_ext=${versions[1]%-*}
        if [ "$ver_app" != "$ver_ext" ] ; then
            ignore_aur="--ignore virtualbox-ext-oracle"
            WARN "virtualbox $ver_app and virtualbox-ext-oracle $ver_ext: no version match."
            echo2 ""
        fi
    fi
}

special_update() {
    cat <<EOF
A pacman wrapper with additional package update features.

Additional features:
   - db lock file check
   - nvidia & kernel update check
   - virtualbox vs. virtualbox-ext-oracle version macth check
   - update keyrings first
   - 'sync' at end

EOF
    local ignore_aur=""
    eos-virtualbox-check
    local -r lockfile=/var/lib/pacman/db.lck logfile="$HOME/.cache/$progname.log"
    if [ -e $lockfile ] && fuser $lockfile &>/dev/null ; then
        WARN "$lockfile is in use." 1
    fi
    # Build the command for sudo:
    local sudo_cmd
    [ -e $lockfile ] && sudo_cmd=("rm -f $lockfile")
    eos-kernel-nvidia-update-check --needed
    [ $? -eq 2 ] && sudo_cmd=("eos-kernel-nvidia-update-check")
    sudo_cmd+=("/usr/bin/pacman $db_opt --needed archlinux-keyring endeavouros-keyring && /usr/bin/pacman -Su")   # the main stuff
    [ "$helper" != "/usr/bin/pacman" ] && sudo_cmd+=("$helper -Sua $ignore_aur")
    sudo_cmd+=("sync")
    # Handle the sudo command:
    local -r last_cmd="${sudo_cmd[@]: -1}"
    sudo_cmd=($(printf "%s\n" "${sudo_cmd[@]}" | sed "/^$last_cmd$/!s/$/ \&\&/" ))  # see 'info sed', chapter 6.4 for details!
    echo "$(date +%Y%m%d-%H%M): ${sudo_cmd[@]}" >> "$logfile"
    [ "$show_cmd" = "yes" ] && echo "sudo bash -c \"${sudo_cmd[*]}\""
    sudo bash -c "${sudo_cmd[*]}"
    return $?
}

pacman_ext() {
    local -r progname="$(basename "$0")"   # $progname used by various functions here
    local helper=/usr/bin/pacman           # $helper used by special_update()
    local db_opt="-Sy"                     # $db_opt used by special_update()
    local opt
    local -r msgtail="must be used as the *only* parameter on the command line."
    case "$2" in
        "") case "$1" in    # additional features
                --aur)                            helper=/usr/bin/paru
                                                  [ -x $helper ] || helper=/usr/bin/yay
                                                  [ -x $helper ] || DIE "AUR helpers 'paru' or 'yay' not found."
                                                  special_update_helper
                                                  return $?
                                                  ;;
                --paru | --yay)                   helper=/usr/bin/${1#*--}
                                                  [ -x $helper ] || DIE "AUR helper '$helper' not found."
                                                  special_update_helper
                                                  return $?
                                                  ;;
                -Syu|-Suy|-ySu|-yuS|-uSy|-uyS|"") special_update
                                                  return $?
                                                  ;;
                -Syyu)                            db_opt="-Syy"
                                                  special_update
                                                  return $?
                                                  ;;
            esac
            ;;
        *)  case "$1" in
                --dg | --downgrade) shift ; eos-downgrade "$@" ; return $? ;;
            esac
            ;;
    esac
    for opt in "$@" ; do
        case "$opt" in
            --aur | --paru | --yay) DIE "special option '$opt' $msgtail" ;;  # should have been handled above!
            -h | --help) Usage 0 ;;
        esac
    done
    normal_pacman_cmd "$@"
}

Main() {
    local wait_enter=no
    local show_cmd=no
    local retval

    while true ; do
        case "$1" in
            --wait-enter) wait_enter=yes ; shift ;;  # e.g. for pacseek
            --show-cmd)  show_cmd=yes ; shift ;;
            *) break ;;
        esac
    done

    pacman_ext "$@"
    retval=$?

    [ "$wait_enter" = "yes" ] && read -p "Press ENTER: " >&2

    return $retval
}
Main "$@"
