#!/bin/bash
#
# Show only the latest Arch news headline.
# Useful e.g. for 'kalu' news.conf.
#
# Usage: $0 [days]
# where
#     days    Show headlines that are no more that 'days' old AND
#             the related package in the headline is currently installed.
# Without 'days' show only the latest available headline.

DIE() {
    echo "Error: $1" >&2
    exit 1
}

LatestHeadlines() {
    local infofile="$1"
    grep 'title="View full article:' $infofile | sed -e 's|&gt;|>|g' -e 's|^.*">[ ]*||' -e 's|</a>$||'
}

LatestDates() {
    local infofile="$1"
    local tmp=$(mktemp)
    grep "timestamp" $infofile | sed -e 's|^.*">||' -e 's|</p>$||'    >> $tmp
    grep "</dt>"     $infofile | sed -e 's|^.*<dt>||' -e 's|</dt>$||' >> $tmp
    cat $tmp
    rm -f $tmp
}

LessThanDays() {
    local latestdate="$1"        # 2020-01-01
    local days="$2"              # nr of days

    local days_in_sec=$((days * 24 * 3600))
    local latestdate_in_sec=$(date --date="$latestdate" +%s)
    local curdate_in_sec=$(date +%s)

    if [ $((curdate_in_sec - days_in_sec)) -gt $latestdate_in_sec ] ; then
        return 1  # too old
    else
        return 0  # within day range
    fi
}

CheckHeadlines()  # show a headline only if the related package is installed and it is less than given days old
{
    local original="$1"
    local days="$2"
    local headlines headline
    local dates     date latestdate
    local pkgname ix matches
    local hlinfo=$(mktemp)

    wget -q -T 10 -O $hlinfo https://www.archlinux.org || DIE "fetching Arch news headlines failed"
    readarray -t headlines <<< "$(LatestHeadlines $hlinfo)"
    test "$original" = "yes" && {
        echo "${headlines[0]}" ; rm -f $hlinfo
        return
    }
    readarray -t dates     <<< "$(LatestDates     $hlinfo)"
    test ${#headlines[@]} -eq ${#dates[@]} || DIE "sorry, headlines do not match with their dates!!"
    rm -rf $hlinfo

    if [ -n "$headlines" ] ; then
        ix=0
        matches=0
        for headline in "${headlines[$ix]}" ; do
            date="${dates[$ix]}"
            LessThanDays "$date" $days && {
                pkgname="$(echo "$headline" | awk '{print $1}')"       # ASSUME: the first word is the package name!
                pkgname="${pkgname%%>*}"                               # remove possible trailing ">=..."
                pacman -Q "$pkgname" >& /dev/null && {
                    echo "    $date : $headline"
                    ((matches++))
                }
            }
            ((ix++))
        done
        if [ $matches -ne 0 ] ; then
            echo "See https://www.archlinux.org for more info about the issue(s)." >&2
            xdg-open https://www.archlinux.org >&/dev/null
        else
            echo "No news for you about Arch issues in $days days." >&2
        fi
    fi
}

Main()
{
    local days="$1"
    local original=no

    test -z "$days" && original=yes

    CheckHeadlines "$original" "$days"
}

Main "$@"
