#!/bin/bash

Main()
{
    local commands=(
        "cd /usr/share/app-info/xmls ;"
        "gunzip community.xml.gz ;"
        "cp community.xml community.xml.foobar ;"
        "sed -i community.xml -e 's|[<]em>not[<]/em>|*not*|' ;"
        "diff -q community.xml community.xml.foobar && printf '\n**** You may uninstall fix-archlinux-appstream-data\n' ;"
        "rm -f community.xml.foobar ;"
        "gzip community.xml"
    )
    su -c "${commands[*]}"
}

Main "$@"
