#!/bin/bash

# Enhance CDPATH and cd:
#   - if multiple matches, make round robin with them

DIE() {
    [ -n "$1" ] && echo "$@" >&2
    exit 1
}

ncd() {
    local newdir="$1"
    local dir matches=() ix count

    for dir in ${CDPATH//:/ } ; do
        [ -d "$dir/$newdir" ] && matches+=("$dir/$newdir")
    done
    count=${#matches[@]}
    case "$count" in
        0) dir="$newdir" ;;         # no match in CDPATH
        1) dir="${matches[0]}" ;;   # one match in CDPATH
        *)
            # many matches in CDPATH
            for ((ix=0; ix < count; ix++)) ; do
                [ "${matches[$ix]}" -ef "$PWD" ] && break
            done
            [ $ix -ge $((count-1)) ] && ix=0 || ((ix++))
            echo "($((ix+1))/$count)" >&2
            dir="${matches[$ix]}"
            ;;
    esac

    echo "$dir"
}

Main()
{
    case "$1" in
        "")          ;;
        .* | /* | -) echo "$@" ;;
        -[LP@])      echo "$@" ;;   # ncd does not support options currently
        -*)          echo "$@" ;;   # error
        *)           ncd  "$@" ;;
    esac
}

Main "$@"
