#!/bin/bash

# Enhance CDPATH and cd:
#   - if multiple matches, use fzf to select

AddUniqueMatch() {
    local d="$1"
    local m n
    for m in "${matches[@]}" ; do
        [ "$d" -ef "$m" ] && return
    done
    matches+=("$d")
}

ncd() {
    local newdir="$1"
    local dir matches=() ix count

    if [ -d "./$newdir" ] ; then
        dir="./$newdir"                 # prefer direct subdir always
    else
        for dir in ${CDPATH//:/ } ; do
            [ -d "$dir/$newdir" ] && AddUniqueMatch "$dir/$newdir"
        done
        count=${#matches[@]}
        case "$count" in
            0)  dir="$newdir" ;;         # no match in CDPATH
            1)  dir="${matches[0]}" ;;   # one match in CDPATH
            *)
                # many matches in CDPATH, select with fzf
                dir=$(printf "%s\n" "${matches[@]}" | fzf  --no-separator --no-info --height=$((count+1)))
                [ -n "$dir" ] || dir=.
                ;;
        esac
    fi
    echo "$dir"
}

Main() {
    case "$1" in
        "")          ;;
        .* | /* | -) echo "$@" ;;   # for builtin cd
        -*)          echo "$@" ;;   # options to builtin cd
        *)           ncd  "$@" ;;
    esac
}

Main "$@"
