#!/bin/bash

DIE() {
    echo "$progname: error: $1"
    exit 1
}

pushd() { command pushd "$@" >/dev/null || DIE "'pushd $*' failed." ; }
popd()  { command popd  "$@" >/dev/null || DIE "'popd $*' failed." ; }

Main()
{
    local progname="$(basename "$0")"
    local folder xx

    pushd _BUILD_

    for folder in $(/usr/bin/ls -1) ; do
        if [ -r $folder/assets.conf ] ; then
            pushd $folder
            printf "\n====> $folder\n\n"

            assets.make -nn

            if [ 0 -eq 1 ] ; then
                # fix some package names if they have 'epoch=' in PKGBUILD

                xx="$(/usr/bin/ls -1 vivaldi-widevine-now-[0-9].*.zst 2>/dev/null)"
                if [ -n "$xx" ] ; then
                    mv $xx     $(echo "$xx"     | sed 's|\(-now-[0-9]\)\.|\1:|')
                    mv $xx.sig $(echo "$xx".sig | sed 's|\(-now-[0-9]\)\.|\1:|')
                fi
            fi
            popd
        fi
    done
    popd
}

Main "$@"
