#!/bin/bash
#
# Check that all source folders are up to date.

DIE() {
    echo "$progname: error: $1"
    exit 1
}

pushd() { /bin/pushd "$@" >/dev/null || DIE "'pushd $*' failed." ; }
popd()  { /bin/popd  "$@" >/dev/null || DIE "'popd $*' failed." ; }

_git_check() {
    local ret=0
    printf "====> %-30s: " "$folder"
    pushd "$PWD/$folder"               # using $PWD because $CDPATH may confuse 'cd' !
    git pull || ret=$?
    popd
    return $ret
}

Main()
{
    local progname="$(basename "$0")"
    local folder

    for folder in $(/usr/bin/ls -1) ; do
        [ -e $folder/.skip-auto-update ] && continue
        [ -d $folder/.git ] || continue
        [ -L $folder/.git ] && continue

        if [ -e $folder/.ask-auto-update ] ; then
            read -p "want to check folder '$folder' (y/N)? " >&2
            case "$REPLY" in
                [yY]*) which logstuff >& /dev/null && logstuff on ;;
                *) continue ;;
            esac
        fi

        _git_check
    done
}

Main "$@"
