#!/bin/bash

DIE() {
    echo "$1" >&2
    [ -n "$2" ] && echo "  ==> $2" >&2
    exit 1
}

xbacklight() {
    local error="$FUNCNAME: error in values of variable AUTO_BRIGHTNESS_TIMED_VALUES"

    case "$1" in
        auto)
            local curr=$(brightness-intel)
            local hour=$(/usr/bin/date +%H)
            local new=""
            local hourspec h1 h2 value ix

            source /etc/xbacklight.conf || DIE "$FUNCNAME: cannot read /etc/xbacklight.conf"

            for ((ix=0; ix < ${#AUTO_BRIGHTNESS_TIMED_VALUES[@]}; )) ; do
                hourspec="${AUTO_BRIGHTNESS_TIMED_VALUES[$((ix++))]}"
                value="${AUTO_BRIGHTNESS_TIMED_VALUES[$((ix++))]}"

                [ -n "$value" ] || DIE "$error" "value = ''"

                case "$hourspec" in
                    "")
                        DIE "$error" "hourspec = ''"
                        ;;
                    other)
                        new="$value"
                        break
                        ;;
                    *-*)
                        h1=${hourspec%-*}
                        h2=${hourspec#*-}
                        if [ $hour -ge $h1 ] && [ $hour -le $h2 ] ; then
                            new="$value"
                            break
                        fi
                        ;;
                    [0-9]*)
                        if [ $hour -eq $hourspec ] ; then
                            new="$value"
                            break
                        fi
                        ;;
                esac
            done
            [ -n "$new" ] || DIE "$error" "new = ''"

            if [ $curr -ne $new ] ; then
                brightness-intel =$new
                echo "$curr --> $new" >&2
            fi
            ;;
        service)
            local dir="$HOME/.config/systemd/user"
            local suffix

            mkdir -p "$dir/OLD"
            for suffix in timer service ; do
                [ -r "$dir"/xbacklight.$suffix ] && mv -f "$dir"/xbacklight.$suffix "$dir"/OLD/
                cp /etc/skel/eos-brightness/xbacklight.$suffix "$dir"
            done
            systemctl --user daemon-reload
            echo "Service initialized." >&2
            ;;
        *)
            brightness-intel "$@"
            ;;
    esac
}

xbacklight "$@"
