#!/bin/bash
#
# Author: manuel (see https://forum.endeavouros.com)
#
# Manipulate the PKGBUILD of a meta package.
#    
# Fetch the PKGBUILD of the given meta package.
# Use the deps of the currently installed meta-package or deps in the fetched PKGBUILD.
# Find dep-package names from a given meta package, e.g. plasma-meta: discover, kde*, etc.
# Manipulate the "depends" array if the meta package by adding or removing a package.
# Build and install the new meta package with: makepkg
#

DIE() {
    echo "Error: $1" >&2
    [ -n "$workdir" ] && echo "See folder '$workdir' for more details" >&2
    echo "" >&2
    Usage
    exit 1
}

Info() {
    echo "---> Info: $1" >&2
}

IsInstalledPkg() {
    pacman -Q "$1" >& /dev/null
}

GetDepends() {
    # Get the dependencies of the meta-package from the fetched PKGBUILD.
    source PKGBUILD
    depends_mod=("${depends[@]}")
}

PutDepends() {
    # Make the PKGBUILD use new dependencies.

    # rename old 'depends' array variable
    sed -i PKGBUILD \
        -e "s|^depends=(|_depends_replaced_=(|"

    local newval=$( printf "depends=(\n%s\n)\n" "$(printf "    '%s'\n" "${depends_mod[@]}")" )
    local tmpname=$(mktemp -u PKGBUILD.XXXXXXXX)
    mv PKGBUILD $tmpname

    # echo "$newval" >&2                 # TESTING !!

    echo "$newval" > PKGBUILD
    cat $tmpname >> PKGBUILD
    rm -f $tmpname
}

AddDepends() {
    local dep
    for dep in "$@" ; do
        Info "adding dependency '$dep' to '$meta'"
        depends_mod+=("$dep")
    done
}

RemoveDepends() {
    local sub dd
    local new_depends=()

    for dd in "${depends_mod[@]}" ; do
        for sub in "$@" ; do
            [ "$sub" = "$dd" ] && break
        done
        if [ "$sub" = "$dd" ] ; then
            IsInstalledPkg "$sub"
            case "$?" in
                0)
                    Info "removing '$sub' from meta package '$meta'"
                    must_delete_meta_temporarily=yes
                    ;;
                *)
                    IsInstalledPkg "$meta" && Info "dependency '$sub' of fetched '$meta' is not currently installed"
                    ;;
            esac
        else
            new_depends+=("$dd")
        fi
    done
    depends_mod=("${new_depends[@]}")
}

RemoveIfInstalled() {
    local pkg="$1"

    [ "$must_delete_meta_temporarily" = "yes" ] || return

    IsInstalledPkg "$pkg"
    case "$?" in
        0)
            Info "uninstalling meta package '$pkg':"
            sudo pacman -Rdd "$pkg" || DIE "failed to remove package '$pkg'"
            ;;
        *)
            #Info "'$pkg' is not currently installed."
            ;;
    esac
}

BuildInstall() {
    local version_suffix="updated by PKGBUILD"
    if [ "$version_suffix" = "updated by PKGBUILD" ] ; then
        version_suffix="12345"
    fi
    sed -i PKGBUILD \
        -e "s|^\(pkgver=.*\)$|\1.eos.$version_suffix|"

    # A problem with meta packages:
    #   "Users cannot remove meta package dependencies without having to uninstall the meta package itself."
    # See https://wiki.archlinux.org/index.php/Meta_package_and_package_group#Difference_between_meta_package_and_package_group

    RemoveIfInstalled "$meta"
    Info "Building package '$meta' and installing (using --noconfirm):"

    makepkg --clean --nodeps --force --syncdeps --install --noconfirm \
        || DIE "failed to build and install new meta-package '$meta'"
}

Cleanup() {
    cd $origdir
    rm -rf $workdir
}

ParamCheck() {
    [ -n "$meta" ] || DIE "meta-package missing"
    [ -n "$1" ]    || DIE "dep-package(s) missing"

    local xx
    for xx in "$@" ; do
        case "$xx" in
            -*) removes+=("${xx:1}") ;;
            +*) adds+=("${xx:1}") ;;
            *) DIE "add or remove '$xx'? Prepend with + or -" ;;
        esac
    done
}

CreateWorkEnv() {
    workdir=$(mktemp -d /tmp/$progname.XXXXX)
    cd $workdir
    yay -G "$meta" >/dev/null || {
        Cleanup
        DIE "problem fetching the PKGBUILD of meta-package '$meta'"
    }
    cd "$meta"
    [ -r PKGBUILD ] || DIE "file 'meta/PKGBUILD' is not found"
    [ -n "$(grep '^depends=(' PKGBUILD)" ] || DIE "$meta/PKGBUILD has no 'depends' array, please check!"

    # Now we are in $workdir/$meta and have ./PKGBUILD
}

Main()
{
    local meta="$1"
    local progname=metamgr
    local workdir=""
    local origdir="$PWD"
    local adds=() removes=()
    local must_delete_meta_temporarily=no    # if any dep-package is removed, temporarily delete current meta package and create new
    local depends_mod
    shift

    case "$meta" in
        -h | --help | "") Usage ; return ;;
    esac

    ParamCheck "$@"
    CreateWorkEnv

    GetDepends

    AddDepends    "${adds[@]}"
    RemoveDepends "${removes[@]}"

    PutDepends
    BuildInstall && Cleanup
}

Usage() {
    cat <<EOF
Usage:
    $progname meta-package {prefix}dep-package [{prefix}dep-package ...]
    $progname command help-option

First usage syntax:
    prefix
        +   Adds the given dep-package as a dependency for the given meta-package.
        -   Removes the given dep-package from the dependencies of the meta-package.

    dep-package
        A dependency package for the given meta-package.

    meta-package
        A package that has specifies required dependency packages.

Second usage syntax:
    help-option
        -h | --help
            This help.

Example:
    # For plasma-meta: remove discover, add kaffeine
    $progname plasma-meta -discover +kaffeine

EOF
}

Main "$@"
