#!/bin/bash

# EndeavourOS news

ShowMsg() {
    # usage: ShowMsg [--no-yad] "msg" [other-parameters-for-yad]

    local show_yad=yes
    test "$1" = "--no-yad" && { show_yad=no ; shift ; }
    local msg="$1"
    shift

    echo "$msg" >&2

    if [ "$show_yad" = "yes" ] ; then
        GDK_BACKEND=x11 \
        yad --form --text="$msg" --title="${progname} message" --button=yad-quit \
            --width=300 --height=200 \
            --window-icon=/usr/share/endeavouros/EndeavourOS-icon.png \
            --image=user-info \
            "$@"
    fi
}

ShowMsgError() { ShowMsg "$@" --image=error ; }

DIE() {
    ShowMsgError "$@"
    exit 1
}

ShowUserNews() { xdg-open $newsfileshow ; }

GetEosNews() {
    local template="20[0-9][0-9]/[0-1][0-9]/[0-3][0-9]-[0-2][0-9]:[0-5][0-9][ ]*"  # works for only this century...
    eosnews="$(wget -q -O- --timeout 5 $newsfile)"
    case "$eosnews" in
        "") DIE "$FUNCNAME failed" ;;
        *)
            eosnews="$(echo "$eosnews" | grep "^$template" | sed 's/|//')"
            readarray -t eosnewsarr <<< $(echo "$eosnews")
            ;;
    esac
}

UpdateUserconf() {
    local newest="$(GetNewsDate 0)"
    if [ "${newest::2}" != "20" ] ; then
        DIE "$FUNCNAME: config file saving corruption!"
    fi
    echo "$newest" > "$userconf"
}

GetNewsDate() { local ix="$1" ; echo "${eosnewsarr[$ix]}" | awk '{print $1}' ; }

UserHasNews() {
    local where
    local lastix=$(( ${#eosnewsarr[@]} - 1))
    local latest_seen="$(GetNewsDate $lastix)"
    local lastseen_ix=$lastix
    local ix

    if [ -r "$userconf" ] ; then
        latest_seen="$(cat "$userconf")"
        where=config
    else
        where=news
    fi
    if [ "${latest_seen::2}" != "20" ] ; then
        test -r "$userconf" && mv -f "$userconf" "$userconf".bak
        echo "$latest_seen" > "$userconf"
        DIE "$FUNCNAME: $where file reading corruption! Resetting config file."
    fi
    if [ "$(GetNewsDate 0)" = "$latest_seen" ] ; then
        return 1
    else
        return 0
    fi
}

Main()
{
    local progname=notme
    local userconf="$HOME/.config/${progname}-latest-seen.conf"
    local newsfile=https://raw.githubusercontent.com/manuel-192/m-m/master/PKGBUILDs/${progname}/README.md
    local newsfileshow=https://github.com/manuel-192/m-m/blob/master/PKGBUILDs/${progname}/README.md
    local eosnewsarr
    local eosnews
    
    GetEosNews

    UserHasNews && {
        ShowUserNews
        UpdateUserconf
    } || {
        ShowMsg --no-yad "No news."
    }
}

Main "$@"
