#!/bin/bash

Main() {
    # NOTE: $1 cannot include colons !!!
    case "$1" in
        https://*) local url="$1" ;;
        *)         local url="https://$1" ;;
    esac
    echo git clone "'$url'"
    git clone "$url"
}

Main "$@"
