#!/bin/bash

FirstAppOf() {
    local -n app_ret="$1"
    shift
    local aaa               # bash bug? cannot make 'app_ret' as the for loop parameter?
    for aaa in "$@" ; do
        type "$aaa" >& /dev/null && { app_ret="$aaa"; return 0 ; }
    done
    return 1
}
RunFirstApp() {
    local apps="$1"
    local app=""
    if FirstAppOf app $apps ; then
        shift             # skip "$apps"
        $app "$@"
    fi
}

who-needs() {
    local pkg="$1"
    if expac -Q %n "$pkg" &> /dev/null ; then
        RunFirstApp pactree --reverse "$pkg"
    else
        return
        if paru -Si "$pkg" &> /dev/null ; then
            echo "Sorry, not implemented yet." >&2
        else
            echo "Package '$pkg' not found."
        fi
    fi
}
deps-of() {
    local pkg="$1"
    if expac -Q %n "$pkg" &> /dev/null ; then
        RunFirstApp pactree --depth 1 "$pkg"
    else
        LANG=C paru -Si "$pkg" | grep -w "^Depends On" | sed 's|^Depends On[ ]*:[ ]*||'
    fi
}
who-owns() {
    local file="$1"
    # pkgfile needs pkgfile-update.timer being enabled and started
    pkgfile "$file"
    # pkgfile "$file" || paru -Qo "$file" 2> /dev/null || paru -F "$file" | sed 's|^    |    /|'
}

Usage() {
    cat <<EOF >&2
Usage: $progname [params]
Params:
  --who-needs <pkgname>     Show which packages need the given package.
  --deps-of <pkgname>       Show the dependencies of the given package.
  --who-owns <file>         Show which package(s) include <file>.
  --tui-install             Install packages (TUI).
  --tui-remove              Uninstall packages (TUI).
  -h, --help                This help.

Without options "$defaultcmd" is executed.

If other params exist, pacman-ext is executed.
EOF
    exit 0
}

Main() {
    local progname="${0##*/}"
    local defaultcmd=""

    FirstAppOf defaultcmd paf pacman-ext paru yay pacman

    case "$1" in
        --tui-install | --tui-remove)
            RunFirstApp paf "$1"
            ;;
        --who-needs | --deps-of | --who-owns)
            ${1:2} "$2"
            ;;
        "")
            $defaultcmd
            ;;
        -h | --help)
            Usage
            ;;
        *)
            RunFirstApp "pacman-ext paru yay pacman" "$@"
            ;;
    esac
}

Main "$@"
