#!/bin/bash

# paccache wrapper
# - properly handle the default value for option -k/--keep
# - show the actual command and parameters unless option --show-command=no is used

HandleOpt_k() {  # option -k/--keep has an optional value
    kopt="$1"                                # -k or --keep
    local val sep=""
    local -r kd=3                            # default keep value
    [ "$2" ] && val="$2" || val=$kd          # default or given value
    [ "$kopt" = "--keep" ] && sep="="        # if long option, syntax to --keep=value
    args+=("$kopt$sep$val")
}

paccache_options_to_args() {
    local opts
    local sopts="a:c:dfhi:k::m:rquvVz"
    local lopts="dryrun,move:,remove,arch:,cachedir:,force,help,ignore:,keep::"
    lopts+=",min-atime:,min-mtime:,nocolor,null,quiet,uninstalled,verbose,version"

    # options for the local implementation!
    sopts+="s:"
    lopts+=",show-command:"

    opts="$(getopt -o=$sopts --longoptions $lopts --name "${FUNCNAME[0]}" -- "$@")" || exit 1
    eval set -- "$opts"

    local kopt    # will be assigned in HandleOpt_k

    while true ; do
        case "$1" in
            --)                 shift ; break ;;

            --move | -m)        args+=("$1" "$2"); shift ;;
            --arch | -a)        args+=("$1" "$2"); shift ;;
            --cachedir | -c)    args+=("$1" "$2"); shift ;;
            --ignore | -i)      args+=("$1" "$2"); shift ;;
            --keep | -k)        HandleOpt_k "$@";  shift ;;
            --min-atime)        args+=("$1" "$2"); shift ;;
            --min-mtime)        args+=("$1" "$2"); shift ;;
            --dryrun | -d)      args+=("$1") ;;
            --remove | -r)      args+=("$1") ;;
            --force | -f)       args+=("$1") ;;
            --help | -h)        args+=("$1") ;;
            --nocolor)          args+=("$1") ;;
            --null | -z)        args+=("$1") ;;
            --quiet | -q)       args+=("$1") ;;
            --uninstalled | -u) args+=("$1") ;;
            --verbose | -v)     args+=("$1") ;;
            --version | -V)     args+=("$1") ;;

            # additional options used by this local implementation:
            --show-command | -s) show_command="$2"; shift ;;   # $2 = "yes" or "no"
        esac
        shift
    done

    local target="$1"   # the first target package name, if given
    local -r cachedir=$(GetCacheDir)

    if [ "$target" ] ; then
        # check if the first target is actually a value for option --keep
        local pkgs=(${cachedir}"$target"-*)
        if [ "${pkgs: -2}" = "-*" ] ; then
            echo "==> $progname: error: target package name '$target' not found." >&2
            if [ "$kopt" ] && [ -z "${target//[0-9]/}" ] ; then   # is a number meant for --keep ?
                local msg="   -> Tip: if '$target' was meant for option $kopt, use syntax:"
                case "$kopt" in
                    -k)     echo "$msg $kopt$target" >&2 ;;
                    --keep) echo "$msg $kopt=$target" >&2 ;;
                esac
            fi
            exit 1
        fi
    fi
    args+=("$@")
    [ $show_command = yes ] && ShowCommand "${args[@]}"
 }

ShowCommand() {
    # show the command and its *real* parameters
    local arg
    local line=":: $progname "

    for arg in "$@" ; do
        if [ "${arg/ /}" = "$arg" ] ; then
            line+="$arg "                   # $arg includes no spaces
        else
            line+="'$arg' "                 # $arg includes spaces
        fi
    done
    echo "${line% }" >&2                    # don't show the trailing space
}

Main() {
    local -r progname=${0}
    local show_command=yes     # "yes" or "no", "no" should be the default for compatibility
    local args=(--verbose)
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || exit 1
    paccache_options_to_args "$@"
    /bin/paccache "${args[@]}"
}

Main "$@"
