#!/bin/bash

# - pacman -Sy
# - show updates and their descriptions
# - pacman -Su

Cmd() {
    [ $verbose = yes ] && echo "==>" "$@" >&2
    "$@"
}

show-updates-and-descriptions() {
    # local updates=$(pacman -Su --print-format '%n')
    local updates=$(pacman -Quq)
    if [ -n "$updates" ] ; then
        hook-update-description $updates
        return 0
    else
        echo "No updates." >&2
        return 0
    fi
}

Main() {
    case "$(id)" in
        *'(root)'* | *'(wheel)'*)
            ;;
        *)  echo "Sorry, must use elevated privileges." >&2
            return 1
            ;;
    esac
    local verbose=yes

    Cmd pacman -Sy
    Cmd show-updates-and-descriptions
    Cmd pacman -Su
    Cmd pacman -Qm
    Cmd eos-pacdiff
}

Main
