#!/bin/bash

# - pacman -Sy
# - show updates and their descriptions
# - pacman -Su

Cmd() {
    [ $verbose = yes ] && echo "==>" "$@" >&2
    "$@" || exit $?
}

show-updates-and-descriptions() {
    local updates=$(pacman -Su --print-format '%n')
    if [ -n "$updates" ] ; then
        local bannerline=$(printf "%.0s=" {1..70})
        echo "$bannerline"
        expac -Q '%n|%d' $updates | column -t -s'|' | sort
        echo $bannerline
        return 0
    else
        echo "Nothing to do." >&2
        exit 1
    fi
}

Main() {
    case "$(id)" in
        *'(root)'* | *'(wheel)'*)
            ;;
        *)  echo "Sorry, must use elevated privileges." >&2
            return 1
            ;;
    esac
    local verbose=yes

    Cmd pacman -Sy
    Cmd show-updates-and-descriptions
    Cmd pacman -Su
}

Main
