#!/bin/bash

# Package updater for EndeavourOS and Arch.
# Handles db lock file, keyrings, syncing, and optionally AUR with given AUR helper.

Options() {
    local opts
    local lopts="nvidia,helper:,min-free-bytes:,paru,yay,pacman,help"
    local sopts="h"

    opts="$(/usr/bin/getopt -o=$sopts --longoptions $lopts --name "$progname" -- "$@")" || {
        Options -h
        return 1
    }
    eval set -- "$opts"

    while true ; do
        case "$1" in
            --nvidia)
                if IsEndeavourOS ; then
                    nvidia=eos-kernel-nvidia-update-check
                else
                    echo "Sorry, option $1 works only in EndeavourOS. Option ignored." >&2
                fi
                ;;
            --min-free-bytes) min_free_bytes="$2" ; shift ;;
            --helper) helper="$2" ; shift ;;
            --paru | --yay | --pacman) helper="${1/--/}" ;;

            -h | --help)
                cat <<EOF >&2
Package updater for EndeavourOS and Arch
Handles:
- disk space check
- pacman db lock
- keyrings
- sync after update
and optionally
- AUR with given AUR helper
- Nvidia driver vs. kernel updates (only on EndeavourOS)

Usage: $progname [options]
Options:
  --help, -h         This help.
  --nvidia           Check also nvidia driver vs. kernel updates.
  --helper           AUR helper to use. Supported: yay, paru, pacman (=no AUR update). Default: pacman.
                     Others supporting option -Sua should work as well.
  --paru             Same as --helper=paru.
  --yay              Same as --helper=yay.
  --pacman           Same as --helper=pacman. Default.
  --min-free-bytes   Minimal amount of free space (in bytes) that the root partition should have
                     before updating. Otherwise a warning message will be displayed.
                     Default: $min_free_bytes
EOF
                exit 0
                ;;
            
            --) shift ; break ;;
        esac
        shift
    done
}

IsEndeavourOS() { [ -r /usr/lib/endeavouros-release ] || grep -iw endeavouros /etc/*-release &> /dev/null ; }

IsEndeavourOSoptimized() {
    case "$isEndeavourOS" in
        "")  if IsEndeavourOS ; then
                 isEndeavourOS=yes
                 return 0    # or: $FUNCNAME
             else
                 isEndeavourOS=no
                 return 1    # or: $FUNCNAME
             fi
             ;;
        yes) return 0
             ;;
        no)  return 1
             ;;
    esac
}

DiskSpace() {
    local available=$(LANG=C /usr/bin/df | /usr/bin/grep -w "/" | /usr/bin/awk '{print $4}')
    local min=$((min_free_bytes / 1000))  # use compatible numbers

    if [ $available -lt $min ] ; then
        {
        echo "WARNING: your root partition (/) has only $available bytes of free space."
        if [ $(du -d0 /var/cache/pacman/pkg | awk '{print $1}') -gt $min ] ; then
            printf "\nFor example, cleaning up the package cache may help.\n"
            printf "Command 'sudo paccache -rk1' would do this:"
            paccache -dk1
            printf "Command 'sudo paccache -ruk0' would do this:"
            paccache -duk0
            echo ""
        fi
        } >&2
    fi
}

Pau() {
    local progname="$(/usr/bin/basename "$0")"
    local nvidia=":"
    local helper="pacman"
    local min_free_bytes=$((1000 * 1000 * 1000))  # default: 1 GB
    local isEndeavourOS=""
    local cmdkeyring="pacman -Sy --needed"   # --noconfirm
    local rmopt=f
    local lock=/var/lib/pacman/db.lck
    local helper2=":"

    #echo "$helper update with additional and useful checks" >&2

    Options "$@"

    DiskSpace

    if [ -e $lock ] && fuser $lock &>/dev/null ; then
        rmopt=i
    fi
    local keyrings=(archlinux-keyring)
    IsEndeavourOSoptimized && keyrings+=(endeavouros-keyring)

    echo "Updating with $helper ..."
    if [ "$helper" = "pacman" ] ; then
        sudo bash -c "rm -$rmopt $lock; [ -e $lock ] || { $nvidia && $cmdkeyring ${keyrings[*]} && pacman -Su && sync ; }"
    else
        helper2="/usr/bin/sudo -u $LOGNAME $helper -Sua"
        sudo bash -c "rm -$rmopt $lock; [ -e $lock ] || { $nvidia && $cmdkeyring ${keyrings[*]} && pacman -Su && $helper2 ; sync ; }"
    fi
}

Main() {
    # pacman with additional features for
    # - update and AUR (via Pau)
    # - avoiding sudo (via pacman-sudo-internal)

    local helper=paru
    [ -x /usr/bin/$helper ] || helper=yay

    case "$1" in
        -h | --help)
            Options -h
            ;;
        -a | --aur)
            Pau --$helper  # ignores other parameters
            ;;
        "")
            Pau
            ;;
        -Syu)
            if [ -n "$2" ] ; then
                pacman-sudo-internal "$@"
            else
                Pau
            fi
            ;;
        *)
            pacman-sudo-internal "$@"
            ;;
    esac
}

Main "$@"
