#!/bin/bash

# Like pacman, but uses sudo only if needed.

# Bash completion: add the following lines (uncommented!) to file
# /usr/share/bash-completion/completions/ph:
#    source /usr/share/bash-completion/completions/pacman
#    complete -F _pacman ph

Main() {
    local -r root_needed="error: you cannot perform this operation unless you are root."  # this pacman output tells sudo is needed
    local out retval

    out=$(LANG=C /bin/pacman "$@" 2>&1)
    retval=$?

    case "$out" in
        "$root_needed") sudo /bin/pacman "$@" ;;                                          # need sudo only here!
        "")             return $retval ;;
        *)              printf "%s\n" "$out" ; return $retval ;;
    esac
}

Main "$@"
