#!/bin/bash

PMGUI_DIE() {
    echo "$PMGUI_PROGNAME: error: $@" >&2
    yad --forn --image=error \
        --title="$PMGUI_PROGNAME: error" --text="sorry, $*" --button=yad-quit
    exit 1
}

FirstAppOf() {
    local cmd app
    for cmd in "$@" ; do
        app=${cmd%% *}            # remove tail from first space
        app=${app%%	*}        # remove tail from first tab

        if which $app >& /dev/null ; then
            echo "$cmd"
            return 0
        fi
    done
    PMGUI_DIE "none of the supported apps ($@) detected"
}

EditFile() {
    local file="$1"
    local editor=$(FirstAppOf "emacs -nw" nano vim)
    local sudo=$(  FirstAppOf  sudo       pkexec)

    [ -n "$editor" ] || return 1
    [ -n "$sudo" ] || return 1

    if [ -w "$file" ] ; then
        RunInTerminal $editor "$file"
    else
        RunInTerminal $sudo $editor "$file"
    fi
}

export -f PMGUI_DIE FirstAppOf EditFile
export PMGUI_PROGNAME="$(basename "$0")"

Main() {
    local pacman_conf=/etc/pacman.conf
    local amp="&amp;"
    
    local cmd=(
        yad --form --align-buttons
        --use-interp
        --title="Package management"
        --text="Manage installed packages with the buttons below"
        --window-icon=/usr/share/endeavouros/EndeavourOS-icon.png
        --image=system-software-install
        --columns=3
        --button=yad-quit

        --field="Check $amp Update!system-software-update!If updates are available, run system update":fbtn "RunInTerminal 'pacman-ext'"
        --field="Update!system-software-update!Run system update directly":fbtn "RunInTerminal 'echo System Update ; pacman-ext -Syu --aur'"
        --field="Install!system-software-install!Select and install packages":fbtn "RunInTerminal 'paf -i'"
        --field="Remove!software-manager!Select and remove packages":fbtn "RunInTerminal 'paf -r'"

        --field="Edit $pacman_conf!accessories-text-editor!Change general package management settings":fbtn "EditFile $pacman_conf"
        --field="Edit Arch mirrorlist!accessories-text-editor!Change the list of Arch mirrors":fbtn "EditFile /etc/pacman.d/mirrorlist"
        --field="Edit EndeavourOS mirrorlist!accessories-text-editor!Change the list of EndeavourOS mirrors":fbtn "EditFile /etc/pacman.d/endeavouros-mirrorlist"

        --field="Rank Arch mirrors":fbtn "reflector-simple"
        --field="Rank EndeavourOS mirrors":fbtn "RunInTerminal eos-rankmirrors"
    )
    "${cmd[@]}" >/dev/null &
}

Main "$@"
