#!/bin/bash

PMGUI_MSG() {
    local type="$1"
    local icon=""

    shift
    case "$type" in
        error)   icon=error ;;
        warning) icon=dialog-warning ;;
    esac
    echo "$PMGUI_PROGNAME: $type: $@" >&2
    eos_yad --form --image=$icon --title="$PMGUI_PROGNAME: $type" --text="sorry, $*" --button=yad-quit
    [ "$type" = "error" ] && exit 1
}
PMGUI_DIE()  { PMGUI_MSG error   "$@" ; }
PMGUI_WARN() { PMGUI_MSG warning "$@" ; }

FirstAppOf() {
    local cmd app
    for cmd in "$@" ; do
        app=${cmd%% *}            # remove tail from first space
        app=${app%%	*}        # remove tail from first tab

        if which $app >& /dev/null ; then
            echo "$cmd"
            return 0
        fi
    done
    PMGUI_DIE "none of the supported apps ($@) detected"
}

EditFile() {
    local file="$1"
    local editor=$(FirstAppOf "emacs -nw" nano vim)
    local sudo=$(  FirstAppOf  sudo       pkexec)

    [ -n "$editor" ] || return 1
    [ -n "$sudo" ] || return 1

    if [ -w "$file" ] ; then
        RunInTerminal $editor "$file"
    else
        RunInTerminal $sudo $editor "$file"
    fi
}
RankArchMirrors() {
    if [ -x /bin/rami ] ; then
        RunInTerminal 'rami --save'
    elif [ -x /bin/rate-mirrors ] ; then
        RunInTerminal 'rate-mirrors arch --max-delay=3600 | sudo tee /etc/pacman.d/mirrorlist'
    else
        RunInTerminal 'reflector -phttps -l20 --save'
    fi
}


export -f PMGUI_MSG PMGUI_DIE PMGUI_WARN FirstAppOf EditFile RankArchMirrors
export PMGUI_PROGNAME="${0##*/}"

Main() {
    AssignIconVariables_in_eos_bash_shared

    local pacman_conf=/etc/pacman.conf

    local -r amp="&amp;"
    local -r and="&#38;"

    local -r icon_prefs=$ICO_PREFERENCES_SYSTEM
    local -r icon_update=$ICO_UPDATE
    local -r icon_install=$ICO_INSTALL
    local -r icon_remove=/usr/share/icons/Qogir/scalable/apps/software-manager.svg
    local -r icon_edit=$ICO_EDIT_CONFIG                                  # accessories-text-editor
    
    local cmd=(
        eos_yad --form --align-buttons --use-interp
        --title="Package management"
        --text="Manage system packages with the buttons below"
        --window-icon=$EOS_WICON                                         # /usr/share/endeavouros/EndeavourOS-icon.png
        --image=system-software-install
        --columns=2
        --button=yad-quit

        --field="Update system!$icon_update!Update packages with eos-update, including AUR":fbtn      "RunInTerminal 'echo System Update ; eos-update --aur'"
        --field="Install packages!$icon_install!Select and install packages":fbtn                     "RunInTerminal 'paf -i'"                                     # ???
        --field="Remove packages!$icon_remove!Select and remove packages":fbtn                        "RunInTerminal 'paf -r'"                                     # ???

        --field="Rank Arch mirrors!$icon_prefs!Rank the list of Arch mirrors":fbtn                    "RankArchMirrors"
        --field="Rank EndeavourOS mirrors!$icon_prefs!Rank the list of EndeavourOS mirrors":fbtn      "RunInTerminal eos-rankmirrors"

        --field="Edit $pacman_conf!$icon_edit!Change general package management settings":fbtn        "EditFile $pacman_conf"
        --field="Edit Arch mirrorlist!$icon_edit!Change the list of Arch mirrors":fbtn                "EditFile /etc/pacman.d/mirrorlist"
        --field="Edit EndeavourOS mirrorlist!$icon_edit!Change the list of EndeavourOS mirrors":fbtn  "EditFile /etc/pacman.d/endeavouros-mirrorlist"

        --field=" Manage config changes!$icon_prefs!Use eos-pacdiff to manage system config changes":fbtn       "RunInTerminal 'echo Running eos-pacdiff: ;  eos-pacdiff'"
        --field=" Configure package cache!$icon_prefs!Configure the management of the package cache":fbtn      "paccache-service-manager"
    )

    "${cmd[@]}" >/dev/null &
}

source /usr/share/endeavouros/scripts/eos-script-lib-yad --limit-icons || exit 1
export -f eos_yad
export -f eos_yad_nothing_todo

Main "$@"
