#!/bin/bash

echo2() { echo -e "$@" >&2 ; }
DIE()   { echo2 "==> $progname: error:"   "$1" ; exit 1 ; }
WARN()  { echo2 "==> $progname: warning:" "$1" ; }
INFO()  { echo2 "==> $progname: info:"    "$1" ; }
STOP()  { echo2 "$1" ; exit $2 ; }

NoneInstalled() { ! expac %n "$@" >/dev/null ; }
IsInstalled() { expac %n "$1" >/dev/null ; }

Main() {
    # Update all packages, also do some extra checks.
    # Needs:
    #    - eos-connection-checker
    #    - eos-kernel-nvidia-update-check (optional)
    #    - eos-pacdiff or eos-pacmerge
    #    - hook-update-description (optional)
    #    - uc-fast (optional)
    #    - clamav (optional)
    #
    # TODO:
    #   - virtualbox?

    local -r progname=${0##*/}
    local AUR=no
    local CONNECTION=no
    local DEEP=no                 # use uc-fast
    local SHOW_FETCH=yes
    local ucfast_options="-ae --verbose"
    local updates_native=""
    local updates_aur=""
    local clamav=no
    local clamav_ref_file="$HOME/.local/$progname.clamav_ref_file"
    local pkgdir=/var/cache/pacman/pkg
    local paru=/bin/paru
    local yay=/bin/yay

    [ -x $paru ] || paru=$yay     # is paru installed?

    Options "$@"
    CheckApps
    UpdatePackages
}

Usage() {
    [ "$1" = "1" ] && echo2 ""
    echo2 "Purpose:  Updates packages including extra checks."
    echo2 "Usage:    $progname [options]"
    echo2 "Options:  --aur,        -a  Include AUR packages too."
    echo2 "          --connection, -c  Check internet connection first."
    echo2 "          --deep,       -d  Check availability of updates more thoroughly."
    echo2 "          --hide-fetch, -f  Don't show the package download."
    echo2 "          --quiet,      -q  Be more quiet."
    echo2 "          --clamav          Scan updates for viruses with clamav."
    echo2 "          --help,       -h  This help."
    echo2 "Note: internet connection is required."
    [ "$1" ] && exit $1 || exit 0
}

Options() {
    # manage options
    local sopts="acdfhq"
    local lopts="aur,clamav,connection,deep,help,hide-fetch,quiet"
    local opts

    opts="$(/usr/bin/getopt -o="$sopts" --longoptions "$lopts" --name "$progname" -- "$@")" || Usage 1
    eval set -- "$opts"

    while true ; do
        case "$1" in
            --aur        | -a) AUR=yes ;;
            --connection | -c) CONNECTION=yes ;;
            --deep       | -d) DEEP=yes ;;
            --hide-fetch | -f) SHOW_FETCH=no ;;
            --help       | -h) Usage ;;
            --quiet      | -q) ucfast_options="-ae" ;;
            --clamav)          clamav=yes ;;
            --) shift; break ;;
        esac
        shift
    done
}
CheckApps() {
    # we must have the required apps
    local pkgs=(
        eos-bash-shared    # needed: eos-connection-checker
        yay
    )
    local pkg

    for pkg in "${pkgs[@]}" ; do
        IsInstalled $pkg || DIE "package '$pkg' is required but missing"
    done
    if [ $clamav = yes ] ; then
        IsInstalled clamav || DIE "package 'clamav' is needed by option --clamav"
    fi
    if [ $DEEP = no ] ; then
        IsInstalled pacman-ext || WARN "package 'pacman-ext' is needed by the fast check"
    fi
}

UpdatePackages() {
    Connection
    Clamav --init
    GetAurUpdates
    FastCheck             # stops here if no updates by "fast check"
    PacmanLock
    GetNativeUpdates
    StopIfNoUpdates
    Nvidia
    Descriptions
    Clamav --check
    Keyrings
    RealUpdate            # update packages here
    Clamav --save
    Pacdiff
}

Clamav() {
    [ $clamav = no ] && return

    case "$1" in
        --init) 
            [ -e "$clamav_ref_file" ] || $FUNCNAME --save
            ;;
        --check)
            local newfiles=""
            if [ -e "$clamav_ref_file" ] ; then
                newfiles=$(find $pkgdir -type f -newer "$clamav_ref_file")
            else
                newfiles=$(find $pkgdir -type f)
            fi
            if [ "$newfiles" ] ; then
                local -r log=/tmp/$progname-clamscan.log
                local CLAMOPTS="--bell -o --no-summary -l $log"
                clamscan $CLAMOPTS $newfiles
                case "$?" in
                    0) INFO "clamscan found nothing." ;;
                    1) DIE  "clamscan found problems! See file $log." ;;
                    2) WARN "clamscan had problems, see file $log." ;;
                esac
            else
                INFO "all package files checked with clamav already!"
            fi
            ;;
        --save)
            local newref=$(/bin/ls -1tr "$pkgdir" | tail -n1 | awk '{print $NF}')
            touch -r "$pkgdir/$newref" "$clamav_ref_file"
            ;;
    esac
}

Connection() {
    if [ $CONNECTION = yes ] ; then
        # we need internet connection
        eos-connection-checker || DIE "no connection!"
    fi
}
GetAurUpdates() {
    # check AUR for updates if needed
    [ $AUR = yes ] && updates_aur=$($paru -Quaq)
}
FastCheck() {
    if [ $DEEP = no ] ; then
        # stop if no updated packages (with uc-fast)
        if [ -x /bin/uc-fast ] ; then
            if ! uc-fast $ucfast_options ; then                              # this line needs internet connection!
                case $AUR in
                    yes) [ -z "$updates_aur" ] && STOP "==> No updates (fast check)" 0 ;;
                    no)  STOP "==> No native updates (fast check)" 0 ;;
                esac
            fi
        fi
    fi
}
PacmanLock() {
    # remove pacman lock if possible
    local -r lockfile=/var/lib/pacman/db.lck
    if [ -e $lockfile ] ; then
        fuser $lockfile &> /dev/null && DIE "$lockfile is in use"
        sudo rm -f $lockfile
        echo2 "==> INFO: $lockfile removed"
    fi
}
GetNativeUpdates() {
    local -r cmd="sudo pacman -Syuw --noconfirm"    # update pacman database and download possible updates
    case "$SHOW_FETCH" in
        yes) $cmd             ;;
        no)  $cmd  >/dev/null ;;
    esac
    updates_native=$(pacman -Quq)               # find names of updated packages
}
StopIfNoUpdates() {
    # stop if no updated packages
    if [ -z "$updates_native$updates_aur" ] ; then
        case $AUR in
            yes) STOP "==> No native nor AUR updates (deep check)" 0 ;;
            no)  STOP "==> No native updates (deep check)" 0 ;;
        esac
    fi
}
Nvidia() {
    NoneInstalled nvidia nvidia-lts && return 0
    if [ -x /bin/eos-kernel-nvidia-update-check ] ; then
        # check Nvidia
        printf "==> INFO: Nvidia & kernel check: " >&2
        eos-kernel-nvidia-update-check $updates_native 2>/dev/null || STOP "FAIL" 1
        echo2 "OK"
    else
        WARN "no Nvidia check done because eos-bash-shared is not installed"
    fi
}
Descriptions() {
    if [ -x /bin/hook-update-description ] ; then
        # show the description for each updated package
        [ "$updates_native" ] && hook-update-description --title="native updates" --header=no $updates_native
        [ "$updates_aur" ]    && hook-update-description --title="AUR updates"    --header=no $updates_aur
    fi
}
Keyrings() {
    # update keyrings if needed
    local keyring_packages=(archlinux-keyring
                            endeavouros-keyring)
    local pkg keyr=()
    for pkg in "${keyring_packages[@]}" ; do
        printf "%s\n" $updates_native | grep "^$pkg$" >/dev/null && keyr+=($pkg)
    done
    [ "$keyr" ] && sudo pacman -S --noconfirm "${keyr[@]}"
}
RealUpdate() {
    # update packages
    if [ "$updates_native" ] ; then
        echo2 "==> Native updates"
        sudo pacman -Su
    fi
    if [ $AUR = yes ] && [ "$updates_aur" ] ; then
        echo2 "==> AUR updates"
        $yay -Sua
    fi
}
Pacdiff() {
    if [ "$updates_native" ] ; then
        # check .pacnew files
        if [ -x /bin/eos-pacmerge ] ; then
            eos-pacmerge --quiet
        else
            eos-pacdiff --quiet
        fi
    fi
}

Main "$@"
