#!/bin/bash

# Package updater for EndeavourOS and Arch.
# Handles lock file, keyrings, syncing, and optionally AUR with given AUR helper.

Options() {
    local opts
    local lopts="nvidia,helper:,paru,yay,help"
    local sopts="h"

    opts="$(/usr/bin/getopt -o=$sopts --longoptions $lopts --name "$progname" -- "$@")" || {
        Options -h
        return 1
    }
    eval set -- "$opts"

    while true ; do
        case "$1" in
            --nvidia) nvidia=eos-kernel-nvidia-update-check ;;
            --helper) helper="$2" ; shift ;;
            --paru | --yay) helper="${1/--/}" ;;

            -h | --help)
                cat <<EOF >&2
Package updater for EndeavourOS and Arch
Handles:
- db lock
- keyrings
- sync after update
and optionally
- AUR with given AUR helper
- Nvidia driver vs. kernel updates

Usage: $progname [options]
Options:
  --help, -h         This help.
  --nvidia           Check also nvidia driver vs. kernel updates.
  --helper           AUR helper name. Supported: yay, paru, pacman. Default: pacman.
                     Others supporting option -Sua should work as well.
  --paru             Same as --helper=paru.
  --yay              Same as --helper=yay.
  --pacman           Same as --helper=pacman.
EOF
                exit 0
                ;;
            
            --) shift ; break ;;
        esac
        shift
    done
}

Main() {
    
    local progname="$(/usr/bin/basename "$0")"
    local nvidia=":"
    local helper="pacman"

    local helper2=":"
    local lock=/var/lib/pacman/db.lck
    local rmopt=f

    Options "$@"

    echo "$helper update with additional and useful checks" >&2

    if [ -e $lock ] && fuser $lock &>/dev/null ; then
        rmopt=i
    fi
    local keyrings=(archlinux-keyring)
    if [ -r /usr/lib/endeavouros-release ] || [ -n "$(grep -iw endeavouros /etc/*-release)" ] ; then
        keyrings+=(endeavouros-keyring)
    fi
    if [ "$helper" = "pacman" ] ; then
        sudo bash -c "rm -$rmopt $lock; [ -e $lock ] || { $nvidia && pacman -Sy --noconfirm --needed ${keyrings[*]} && pacman -Su && sync ; }"
    else
        helper2="/usr/bin/sudo -u $LOGNAME $helper -Sua"
        sudo bash -c "rm -$rmopt $lock; [ -e $lock ] || { $nvidia && pacman -Sy --noconfirm --needed ${keyrings[*]} && pacman -Su && $helper2 ; sync ; }"
    fi
}

Main "$@"
