#!/bin/bash

echo2() { echo "$@" >&2 ; }
read2() { read "$@" >&2 ; }

DIE() {
    echo2 "$progname: error in function ${FUNCNAME[1]}: $1"
    exit 1
}

_browser() {
    local browser
    for browser in "${MANE_BROWSERS[@]}" exo-open xdg-open ; do
        if [ -x /usr/bin/$browser ] ; then
            $browser "$@" >& /dev/null &
            return
        fi
    done
    DIE "no browser found"
}

_pdf() {
    local pdf
    for pdf in "${MANE_PDFS[@]}" exo-open xdg-open ; do
        if [ -x /usr/bin/$pdf ] ; then
            $pdf "$@" >& /dev/null &
            return
        fi
    done
    DIE "no pdf viewer found"
}

_eos_usage() {
            cat <<EOF
This program shows both the traditional 'man' pages and additional manual pages.
Note that the additional manual pages may not be in the format of the
traditional 'man' pages.

Usage:
    $progname {any-man-parameters}
    $progname {eos-name | extra-name}
    $progname [--help | -h | --additional-manuals]

Paramemers:
    any-man-parameters
        Does the same as the 'man' command.
        Run command 'man man' for all parameters and details.
    eos-name
        An EndeavourOS specific program or package name, e.g.
            welcome              # package name
            eos-welcome          # program name
            eos-wallpaper-set    # program name
            eos-update-notifier  # package and program name
    extra-name
        Some generally useful app, e.g.
            grub
            libreoffice
            virtualbox
    --ending=X
            Prefer ending X in file name if more than one manual with different
            ending is available, for example: bashdb.html vs. bashdb.pdf.
    --additional-manuals
        Show the supported eos-names and extra-names
    --help | -h
        This help.

File /etc/$progname.conf may include configurations for $progname, e.g.
    MANE_PREFER_EXTENSION[bashdb]=pdf

=========================================================================

EOF
}

_usage() {
    while true ; do
        _eos_usage
        /usr/bin/man --help
        break
    done | less -RF
}

_local_manual() {
    # better or correct manual

    local appname="$1"
    local dir=/usr/share/doc/doc-extra
    local file="$(ls -1 $dir/$appname.*)"
    local end

    case "$(echo "$file" | wc -l)" in
        1) ;;
        0) DIE "'$file': manual page not found" ;;
        *)
            if [ -n "$ending" ] ; then
                end="$ending"
            else
                end="${MANE_PREFER_EXTENSION[$appname]}"
            fi
            if [ -n "$end" ] ; then
                file="$(echo "$file" | grep $end$)"
            else
                echo2 "Found manuals:"
                echo2 "$file"
                local endings=$(echo "$file" | sed 's|.*\.\([a-z][a-z]*\)$|\1|')
                endings="$(echo $endings)"
                read2 -p "Select ending to use [$endings]: "
                file="$(echo "$file" | grep $REPLY$)"
            fi
            case "$(echo "$file" | wc -l)" in
                1) ;;
                0) DIE "'$file': manual page not found" ;;
                *) DIE "too many files: '$file'" ;;
            esac
            case "$file" in
                *.pdf | *.html) ;;
                *) DIE "sorry, unsupported file ending in '$file'" ;;
            esac
            ;;
    esac

    case "$file" in
        *.pdf)  _pdf     "$file" ;;
        *.html) _browser "$file" ;;
        *) DIE "unsupported file type in '$file'" ;;
    esac

    # show the upstream manual as well (if is exists)
    /usr/bin/man "$appname"
}

_additional_manuals() {
    local pkgs="$(pacman -Slq endeavouros)"
    local manuals="$(echo $pkgs)"              # all EOS packages

    # add all EOS programs
    manuals+=" $(echo $(pacman -Flq $pkgs | grep ^usr/bin/. | sed 's|usr/bin/||'))"

    # add some general manuals
    manuals+=" bashdb grub kaffeine virtualbox"
    manuals+=" code libreoffice soffice reflector"

    manuals="$(printf "%s\n" $manuals | sort | uniq)"
    local xx count=0
    for xx in $manuals ; do
        printf "%s " "$xx"
        if [ $((++count)) -eq 3 ] ; then
            count=0
            printf "\n"
        fi
    done | column -t
}

_actual_man() {
    case "$1" in
        bashdb | grub | kaffeine | virtualbox)
            _local_manual "$@"
            ;;
        code)
            _browser https://code.visualstudio.com/docs
            ;;
        libreoffice | soffice)
            _browser https://help.libreoffice.org
            /usr/bin/man "$1"
            ;;
        reflector)
            _browser https://xyne.archlinux.ca/projects/reflector
            /usr/bin/man "$1"
            ;;
        *)
            # try the "real" man command
            /usr/bin/man "$@"
            case "$?" in
                16) # man page not found
                    eos-pkginfo "$@"
                    ;;
                0)  # OK
                    ;;
                *)
                    echo "Sorry, man failed." >&2
                    ;;
            esac
    esac
}

_man() {
    local progname="$(basename "$0")"
    declare -A MANE_PREFER_EXTENSION  # array to select file name endings
    source /etc/mane.conf || DIE "reading /etc/mane.conf failed"
    local ending=""
    local arg

    [ "$1" = "" ] && { _usage ; return ; }

    while true ; do
        arg="$1"
        case "$arg" in
            -h | --help)
                _usage
                return
                ;;
            --additional-manuals)
                _additional_manuals
                return
                ;;
            --ending=*)
                ending="${arg#*=}"
                ;;
            -*)
                DIE "unsupported option $arg"
                ;;
            *)
                break
                ;;
        esac
        shift
    done

    _actual_man "$@"
}

_man "$@"
