#!/bin/bash

# Use database to set the correct Ethernet driver.

echo2()   { echo "$@" >&2 ; }
printf2() { printf "$@" >&2 ; }
DIE()     { echo2 "$progname: error: $1"; exit 1; }

debug()   { [ "$debug" = "yes" ] && echo2 "$@" ; }

GetId()     { echo "$lspci" | sed -n "/$devstring/,/^$/p" | grep -w "$devstring" | sed 's|.*\[\([0-9a-f:]*\)\].*|\1|' ; }
GetDriver() { echo "$lspci" | sed -n "/$devstring/,/^$/p" | grep 'Kernel driver in use' | awk '{print $NF}' ; }
FindCard()  { echo "$lspci" | sed -n "/$devstring/,/^$/p" | grep -w "$devstring" ; }

Options() {
    local opts
    opts="$(getopt -o=dsh --longoptions debug,display,help,save,sendlog --name "$progname" -- "$@")" || exit 1

    eval set -- "$opts"

    while true ; do
        case "$1" in
            -h | --help)
                cat <<EOF
Usage: $progname [options]
Options:
    --save    -s   Store your card and *working* driver info temporarily for --sendlog.
    --display -d   Display the known good driver name from the local system database.
    --sendlog      Send the stored temporary info to internet using eos-sendlog.
    --help    -h   Show this help and exit.
EOF
                exit 0
                ;;
            -s | --save) mode=save ;;
            -d | --display) mode=display ;;
            --sendlog) mode=sendlog ;;

            # "hidden" options:
            --debug) debug=yes ;;

            --) shift ; break ;;
        esac
        shift
    done
    [ -n "$1" ] && devstring="$1"
}

Main()
{
    local progname="$(basename "$0")"

    # Options may modify these variables:
    local mode=display  # save or display
    local devstring="Ethernet controller"  # device search string
    local debug=no

    Options "$@"

    local id driver="" dbline=""
    local database_sys=/usr/share/endeavouros/drivers_ethernet_r8168
    local database_user=$HOME/.cache/drivers_ethernet_r8168
    local lspci="$(lspci -vnn)"
    local cardinfo=$(FindCard)

    #if [ ! -r "$database" ] ; then
    #    touch "$database" || DIE "cannot create database file $database"
    #fi

    id=$(GetId)

    case "$mode" in
        save)
            # It is possible that more than one driver is supported by the same id.
            driver=$(GetDriver)
            if (! eos-connection-checker) ; then
                DIE "Connection failure! Will not store driver '$driver' to database. Please check your connections."
            fi
            if [ -r $database_sys ] ; then
                dbline="$(grep "^$id $driver # " "$database_sys")"
            fi
            if [ -z "$dbline" ] ; then
                if [ -r "$database_user" ] ; then
                    dbline="$(grep "^$id $driver # " "$database_user")"
                fi
                if [ -z "$dbline" ] ; then
                    echo2 "Adding driver $driver with id $id."
                    printf "%s %s # %s\n" "$id" "$driver" "$cardinfo" > "$database_user"
                else
                    debug "user database has line: $dbline"
                    echo2 "Driver $driver already added for sending. Now use option --sendlog."
                fi
            else
                echo2 "Driver $driver already added, nothing to do."
                debug "system database has line:"
                debug "$dbline"
            fi
            ;;
        sendlog)
            [ -r "$database_user" ] || DIE "file '$database_user' not found, use option '--save' first."
            cat "$database_user" | eos-sendlog
            rm -f "$database_user"               # this file not needed anymore
            ;;

        display)
            [ -r $database_sys ] || DIE "database '$database' does not exist."
            dbline="$(grep -w "^$id" "$database_sys")"
            driver="$(echo "$dbline" | awk '{print $2}')"
            [ -n "$driver" ] || DIE "database does not contain a driver for '$id'"
            debug "Database has the following card info:"
            debug "$dbline"
            echo "$driver"
            ;;
    esac
}

Main "$@"

