#!/bin/bash

Show() {
    local name="$1"
    local value="$2"
    printf "%-15s : %s\n" "$name" "$value"
}

Main()
{
    local devstring="Ethernet controller"
    local data=$(lspci -vnn | sed -n "/$devstring/,/^$/p")

    local card=$(  echo "$data" | grep -w "$devstring")
    local id=$(    echo "$card" | sed 's|.*\[\([0-9a-f:]*\)\].*|\1|')
    local driver=$(echo "$data" | grep 'Kernel driver in use' | awk '{print $NF}')

    Show "card id"       "$id"
    Show "card info"     "$card"
    Show "driver in use" "$driver"
}

Main "$@"
