#!/bin/bash

# The Finnish translation for stickburn.

# Define all translations in the associative array BTR_ARR.

declare -A BTR_ARR=(
    iso_not_exist          "ISO-tiedostoa '%s' ei löydy."
    wait_find_usb_drives   "Etsitään USB-asemia, odota..."
    usb_drive_not_found    "USB-asemaa ei saatavilla."
    word_warning           "varoitus"
    word_error             "virhe"
    word_finished          "Valmis${BTR_exclamation}"
    word_burn              "Polta"
    burn_fail_stopped      "USB-aseman poltto lopetettu."
    burn_fail_cancel       "USB-aseman %s poltto keskeytetty."
    burn_ok_ready          "USB-aseman poltto on valmis."
    burn_ok_stick          "USB-aseman %s poltto on valmis."
    burning_to             "Poltto tikulle %s:"
    creating_config        "==> Luodaan asetustiedosto %s"
    die_app_missing        "en löydä sovellusta toiminnolle '%s'"
    die_create_fail        "en pysty luomaan asetustiedostoa '%s'."
    die_read_fail          "en pysty lukemaan asetustiedoatoa '%s'."
    die_var_not_set        "muuttuja ISO_folder on asettamatta, katso tiedosto\n%s"
    die_iso_missing        "ISO-tiedosto '%s' ei löydy."
    die_drive_not_selected "USB-asema ei ole valittu."
    warn_dep_missing       "valitsimen '%s' käyttö tarvitsee paketin '%s'"
    warn_folder_changed    "==> Varoitus: %s: muuttujan ISO_folder arvoa ei voi käyttää. Asetan ISO_folder:n arvoksi %s."
    title_purpose          "Polta ISO USB-asemaan"
    cmd_text               "Polta ISO-tiedosto USB-asemaan"
    yad_field_iso          "<tt>ISO-tiedosto:   </tt>"
    yad_field_no_drives    "<i>Valitan, USB-asemaa ei löydy.</i>"
    yad_field_msg_fail1    "\n<i>Valitan, kaikki USB-asemat ovat jo sidottuja (mount) enkä voi jatkaa.\n"
    yad_field_msg_fail2    "USB-aseman pitää olla sitomaton (umount) kun siihen poltetaan.</i>"
    yad_field_usb          "<tt>USB-asema:   </tt><b>%s</b>"
    yas_field_usb_d        "<tt>USB-asema:</tt>"
    yad_field_select_usb   "\nValitse alla oleva USB-aseman nappi (ellei jo näkyvissä yllä)"
    msg_no_drives          "Ei USB-asemia"
    msg_no_unmounted       "Ei sitomattomia (umount) USB-asemia"
    msg_tip_title          "Polttaa valitun ISO-tiedoston valittuun USB-asemaan"
    no_selection           "(Ei mitään)"
    msg_already_mounted    "Jo sidotut USB-asemat:"
    txt_multifield1        "_MULTILINE_1"
)

_MULTILINE_1=(
    "Valitse hakemisto josta ISO-tiedosto haetaan.\n"
    "Valitse USB-asema kohteeksi (jollei automaattisesti valittu).\n"
    "<b><i>Varmista</i></b> että kohteeksi valittu USB-asema on juuri oikea. "
    "Polttoa ei pysty perumaan aloittamisen jälkeen${BTR_exclamation}\n"
    "Poltto kestää muutamia minuutteja USB-aseman nopeudesta riippuen.\n"
    "Polton valmistuttua saat ilmoitusikkunan.\n"
)
