#!/bin/bash
#
# Author: manuel (see https://forum.endeavouros.com)
#

USB_all_infos()
{
    # Usage examples:
    #     USB_all_infos PATH,SIZE,VENDOR,MODEL
    #     USB_all_infos VENDOR

    local options="$1"   # comma separated list of options for 'lsblk -o'
    local -n _infovar="$2"
    local tmpinfo

    case "$options" in
        [A-Z]*)
            tmpinfo="$(lsblk -o $options,SUBSYSTEMS,TYPE,HOTPLUG | grep -E ':usb:|1$' | grep ' disk ')"
            options=$(echo "$options" | tr ',' '\n' | wc -l)
            ;;
        *)
            tmpinfo="$(lsblk -o PATH,SIZE,VENDOR,MODEL,SUBSYSTEMS,TYPE,HOTPLUG | grep -E ':usb:|1$' | grep ' disk ')"
            options=4
            ;;
    esac
    [ "$tmpinfo" ] || return 1

    case "$options" in
        "1")   tmpinfo="$(echo "$tmpinfo" | awk '{printf "%-10s\n", $1}')" ;;
        "2")   tmpinfo="$(echo "$tmpinfo" | awk '{printf "%-10s %7s\n", $1, $2}')" ;;
        "3")   tmpinfo="$(echo "$tmpinfo" | awk '{printf "%-10s %7s %s\n", $1, $2, $3}')" ;;
        "4"|*) tmpinfo="$(echo "$tmpinfo" | awk '{printf "%-10s %7s %s %s\n", $1, $2, $3, $4}')" ;;
    esac
    _infovar="$tmpinfo"     # echo "$tmpinfo"
    return 0
}

USB_info()
{
    local path="$1"
    local option="$2"  # one option, e.g. VENDOR
    local -n _var2="$3"
    local info=""
    USB_all_infos "PATH,$option" info
    [ "$info" ] && info="$(echo "$info" | grep "$path" | awk '{print $2}')"
    _var2="$info"
}

USB_generation()
{
    local vendor2="$1"
    local lines=7        # usb-devices lines for one entry, minus one
    local usbdata=$(usb-devices 2>/dev/null | grep -B$lines "Driver=usb-storage")
    local speed=$(echo "$usbdata" | grep -B$lines "Manufacturer=$vendor2" | grep 'Spd=' | sed 's|^.*Spd=\([0-9]*\).*$|\1|')
    if [ -z "$speed" ] ; then
        # usb-devices reports SanDisk fields [Manufacturer,Product] incorrectly, is this a vendor mistake?
        usbdata=$(echo "$usbdata" | grep -B$lines -A1 "Manufacturer= $vendor2")
        if [ "$usbdata" ] ; then
            speed=$(echo "$usbdata" | grep 'Spd=' | sed 's|^.*Spd=\([0-9]*\).*$|\1|')
            vendor2=$(echo "$usbdata" | grep "Product=")
            [ "$vendor2" ] && vendor=$(echo "$vendor2" | sed -E 's|^[A-Z]:[ ]+Product= ||')
        fi
    fi
    # | grep 'Spd=' | sed 's|^.*Spd=\([0-9]*\).*$|\1|')
    case "$speed" in
        480)  echo "2.0" ;;
        5000) echo "3.0" ;;
        *)    echo "[Mbps:$speed]" ;;
    esac
}

Main()
{
    local -r progname="${0##*/}"
    local usb_infos=""
    local path vendor model usbgen size type hotplug
    local sep="|"

    USB_all_infos PATH usb_infos

    while [ "$1" ] ; do
        case "$1" in
            --separator)   sep="$2"; shift ;;
            --separator=*) sep="${1#*=}" ;;
            -h | --help)   Usage; return 0 ;;
            *) DIE "unsupported parameter '$1'" ;;
        esac
        shift
    done

    if [ "$usb_infos" ] ; then
        for path in $usb_infos
        do
            USB_info "$path" SIZE    size
            USB_info "$path" VENDOR  vendor
            USB_info "$path" MODEL   model
            USB_info "$path" TYPE    type
            USB_info "$path" HOTPLUG hotplug
            case "$hotplug" in
                1) hotplug="" ;;                  # hotplug="${sep}hotplug" ;;
                *) hotplug="${sep}non-hotplug?" ;;
            esac

            usbgen=$( USB_generation "$vendor")

            echo "$path${sep}usb-$usbgen${sep}$vendor${sep}$model${sep}$size${sep}$type$hotplug"
        done
        return 0
    else
        echo "Looks like no USB drive attached." >&2
        return 1
    fi
}

Usage() {
    cat <<EOF
Usage: $progname [options]
Options:
    -h, --help        This help.
    --separator X     Use X as a separator inside the displayed strings.
EOF
}

DIE() {
    echo "$progname: error: $1"
    Usage
    exit 1
}

Main "$@"
