#!/bin/bash

# set -o euxo pipefail
# set -o euo pipefail

echo2() { echo -e "$@" >&2 ; }
debug() { test "$DEBUG" = "yes" && echo2 "Debug: " "$@" ; }
m_yad() { eos_yad --window-icon=$usb_icon --image=$usb_icon "$@" ; }

DIE_WARN() {
    local type="$1"
    shift
    echo2 "==> $progname: $type: $1"
    m_yad --form --text="${type^}: $1" --title="$progname" \
          --button=yad-quit --width=400 --window-icon=dialog-"$type"
}
DIE()  { DIE_WARN $(BTR word_error)   "$1"; exit 1; }
WARN() { DIE_WARN $(BTR word_warning) "$1"; }

ConfField() {
    local fieldname="$1"
    grep "^$fieldname=" | cut -d '=' -f 2 | sed -e "s|^['\"]||" -e "s|['\"]$||"
}

DeviceOf() {
    local usb_line="$1"
    echo "$usb_line" | awk '{print $1}' | sed 's|:$||'
}

# DD_command() {
#     local iso_file="$1"
#     local usb_stick="$2"
#     echo "dd status=progress bs=4M if=$iso_file of=$usb_stick && sync"
# }

BurnFail() {
    local timeout=600
    local cmd=(NotifySend "$timeout"
               "$(BTR burn_fail_stopped)"
               "$(BTR burn_fail_cancel "$usb_stick")"
               "$is_foreground")
    "${cmd[@]}"
    exit 1
}
BurnSuccess() {
    debug "Syncing..."
    sync

    local timeout=30
    local cmd=(NotifySend "$timeout"
               "$(BTR burn_ok_ready)"
               "$(BTR burn_ok_stick "$usb_stick")"
               "$is_foreground")
    "${cmd[@]}"
    exit 0
}

Burn() {
    if [ -x /bin/RunInTerminal ] ; then
        /bin/RunInTerminal "echo -e '$(BTR burning_to "$usb_stick")' ; sudo burn2dev '$usb_stick' '$iso_file'" || BurnFail
    else
        pkexec burn2dev "$usb_stick" "$iso_file" || BurnFail
    fi
    BurnSuccess
}

NotifySend() {
    local sec="$1"
    local header="$2"
    local msg="$3"
    local is_foreground="$4"
    local ms="${sec}000"

    if [ "$is_foreground" = "no" ] ; then
        notify-send --expire-time="$ms" "$header" "$msg" &
    else
        notify-send --expire-time="$ms" "$header" "$msg"
        echo2 "$(BTR word_finished)"
        sleep 5
    fi
}

Open() {
    local op="$1"
    local app
    local apps=(kde-open exo-open xdg-open)
    shift
    case "$op" in
        edit) apps+=(kate gedit emacs xed codium geany) ;;
        open) ;;
    esac
    for app in "${apps[@]}" ; do
        if which "${app%% *}" &>/dev/null ; then
            $app "$@"
            exit 0
        fi
    done
    DIE "$(BTR die_app_missing "$op")"
}

GetIsoFolder() {
    if [ -x /bin/fetch-iso ] ; then
        # for fetch-iso users
        local fetch_conf
        fetch_conf=$(fetch-iso --show-config)
        if [ -e "$fetch_conf" ] ; then
            # shellcheck disable=1090
            iso_folder="$(source "$fetch_conf"; echo "$TARGETDIR")"
            if [ "$iso_folder" ] ; then
                iso_folder=${iso_folder/\~/$HOME}
                iso_folder=${iso_folder%/}
            fi
        fi
    fi
    if [ -z "$iso_folder" ] ; then
        iso_folder="$HOME"
    fi
}

ReadConfig() {
    if [ ! -e "$conf" ] ; then
        echo2 "$(BTR creating_config "${conf/$HOME/\~}")"
        local iso_folder=""
        GetIsoFolder
        cat <<EOF > "$conf"
#!/bin/bash

ISO_folder="$iso_folder"
EOF
        test -r "$conf" || DIE "$(BTR die_create_fail "${conf/$HOME/\~}")"
    fi

    ## shellcheck source=/dev/null                                        # shellcheck totally ignores what $conf referers to
    # shellcheck disable=SC1090                                           # variable 'conf' is readonly, why does shellcheck complain?
    source "$conf" || DIE "$(BTR die_read_fail "${conf/$HOME/\~}")"
}

HandleParams() {
    local arg
    for arg in "$@" ; do
        case "$arg" in
            --edit-config | -e)
                Open edit "$conf"
                ;;
            --open-iso-folder)
                [ "$ISO_folder" ] || DIE "$(BTR die_var_not_set "${conf/$HOME/\~}")"
                Open open "$ISO_folder"
                ;;
            --show-disks)
                if [ -x /bin/RunInTerminal ] ; then
                    RunInTerminal lsblk -fm
                else
                    WARN "$(BTR warn_dep_missing "$arg" "eos-bash-shared")"
                fi
                exit 0
                ;;
            --fg)
                is_foreground=yes
                ;;
            -*)
                Usage 1
                ;;
            *)
                iso_file="$arg"
                case "$iso_file" in
                    /* | ./*) ;;
                    *)
                        if [ ! -e "$iso_file" ] ; then
                            if [ -e "$ISO_folder/$iso_file" ] ; then
                                iso_file="$ISO_folder/$iso_file"
                            fi
                        fi
                        ;;
                esac
                ;;
        esac
    done
}

Usage() {
    cat <<EOF >&2
Usage:        $progname [options] [iso-file]
Options:      --edit-config, -e     Edit the config file ${conf/$HOME/\~}.
              --open-iso-folder     Open the folder configured in ${conf/$HOME/\~} with variable 'ISO_folder'.
              --show-disks          Show all disks to see which can be used for burning.
              --fg                  Notification at the end is in foreground (when started from a launcher).
Files:        iso-file              Path of the ISO file to burn.
EOF
    [ "$1" ] && exit "$1"
}

Main()
{
    local progname=${0##*/}

    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1
    AssignIconVariables_in_eos_bash_shared

    source /usr/share/endeavouros/translations/bash-app-translate "$progname" || exit 1

    local is_foreground=no
    local iso_file=""
    local -r usb_icon=drive-removable-media-usb
    local -r conf="$HOME/.config/$progname.conf"

    ReadConfig

    HandleParams "$@"

    local DEBUG=no

    local progname=${0##*/}    #"stickburn"
    local usb_stick=""
    local iso_file_folder=""
    local iso_file_folder_conf=""
    local cmd=()
    local result=""
    # local dd_command
    local iso_field=2
    local usb_field=$((iso_field + 1))
    local xx device tmp
    local usb_sticks_info
    local usb_candidates=()
    local no_selection="$(BTR no_selection)"
    local txt
    local mounted_sticks=0
    local -r exclamation='&#33;'

    DebugBreak

    if [ "$iso_file" ] ; then
        test -r "$iso_file" || DIE "$(BTR iso_not_exist "$iso_file")"
    fi

    # echo2 "Finding USB drives, please wait..."
    echo2 "==> $(BTR wait_find_usb_drives)"
    readarray -t usb_sticks_info <<< "$(find-usb-sticks --quiet --separator " ")"

    # [ "${usb_sticks_info[*]}" ] || DIE "no target USB drive available."
    [ "${usb_sticks_info[*]}" ] || DIE "$(BTR usb_drive_not_found)"

    for xx in "${usb_sticks_info[@]}" ; do
        test -n "$xx" || continue
        device="$(DeviceOf "$xx")"
        tmp="$(/usr/bin/df --output=source,target | grep "^$device" | awk '{print $2}')"
        if [ -z "$tmp" ] ; then
            usb_candidates+=("$xx")
        fi
    done

    iso_file_folder_conf="$(cat "$conf" | ConfField 'ISO_folder')"
    iso_file_folder="$iso_file_folder_conf"
    test -d "$iso_file_folder" || {
        WARN "$(BTR warn_folder_changed "${conf/$HOME/\~}" '$HOME')"
        iso_file_folder="$HOME"
    }

    cmd=(m_yad --form --title="$progname: $(BTR title_purpose)"
         # --scroll
         #--height=350
         # --width=600
        )

    # button icon: media-record, usb-creator
    cmd+=(--button=yad-cancel:1)

    txt="$(BTR cmd_text)"
    cmd+=(--text="$txt")

    txt=""
    txt+="$(BTR txt_field1 "$iso_file_folder")"
    txt+="$(BTR txt_field2)"
    txt+="$(BTR txt_field3)"
    txt+="$(BTR txt_field4)"
    txt+="$(BTR txt_field5)"
    txt+="$(BTR txt_field6)"

    cmd+=(--field="$txt":LBL "")

    if [ -z "$iso_file" ] ; then
        cmd+=(--field="$(BTR yad_field_iso)":FL "$iso_file_folder/*")
    else
        cmd+=(--field="$(BTR yad_field_iso)":RO "$iso_file")
    fi
    case "${#usb_candidates[@]}" in
        0)  case "${usb_sticks_info[0]}" in
                "")
                   cmd+=(--field="$(BTR yad_field_no_drives)":LBL "")
                   result="$(BTR msg_no_drives)"
                   ;;
                *) txt=""
                   txt+="$(BTR yad_field_msg_fail1)"
                   txt+="$(BTR yad_field_msg_fail2)"
                   cmd+=(--field="$txt":LBL "")
                   result="$(BTR msg_no_unmounted)"
                   ;;
            esac
            ;;
        1)
            usb_stick="${usb_candidates[0]}"
            cmd+=(--field="$(BTR yad_field_usb "${usb_stick%% *} -- (${usb_stick#* })")":LBL "")
            ;;
        *)  cmd+=(--field="$(BTR yad_field_usb_d)":RO "$no_selection")
            cmd+=(--field="$(BTR yad_field_select_usb)":LBL "")
            for xx in "${usb_sticks_info[@]}" ; do
                device="$(DeviceOf "$xx")"
                tmp="$(/usr/bin/df --output=source,target | grep "^$device" | awk '{print $2}')"
                if [ -z "$tmp" ] ; then
                    cmd+=(--field="$xx":fbtn "@bash -c 'echo $usb_field:$device'")
                fi
            done
            ;;
    esac
    case "$result" in
        "No USB drives") ;;
        *)
            for xx in "${usb_sticks_info[@]}" ; do
                device="$(DeviceOf "$xx")"
                tmp="$(/usr/bin/df --output=source,target | grep "^$device" | awk '{print $2}')"
                if [ -n "$tmp" ] ; then
                    ((mounted_sticks++))
                    if [ $mounted_sticks -eq 1 ] ; then
                        cmd+=(--field="$(BTR msg_already_mounted)":LBL "")
                    fi
                    cmd+=(--field="\t\t<i>$xx</i>":LBL "")
                fi
            done
    esac
    case "$result" in
        "$(BTR msg_no_drives)" | "$(BTR msg_no_unmounted)")
            ;;
        *)
            cmd+=(--button="$(BTR word_burn)${exclamation}!$usb_icon!$(BTR msg_tip_title)":0)
            ;;
    esac
 
    result="$("${cmd[@]}" 2>/dev/null)"

    debug "result = '$result'"

    test -n "$result" || return

    iso_file="$(echo "$result" | cut -d '|' -f $iso_field)"
    if [ -n "$usb_stick" ] ; then
        usb_stick="$(echo "$usb_stick" | awk '{print $1}' | sed 's|:$||')"
    else
        usb_stick="$(echo "$result" | cut -d '|' -f $usb_field | awk '{print $1}' | sed 's|:$||')"
    fi

    if [ ! -r "$iso_file" ] ; then
        DIE "$(BTR die_iso_missing "$iso_file")"
    fi

    # Save ISO file folder to conf file
    sed -i "$conf" -e 's|^ISO_folder=.*$|ISO_folder="'"$(dirname "$iso_file")"'"|'

    case "$usb_stick" in
        "" | "$no_selection") DIE "$(BTR die_drive_not_selected)" ;;
    esac

    debug "iso file  = $iso_file"
    debug "usb stick = $usb_stick"

    Burn
}

DebugBreak() { : ; }

Main "$@"
