#!/bin/bash

# set -o euxo pipefail
# set -o euo pipefail

echo2() { echo -e "$@" >&2 ; }
debug() { test "$DEBUG" = "yes" && echo2 "Debug: " "$@" ; }
m_yad() { eos_yad --window-icon=$usb_icon --image=$usb_icon "$@" ; }

DIE_WARN() {
    local type="$1"
    shift
    echo2 "$progname $type: $1"
    m_yad --form --text="${type^}: $1" --title="$progname" \
          --button=yad-quit --width=400 --window-icon=dialog-"$type"
}
DIE()  { DIE_WARN error   "$1"; exit 1; }
WARN() { DIE_WARN warning "$1"; }

ConfField() {
    local fieldname="$1"
    grep "^$fieldname=" | cut -d '=' -f 2 | sed -e "s|^['\"]||" -e "s|['\"]$||"
}

DeviceOf() {
    local usb_line="$1"
    echo "$usb_line" | awk '{print $1}' | sed 's|:$||'
}

# DD_command() {
#     local iso_file="$1"
#     local usb_stick="$2"
#     echo "dd status=progress bs=4M if=$iso_file of=$usb_stick && sync"
# }

BurnFail() {
    local timeout=600
    local cmd=(NotifySend "$timeout"
               "USB drive burn stopped."
               "Burning the USB drive $usb_stick was canceled."
               "$is_foreground")
    "${cmd[@]}"
    exit 1
}
BurnSuccess() {
    debug "Syncing..."
    sync

    local timeout=30
    local cmd=(NotifySend "$timeout"
               "USB drive burn is ready."
               "Burning the USB drive $usb_stick is ready."
               "$is_foreground")
    "${cmd[@]}"
    exit 0
}

Burn() {
    if [ -x /bin/RunInTerminal ] ; then
        /bin/RunInTerminal "echo -e 'Burning to $usb_stick:' ; sudo burn2dev '$usb_stick' '$iso_file'" || BurnFail
    else
        pkexec burn2dev "$usb_stick" "$iso_file" || BurnFail
    fi
    BurnSuccess
}

NotifySend() {
    local sec="$1"
    local header="$2"
    local msg="$3"
    local is_foreground="$4"
    local ms="${sec}000"

    if [ "$is_foreground" = "no" ] ; then
        notify-send --expire-time="$ms" "$header" "$msg" &
    else
        notify-send --expire-time="$ms" "$header" "$msg"
        echo2 "Finished!"
        sleep 5
    fi
}

Open() {
    local op="$1"
    local app
    local apps=(kde-open exo-open xdg-open)
    shift
    case "$op" in
        edit) apps+=(kate gedit emacs xed codium geany) ;;
        open) ;;
    esac
    for app in "${apps[@]}" ; do
        if which "${app%% *}" &>/dev/null ; then
            $app "$@"
            exit 0
        fi
    done
    DIE "cannot find app to '$op'"
}

ReadConfig() {
    if [ ! -e "$conf" ] ; then
        echo2 "==> Creating config file ${conf/$HOME/\~}"
        cat <<EOF
#!/bin/bash

ISO_folder="\$HOME"
EOF
        test -r "$conf" || DIE "cannot create the configuration file '$conf'."
    fi

    ## shellcheck disable=SC1090                                          # variable 'conf' is readonly, why does shellcheck complain?
    ## shellcheck source=/dev/null                                        # shellcheck totally ignores what $conf referers to
    source "$conf" || DIE "cannot read configuration file '$conf'."
}

HandleParams() {
    local arg
    for arg in "$@" ; do
        case "$arg" in
            --edit-config | -e)
                Open edit "$conf"
                ;;
            --open-iso-folder)
                [ "$ISO_folder" ] || DIE "variable ISO_folder is not set, see file\n${conf/$HOME/\~}"
                Open open "$ISO_folder"
                ;;
            --show-disks)
                if [ -x /bin/RunInTerminal ] ; then
                    RunInTerminal lsblk -fm
                else
                    WARN "option '$arg' requires package 'eos-bash-shared'"
                fi
                exit 0
                ;;
            --fg)
                is_foreground=yes
                ;;
            -*)
                Usage 1
                ;;
            *)
                iso_file="$arg"
                ;;
        esac
    done
}

Usage() {
    cat <<EOF >&2
Usage:        $progname [options] [iso-file]
Options:      --edit-config, -e     Edit the config file ${conf/$HOME/\~}.
              --open-iso-folder     Open the folder configured in ${conf/$HOME/\~} with variable 'ISO_folder'.
              --show-disks          Show all disks to see which can be used for burning.
              --fg                  Notification at the end is in foreground (when started from a launcher).
Files:        iso-file              Path of the ISO file to burn.
EOF
    [ "$1" ] && exit "$1"
}

Main()
{
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1
    AssignIconVariables_in_eos_bash_shared

    local progname=stickburn
    local is_foreground=no
    local iso_file=""
    local -r usb_icon=drive-removable-media-usb
    local -r conf="$HOME/.config/$progname.conf"

    ReadConfig

    HandleParams "$@"

    local DEBUG=no

    local progname="stickburn"
    local usb_stick=""
    local iso_file_folder=""
    local iso_file_folder_conf=""
    local cmd=()
    local result=""
    # local dd_command
    local iso_field=2
    local usb_field=$((iso_field + 1))
    local xx device tmp
    local usb_sticks_info
    local usb_candidates=()
    local no_selection="(None)"
    local txt
    local mounted_sticks=0
    local -r exclamation='&#33;'

    if [ "$iso_file" ] ; then
        test -r "$iso_file" || DIE "ISO file '$iso_file' does not exist."
    fi

    echo2 "Finding USB drives, please wait..."
    readarray -t usb_sticks_info <<< "$(find-usb-sticks --separator " ")"

    [ "${usb_sticks_info[*]}" ] || DIE "no target USB drive available."

    for xx in "${usb_sticks_info[@]}" ; do
        test -n "$xx" || continue
        device="$(DeviceOf "$xx")"
        tmp="$(/usr/bin/df --output=source,target | grep "^$device" | awk '{print $2}')"
        if [ -z "$tmp" ] ; then
            usb_candidates+=("$xx")
        fi
    done

    iso_file_folder_conf="$(cat "$conf" | ConfField 'ISO_folder')"
    iso_file_folder="$iso_file_folder_conf"
    test -d "$iso_file_folder" || {
        # DIE "$conf: value of ISO_folder is not a folder."
        echo2 "Warning: $conf: value of ISO_folder cannot be used. Changing ISO_folder to \$HOME."
        iso_file_folder="$HOME"
    }

    cmd=(m_yad --form --title="$progname: Burn ISO to a USB drive" --scroll --height=350 --width=600)

    # button icon: media-record, usb-creator
    cmd+=(--button=yad-cancel:1)

    txt="Burn an ISO file to a USB drive."
    cmd+=(--text="$txt")

    txt="Select the ISO file from any folder. The selected folder will be auto-saved [<i>$iso_file_folder</i>].\n"
    txt+="Select the target USB drive (unless auto-selected).\n"
    txt+="Make <b><i>absolutely sure</i></b> you select the right USB drive.\n"
    txt+="There's no turning back after you start burning.\n"
    txt+="Burning takes a few minutes.\n"
    txt+="A notification window will appear when burning has finished.\n"
    cmd+=(--field="$txt":LBL "")

    if [ -z "$iso_file" ] ; then
        cmd+=(--field="<tt>ISO file:   </tt>":FL "$iso_file_folder/*")
    else
        cmd+=(--field="<tt>ISO file:   </tt>":RO "$iso_file")
    fi
    case "${#usb_candidates[@]}" in
        0)  case "${usb_sticks_info[0]}" in
                "")
                   cmd+=(--field="<i>Sorry, no USB drives found.</i>":LBL "")
                   result="No USB drives"
                   ;;
                *) txt="\n<i>Sorry, all USB drives are already mounted, cannot continue.\n"
                   txt+="USB drive must be umounted for burning.</i>"
                   cmd+=(--field="$txt":LBL "")
                   result="No umounted USB drives"
                   ;;
            esac
            ;;
        1)
            usb_stick="${usb_candidates[0]}"
            cmd+=(--field="<tt>USB drive:   </tt><b>$usb_stick</b>":LBL "")
            ;;
        *)  cmd+=(--field="<tt>USB drive:</tt>":RO "$no_selection")
            cmd+=(--field="\nSelect USB drive button below (unless already shown above):":LBL "")
            for xx in "${usb_sticks_info[@]}" ; do
                device="$(DeviceOf "$xx")"
                tmp="$(/usr/bin/df --output=source,target | grep "^$device" | awk '{print $2}')"
                if [ -z "$tmp" ] ; then
                    cmd+=(--field="$xx":fbtn "@bash -c 'echo $usb_field:$device'")
                fi
            done
            ;;
    esac
    case "$result" in
        "No USB drives") ;;
        *)
            for xx in "${usb_sticks_info[@]}" ; do
                device="$(DeviceOf "$xx")"
                tmp="$(/usr/bin/df --output=source,target | grep "^$device" | awk '{print $2}')"
                if [ -n "$tmp" ] ; then
                    ((mounted_sticks++))
                    if [ $mounted_sticks -eq 1 ] ; then
                        cmd+=(--field="\n\tUSB drives already mounted:":LBL "")
                    fi
                    cmd+=(--field="\t\t<i>$xx</i>":LBL "")
                fi
            done
    esac
    case "$result" in
        "No USB drives" | "No umounted USB drives")
            ;;
        *)
            cmd+=(--button="Burn${exclamation}!$usb_icon!Burns the selected ISO file to the selected USB drive":0)

            # txt="\n<b>Make absolutely sure you select the right USB drive.</b>\n"
            # txt+="<i>There's no turning back after you start burning.</i>\n\n"
            # txt+="Burning takes a few minutes.\n"
            # txt+="When burning has finished, a notification window will appear."
            # cmd+=(--field="$txt":LBL "")
            ;;
    esac
 
    result="$("${cmd[@]}" 2>/dev/null)"

    debug "result = '$result'"

    test -n "$result" || return

    iso_file="$(echo "$result" | cut -d '|' -f $iso_field)"
    if [ -n "$usb_stick" ] ; then
        usb_stick="$(echo "$usb_stick" | awk '{print $1}' | sed 's|:$||')"
    else
        usb_stick="$(echo "$result" | cut -d '|' -f $usb_field | awk '{print $1}' | sed 's|:$||')"
    fi

    if [ ! -r "$iso_file" ] ; then
        DIE "ISO file '$iso_file' does not exist."
    fi

    # Save ISO file folder to conf file
    sed -i "$conf" -e 's|^ISO_folder=.*$|ISO_folder="'"$(dirname "$iso_file")"'"|'

    case "$usb_stick" in
        "" | "$no_selection") DIE "USB drive not selected." ;;
    esac

    debug "iso file  = $iso_file"
    debug "usb stick = $usb_stick"

    Burn
}

Main "$@"
