#!/bin/bash

echo2() { echo "$@" >&2 ; }
debug() { test "$DEBUG" = "yes" && echo2 "Debug: " "$@" ; }
m_yad() { yad --window-icon=drive-removable-media-usb "$@" ; }

DIE() {
    echo2 "$progname error: $1"
    m_yad --form --text="Error: $1" --title="$progname error" \
          --button=yad-quit --width=400 --window-icon=dialog-error
    exit 1
}

ConfField() {
    local fieldname="$1"
    grep "^$fieldname=" | cut -d '=' -f 2 | sed -e "s|^['\"]||" -e "s|['\"]$||"
}

DeviceOf() {
    local usb_line="$1"
    echo "$usb_line" | awk '{print $1}' | sed 's|:$||'
}

DD_command() {
    local iso_file="$1"
    local usb_stick="$2"
    echo "dd status=progress bs=4M if=$iso_file of=$usb_stick && sync"
}

Main()
{
    local iso_file="$1"

    local DEBUG=no

    #test "$(uname -n)" = "kuulas" && DEBUG=yes    # TESTING ONLY !!!

    local progname="stickburn"
    local usb_stick=""
    local conf="$HOME/.config/$progname.conf"
    local iso_file_folder="."
    local iso_file_folder_conf=""
    local cmd=()
    local result=""
    local dd_command
    local iso_field=1
    local usb_field=2
    local xx device tmp
    local usb_sticks_info
    local usb_candidates=()
    local no_selection="(None)"
    local txt

    if [ -n "$iso_file" ] ; then
        test -r "$iso_file" || DIE "ISO file '$iso_file' does not exist."
    fi

    echo2 "Finding USB drives, please wait..."
    readarray -t usb_sticks_info <<< "$(find-usb-sticks)"
    for xx in "${usb_sticks_info[@]}" ; do
        device="$(DeviceOf "$xx")"
        tmp="$(/usr/bin/df --output=source,target | grep "^$device" | awk '{print $2}')"
        if [ -z "$tmp" ] ; then
            usb_candidates+=("$xx")
        fi
    done

    if [ -r "$conf" ] ; then
        iso_file_folder_conf="$(cat "$conf" | ConfField 'ISO_folder')"
        iso_file_folder="$iso_file_folder_conf"
        test -d "$iso_file_folder" || DIE "$conf: value of ISO_folder is not a folder."
    fi

    cmd=(m_yad --form --title="Burn ISO to a USB drive" --width=600 --height=400)

    # button icon: media-record, usb-creator
    cmd+=(--button=yad-cancel:1)

    if [ -z "$iso_file" ] ; then
        cmd+=(--field="Selected ISO file":FL "$iso_file_folder/*")
    else
        cmd+=(--field="Selected ISO file":RO "$iso_file")
    fi
    case "${#usb_candidates[@]}" in
        0)  case "${#usb_sticks_info[@]}" in
                0) cmd+=(--field="<i>Sorry, no USB drives found.</i>":LBL "")
                   result="No USB drives"
                   ;;
                *) txt="\n<i>Sorry, all USB drives are already mounted, cannot continue.\n"
                   txt+="USB drive must be umounted for burning.</i>"
                   cmd+=(--field="$txt":LBL "")
                   result="No umounted USB drives"
                   ;;
            esac
            ;;
        1)
            usb_stick="${usb_candidates[0]}"
            cmd+=(--field="Selected USB drive: <b>$usb_stick</b>":LBL "")
            ;;
        *)  cmd+=(--field="Selected USB drive":RO "$no_selection")
            cmd+=(--field="\nSelect USB drive button below (unless already shown above):":LBL "")
            for xx in "${usb_sticks_info[@]}" ; do
                device="$(DeviceOf "$xx")"
                tmp="$(/usr/bin/df --output=source,target | grep "^$device" | awk '{print $2}')"
                if [ -z "$tmp" ] ; then
                    cmd+=(--field="$xx":fbtn "@bash -c 'echo $usb_field:$device'")
                fi
            done
            ;;
    esac
    case "$result" in
        "No USB drives") ;;
        *)
            cmd+=(--field="\n\tUSB drives already mounted:":LBL "")
            for xx in "${usb_sticks_info[@]}" ; do
                device="$(DeviceOf "$xx")"
                tmp="$(/usr/bin/df --output=source,target | grep "^$device" | awk '{print $2}')"
                if [ -n "$tmp" ] ; then
                    cmd+=(--field="\t\t<i>$xx</i>":LBL "")
                fi
            done
    esac
    case "$result" in
        "No USB drives" | "No umounted USB drives")
            ;;
        *)
            cmd+=(--button="Start burning now!usb-creator!Burns the selected ISO file to the selected USB drive":0)

            txt="\n<b>Make absolutely sure you select the right usb drive!</b>\n"
            txt+="<i>There's no turning back after you start burning!</i>\n\n"
            txt+="When burning has finished, a notification window appears."
            cmd+=(--field="$txt":LBL "")
            ;;
    esac
 
    result="$("${cmd[@]}")"
    debug "result = '$result'"

    test -n "$result" || return

    iso_file="$(echo "$result" | cut -d '|' -f $iso_field)"
    if [ -n "$usb_stick" ] ; then
        usb_stick="$(echo "$usb_stick" | awk '{print $1}' | sed 's|:$||')"
    else
        usb_stick="$(echo "$result" | cut -d '|' -f $usb_field | awk '{print $1}' | sed 's|:$||')"
    fi

    if [ ! -r "$iso_file" ] ; then
        DIE "ISO file '$iso_file' does not exist."
    fi
    case "$usb_stick" in
        "" | "$no_selection") DIE "USB drive not selected." ;;
    esac
    if [ -n "$(df --output=source,target | grep "^$usb_stick" | awk '{print $2}')" ] ; then
        DIE "USB drive '$usb_stick' is mounted. Please umount it first!"
    fi

    debug "iso file  = $iso_file"
    debug "usb stick = $usb_stick"

    dd_command="dd status=progress oflag=direct bs=4M if=$iso_file of=$usb_stick"

    echo2 "Command: $dd_command"
    echo2 "Starting to burn. It takes several minutes, be patient ..."
    pkexec $dd_command || {
        echo2 "Canceled."
        return 1
    }

    debug "Syncing..."
    sync

    notify-send --expire-time=30000 \
                "USB drive burn is ready." \
                "Burning the USB drive $usb_stick is ready." &
}

Main "$@"
