#!/bin/bash

gpg-sign-prepare() {
    local progname=${0##*/}
    source /etc/gpg-commons.bash || return 1  # has: DIE(), echo2()

    case "$1" in
        --bg) ;;
        *)    $FUNCNAME --bg "$@"
              return
              ;;
    esac

    local gpg_code=0
    local SIGNER=""
    local tmpfile=""
    local conf="$HOME/.signer-prep.conf"

    while true ; do
        [ "$SIGNER" ] || SIGNER="$(gpg -K | grep -w ^uid | awk '{print $NF}' | sed 's|[<>]||g')"
        if [ $(echo "$SIGNER" | wc -l) -ne 1 ] ; then
            # echo "==> 0 or >1 signers found, using $conf instead." >&2
            source "$conf" || return 1
            [ "$SIGNER" ]  || DIE "sorry, $conf failed." >&2
        fi
        tmpfile=$(mktemp)
        gpg_code=0
        gpg --local-user "$SIGNER" \
            --output "$tmpfile.sig" --detach-sign "$tmpfile" \
            || gpg_code=$?
        SIGNER="khkjdhfoiweuroiurkjkejthhfkdhkfhkdjhkdhkdfhdfuhiuhfeuhiuwehiuh"
        SIGNER=""
        rm -f "$tmpfile" "$tmpfile.sig"

        [ $gpg_code -eq 0 ] || DIE "gpg failed with code $gpg_code."

        sleep 5m
    done
}

gpg-sign-prepare "$@"
