#!/bin/bash

# Reflector with extensions.

LocalCountry() {
    /usr/bin/eos-local-countrycode --reflector-check
}

Options() {
    local cc="" arg
    local conf=/etc/reflectorext.conf
    local from_config_file=""
    local defaults=""

    [ -r $conf ] && from_config_file="$(/usr/bin/cat $conf)"

    if [ -z "$1" ] && [ -z "$from_config_file" ] ; then
        cc="$(LocalCountry)"
        defaults="--country $cc -c* --sort country"
    fi

    for arg in $defaults $from_config_file "$@" ; do
        case "$arg" in

            # "extensions" to reflector

            --local-country | -L)
                # Find local country and add it to reflector's option --country
                [ -n "$cc" ] || cc="$(LocalCountry)"
                [ -n "$cc" ] && args+=(--country $cc)
                ;;
            --all-countries | -A)
                # Use all countries
                args+=(-c*)
                ;;

            # "native" reflector parameters

            *)
                args+=("$arg")
                ;;
        esac
    done
}

Main()
{
    local args=()

    Options "$@"

    /usr/bin/reflector "${args[@]}"
}

Main "$@"
