#!/bin/bash

# Reflector with extensions.

LocalCountry() {
    /usr/bin/eos-local-countrycode --reflector-check
}

Options() {
    local cc="" arg
    local conf=/etc/reflectorext.conf
    local from_config_file=""
    local defaults=""

    [ -r $conf ] && from_config_file="$(/usr/bin/cat $conf)"

    # default values
    cc="$(LocalCountry)"
    [ -n "$cc" ] && defaults="--country $cc"
    defaults+=" -c* --sort country"

    if [ -z "$1" ] && [ -z "$from_config_file" ] ; then
        from_config_file="$defaults"
    fi

    for arg in $from_config_file "$@" ; do
        case "$arg" in

            # "extensions" to reflector

            --local-country | -L)
                # Find local country and add it to reflector's option --country
                [ -n "$cc" ] && args+=(--country $cc)
                ;;
            --add-defaults | -A)
                # Add the defaults above
                args+=($defaults)
                ;;

            # "native" reflector parameters

            *)
                args+=("$arg")
                ;;
        esac
    done
}

Main()
{
    local args=()

    Options "$@"

    /usr/bin/reflector "${args[@]}"
}

Main "$@"
