#!/bin/bash

echo2() { echo -e "$@" >&2 ; }
DIE2()  { echo2 "==> $PROGNAME: error: $1\n"; Usage; exit 1; }
Usage() {
    cat <<EOF
Usage: $progname [options] [filename(s)]

Options:
    -h, --help         This help.
    -s | --save        Backup the old file before the operation.
    --search-details   Show details about searched files.
Parameters:
    filename(s)        File name(s) with one of the suffixes .pacnew, .pacsave, .pacorig.
                       Without file names /etc/*.pac{new,orig,save} will be looked for.

EOF
}

Differ() {
    local tmp

    for tmp in "${EOS_WELCOME_PACDIFFERS[@]}" ; do
        if type "$tmp" &> /dev/null ; then
            echo "$tmp"
            return 0
        fi
    done
    DIE2 "differ not found."
}

Date() { date +%Y%m%d-%H%M ; }

RemoveIdentical() {
    local -r pacfile="$1"
    local -r file="$2"

    if diff "$pacfile" "$file" >/dev/null ; then
        Elevated rm -f "$pacfile"
        Msg "$pacfile was identical, removed"     # identical files
        return 0
    else
        return 1
    fi
}

MERGE() {
    local -r pacfile="$1"
    local -r file="$2"

    Elevated $DIFFER "$pacfile" "$file"
    RemoveIdentical  "$pacfile" "$file"
}
REMOVE()    { [ -e "$1" ] || return; Elevated rm -f "$1" ; Msg "$1 removed" ; }
OVERWRITE() { [ -e "$1" ] || return; Elevated mv "$1" "$2" ; Msg "$2 overwritten by $1" ; }
SKIP()      { [ -e "$1" ] || return; Msg "$1 skipped" ; }
LIST()      { RunInTerminal "echo '$pacfiles'"; return 1; }

case "$(id)" in
    *"(wheel)"*) Elevated() { /bin/sudo bash -c "$*"    || echo quit_now ; } ;;
    *"(root)"*)  Elevated() { bash -c "$*"              || echo quit_now ; } ;;
    *)           Elevated() { su-c_wrapper bash -c "$*" || echo quit_now ; } ;;
esac

Msg() { echo -e "==> $1" >&2 ; }

# export -f MERGE Elevated Msg RemoveIdentical
# export -f echo2 DIE2 Usage

Operate() {
    local cmd=(
        eos_yad --form --title="$progname $pacfile" --text="$text"
        --use-interp --buttons-layout=center
        --button="$b_list!!List all detected pacfiles":$e_list
        --button="$b_merge!!Help merging individual changes with <b>meld</b> from $pacfile":$e_merge
        --button="$b_skip!!Ignore $pacfile for now":$e_skip
        --button="$b_remove!!Remove $pacfile":$e_remove
        --button="$b_overwrite!!Be cautious$EXCLAMATION Will overwrite $file":$e_overwrite
        --button="$b_quit!!Quit this program now":$e_quit
    )
    local msg retval=0
    msg=$("${cmd[@]}")
    retval=$?
    case "$msg" in
        quit_now) exit $retval ;;
    esac
    case $retval in
        $e_merge)     MERGE     "$pacfile" "$file" || Operate ;;  # Why Operate again: MERGE may not remove the pacfile,
                                                                  # so give a change to e.g. skip it.
        $e_list)      LIST || Operate ;;
        $e_skip)      SKIP      "$pacfile" ;;
        $e_remove)    REMOVE    "$pacfile" ;;
        $e_overwrite) OVERWRITE "$pacfile" "$file" ;;
        $e_quit)      exit 0 ;;
    esac
}

OperationSelector() {
    case "$(id)" in
        *"(wheel)"*) /bin/sudo -v || DIE2 "program quits." ;;         # NOP to get 'sudo' "initialized" while still in terminal (?)
    esac

    RemoveIdentical "$pacfile" "$file" && return 0

    local -r b_list="List"
    local -r b_merge="Merge manually"
    local -r b_remove="Remove"
    local -r b_overwrite="Overwrite"
    local -r b_skip="Skip"
    local -r b_quit="Quit"

    local -r e_list=11
    local -r e_merge=1
    local -r e_remove=3
    local -r e_overwrite=5
    local -r e_skip=7
    local -r e_quit=9

    local text=""
    text+="<b>Merging or ignoring changes.</b>\n\n"

    if false ; then
    text+="<b>$b_list</b> pacfiles that were detected on the system.\n"
    text+="<b>$b_merge</b> with <i>meld</i> helps including useful changes from file\n <tt>    $pacfile</tt>\n<tt>  </tt>into file\n <tt>    $file</tt>\n"
    text+="<b>$b_skip</b> $pacfile if you are unsure what to do. Handle it later if needed.\n"
    text+="<b>$b_remove</b> simply deletes file $pacfile.\n"
    text+="<b>$b_overwrite</b> overwrites $file with $pacfile. Use it with great care!\n"
    text+="<b>$b_quit</b> will quit this program immediately.\n"
    fi

    text+="\nTips:\n"
    text+="  - Use command line option <tt>--save</tt> to backup the existing $file.\n"
    text+="  - If the files are identical, $pacfile will automatically be removed.\n"

    local -r EXCLAMATION='&#33;'

    Operate
}

Save() {
    local -r file="$1"
    local -r bak="$file.bak.$(Date)"
    local retval=0
    local msg=$(Elevated cp -a "$file" "$bak")
    retval=$?
    case "$msg" in
        quit_now) exit $retval ;;
    esac
    
    Msg "$bak saved"
}

RefuseCriticalFiles() {
    local xx="$1"
    if [ $save = no ] && [ "$xx" ] ; then
        # Don't continue with system critical files.
        local first=${xx%.*}
        local second=${xx##*.}
        case "$(realpath "$first")" in
            /etc/passwd | /etc/group | /etc/shadow)                      # system critical files
                case "$second" in
                    pacnew | pacsave | pacorig)
                        DIE2 "sorry, $xx is an essential system file, refusing to continue without option --save."
                        ;;
                esac
                ;;
        esac
    fi
}

RefuseOptionsHere() {
    [ ${1::1} = "-" ] && DIE2 "'$1': options must be given before any file name."
}

FindPacFiles() {
    local search_details="$1"
    local suffix
    local tmp

    for suffix in pacnew pacorig pacsave ; do
        tmp="$(find /etc -name \*.$suffix 2>/dev/null)"                                                            # files with suffixes
        if [ "$tmp" ] ; then
            case "$search_details" in
                no)  tmp="$(/bin/ls -1 $(echo "$tmp" | sed "s|\.$suffix$||") 2>/dev/null | sed "s|$|.$suffix|")"   # files without suffixes
                     ;;
                yes) echo2 "\n==> .$suffix files found:"
                     echo "$tmp\n" | sed 's|^|    |' >&2
                     tmp="$(/bin/ls -1 $(echo "$tmp" | sed "s|\.$suffix$||")             | sed "s|$|.$suffix|")"   # files without suffixes; non-existing to stderr
                     ;;
            esac
            if [ "$tmp" ] ; then
                echo "$tmp"
            fi
        fi
    done
}

Pachandle() {
    local progname=${0##*/}
    export PROGNAME="$progname"
    local save=no
    local search_details=no
    local pacfile=""                # pacfile == file.pac{new,save,orig}
    local file=""
    local xx
    local sourced=no
    local pacfiles=()
    local refuseOptions=no

    while [ "$1" ] ; do
        case "$1" in
            -*)
                [ $refuseOptions = yes ] && RefuseOptionsHere "$1"
                case "$1" in
                    --dump-options)   echo "-h -s --help --save --search-details"; exit 0 ;;  # for bash completion
                    -h | --help)      Usage; exit 0 ;;
                    -s | --save)      save=yes; shift ;;
                    --search-details) search_details=yes; shift ;;
                    -*)               DIE2 "option $1 is not supported" ;;
                esac
                ;;
            *)
                RefuseCriticalFiles "$1"
                refuseOptions=yes
                pacfiles+=("$1")
                shift
                ;;
          esac
    done
    if [ ${#pacfiles[@]} -eq 0 ] ; then
        pacfiles="$(FindPacFiles $search_details)"
        if [ -z "$pacfiles" ] ; then
            [ "$search_details" = yes ] && echo2 ""
            echo2 "==> *.pacnew, *.pacorig, *.pacsave: not found under /etc"
            return 1
        fi
        readarray -t pacfiles <<< $(echo "$pacfiles")
    fi

    for pacfile in "${pacfiles[@]}" ; do
        file="${pacfile%.pac*}"     # file without suffix

        case "$pacfile" in
            *.pacnew | *.pacsave | *.pacorig)
                [ -e "$pacfile" ] || DIE2 "$pacfile not found."
                [ -e "$file" ]    || DIE2 "$file not found."

                [ "$save" = yes ] && Save "$file"

                if [ $sourced = no ] ; then
                    source /usr/share/endeavouros/scripts/eos-script-lib-yad || exit 1
                    export DIFFER="$(Differ)"
                    sourced=yes
                fi

                OperationSelector
                ;;
            "") DIE2 "please give a file name, e.g. '/etc/locale.gen.pacnew'." ;;
            *)  DIE2 "the file name must contain suffix [.pacnew|.pacsave|.pacorig], e.g. '/etc/locale.gen.pacnew'." ;;
        esac
    done
}

Pachandle "$@"
