#!/bin/bash

echo2()   { [ $verbosity != deaf ] && echo -e "$@" >&2 ; }
Message() { [ $verbosity = loud ] && echo2 "$@" ; }

InGitTree() {
    local dir="$PWD"
    while [ "$dir" ] ; do
        [ -d "$dir/.git" ] && return 0
        dir="${dir%/*}"
    done
    return 1
}

MELD() { meld "$@" &> /dev/null & }

Help() {
    local -r progname=${0}
    cat <<EOF
Purpose: Extend 'meld' to make comparison(s) with either 'meld' or 'rcsdiff' parameters.
         Plain 'meld' command will assume '.' as the parameter.
Usage:   $progname [verbosity-options] [tool-options] [vcs-options] [parameters]

Verbosity options:
        -l, --loud         Show all messages. Default.
        -q, --quiet        Show less messages.
        -d, --deaf         Show no messages.
Tool options:
        -G                 Comparison using GIT instead of RCS.
        -R                 Comparison using RCS instead of GIT.
        -h, --help         This info and help from meld.
Vcs options:               For meld: any options for 'meld'.
                           For RCS:  any options for 'rcsdiff'.
Parameters (meld extension):                
        file folder        Show 'meld' comparison between given 'file' with
                           the same file in the given 'folder'.
        folder file        -"-
        folder folder      Show 'meld' comparison between two folders.
Parameters (other cases):
        Any 'meld' or 'rcsdiff' parameters.

EOF
}

Meld() {
    local cmd=()
    local verbosity=loud
    local compare=""

    while [ "$1" ] ; do
        case "$1" in
            -l | --loud)      verbosity=loud ;;
            -q | --quiet)     verbosity=quiet ;;
            -d | --deaf)      verbosity=deaf ;;

            -G)               compare=git ;;
            -R)               compare=rcs ;;

            -h | --help)      {
                                  Help
                                  case "$compare" in
                                      git) /bin/meld --help ;;
                                      rcs) /bin/rcsdiff --help ;;
                                      *) /bin/meld --help ; /bin/rcsdiff --help ;;
                                  esac
                              } | less
                              exit
                              ;;
            *)                break ;;
        esac
        shift
    done
    local count=${#@}
    local done=no

    if [ "$count" -eq 2 ] ; then
        if [ -d "$1" ] && [ -f "$2" ] ; then
            # meld: handle 2 parameters: folder and file.
            cmd=(MELD "${1%/}/${2##*/}" "$2")
            Message "==> meld: folder & file comparison detected"
            done=yes
        elif [ -f "$1" ] && [ -d "$2" ] ; then
            # meld: handle 2 parameters: file and folder.
            cmd=(MELD "$1" "${2%/}/${1##*/}")
            Message "==> meld: file & folder comparison detected"
            done=yes
        elif [ -e "$1" ] && [ -e "$2" ] ; then
            # meld: handle 2 parameters: either files or folders.
            cmd=(MELD "$1" "$2")
            Message "==> meld: 2 file or folder comparison detected"
            done=yes
        fi
    fi
    if [ "$done" = no ] ; then
        # Other parameter set, use either 'meld with git' or 'meld with rcsdiff'
        case "$compare" in
            git) shift
                cmd=(meldgit "$@")
                Message "==> 'meld with git' selected"
                ;;
            rcs) shift
                cmd=(meldrcs "$@")
                Message "==> 'meld with rcsdiff' selected"
                ;;
            *)  if [ -d RCS ] ; then
                    cmd=(meldrcs "$@")
                    Message "==> 'meld with rcsdiff' detected"
                elif InGitTree ; then
                    cmd=(meldgit "$@")
                    Message "==> 'meld with git' detected"
                else
                    Message "==> cannot detect the needed comparison!"
                    exit 1
                fi
                ;;
        esac
    fi
    echo2 "==> ${cmd[*]}"
    "${cmd[@]}"
}

Meld "$@"
