#!/bin/bash

DIE() {
    source /etc/bash-colors.conf
    [ "$RED" ]   || local -r RED=""
    [ "$RESET" ] || local -r RESET=""
    local -r progname="${0##*/}"
    echo -e "${RED}$progname: error: $1${RESET}" >&2
    exit 1
}

MELD() {
    /bin/meld "$@" &  # &> /dev/null &
}

Modify2para() {
    local -n _ff="$1"   # file
    local -n _dd="$2"   # folder

    [ "${_ff//\//}" = "$_ff" ] && _ff="./$_ff"     # if no dir in the file, add ./ in front
    [ "$_dd" != "/" ]          && _dd="${_dd%/}"   # remove possible trailing slash
    _dd="$_dd/${_ff##*/}"                          # add file name after the folder name
}

MELD2PARA() {
    # Handle two parameters.
    # A special case: if the two parameters are (in either order):
    #    - FolderA/file
    #    - FolderB
    # compare FolderA/file with FolderB/file.

    local aa="$1"
    local bb="$2"

    if [ -d "$aa" ] && [ -f "$bb" ] ; then
        Modify2para bb aa
    elif [ -f "$aa" ] && [ -d "$bb" ] ; then
        Modify2para aa bb
    fi

    MELD "$aa" "$bb"
}

InGitTree() {
    local dir="$PWD"
    while [ "$dir" ] ; do
        [ -d "$dir/.git" ] && return 0
        dir="${dir%/*}"
    done
    return 1
}

Meld() {
    # Changing meld operation:
    # - plain 'meld' means 'meld .'
    # - compare two files when one parameter is a folder

    # Counting $lines does not work on a single line ???
    local lines=$(/bin/ps -C meld)
    lines=$(echo "$lines" | grep -w meld)
    lines=$(echo "$lines" | wc -l)             # this instance counts...
    local -r max_meld_instances=2
    [ $lines -gt $max_meld_instances ] && DIE "sorry, no more 'meld' instances are allowed to run."

    local -r meldgit=/bin/meldgit
    local -r meldrcs=/bin/meldrcs

    case "$1" in
        -R) shift; $meldrcs "$@" ;;
        -G) shift; $meldgit "$@" ;;
        "") if InGitTree ; then
                $meldgit
            elif [ -d RCS ] ; then
                $meldrcs
            else
                MELD
            fi
            ;;
        *)  if [ "$2" ] && [ "$1 $2" = "$*" ] ; then
                MELD2PARA "$@"           # 2 parameters, may have a file and a folder
            else
                MELD "$@"                # other cases
            fi
            ;;
    esac
}

Meld "$@"
