#!/bin/bash

DIE() {
    source /etc/bash-colors.conf
    [ "$RED" ]   || local -r RED=""
    [ "$RESET" ] || local -r RESET=""
    local -r progname="${0##*/}"
    echo -e "${RED}$progname: error: $1${RESET}" >&2
    exit 1
}

MELD() {
    /bin/meld "$@"  &> /dev/null &
}

Meld() {
    # Changing meld operation:
    # - plain 'meld' means 'meld .'
    # - compare two files when one parameter is a folder

    local git_diffs code=0
    git_diffs="$(git diff 2>/dev/null)" || code=$?

    case "$code" in
        0)  if [ "$git_diffs" ] ; then
                case "$1" in
                    "") MELD . ;;
                    *)  MELD "$@" ;;
                esac
            else
                echo "No git diffs." >&2
            fi
            ;;
        129)
            MELD "$@"        # no git, just run meld
            # DIE "'git diff' problem, code $code.\n$PWD is not a git directory?"
            ;;
        *)
            DIE "'git diff' problem, code $code"
            ;;
    esac
}

Meld "$@"
