#!/bin/bash
#
# Arch change log for a package.
#
# Uses the BROWSER_ARCH_CL and BROWSER environment variables, exo-open, xdg-open (in this order)
# and various common browser names.
#

_DIE() {
    echo "Error: $1" >&2
    test -n "$infofile" && rm -f "$infofile"
    exit 1
}

_DIE2() {
    echo "Error:" >&2
    echo "$1" >&2
    test -n "$infofile" && rm -f "$infofile"
    exit 1
}

_find_url()
{
    local pkg="$1"
    local url="https://www.archlinux.org/packages/?sort=&q=$pkg"
    local path repo arch pkg2
    local infofile=$(mktemp)

    wget -q -O $infofile "$url"
    path=$(grep 'View package details for' $infofile | head -n 1 | sed -e 's|^.*a href="||' -e 's|/" title.*$||')

    # path = /packages/<repo>/<arch>/<pkg>
    repo=$(echo $path | cut -d '/' -f 3)
    arch=$(echo $path | cut -d '/' -f 4)
    pkg2=$(echo $path | cut -d '/' -f 5)

    if [ "$pkg2" != "$pkg" ] ; then
        if [ -n "$pkg2" ] ; then
            _DIE2 "$(while true ; do
                  echo "Only these packages match, possibly select one of them:"
                  grep 'View package details for' $infofile | sed -e 's|^.*a href="||' -e 's|/" title.*$||' | cut -d '/' -f 5 | sed 's|^|    |'
                  break
                  done
                  )"
        else
            _DIE "No match."
        fi
    fi

    printf "" > $infofile
    wget -q -O $infofile "https://www.archlinux.org/packages/$repo/$arch/$pkg"
    url="$(grep "View changes for " $infofile | sed -e 's|^.*href="||' -e 's|" title=.*$||')&showmsg=1"

    rm -f $infofile

    echo "$url"
}

_arch_pkg_changelog()
{
    local pkg="$1"
    local browser_ok=0

    test -n "$pkg" || _DIE "no package given."
    pacman -Si "$pkg" >& /dev/null || _DIE "Package '$pkg' does not exist."

    local browser br
    local browsers=(              # order is significant
        "$BROWSER_ARCH_CL"
        "$BROWSER"
        "exo-open --launch WebBrowser"
        xdg-open
        chromium
        firefox
        vivaldi-stable
        opera
        falkon
    )
    local url="$(_find_url "$pkg")"
    test -n "$url" || return 1

    for browser in "$BROWSER_ARCH_CL" "$BROWSER" "$exo" "$xdg" chromium firefox vivaldi-stable opera falkon
    do
        test -n "$browser" || continue
        br=$(basename "$(echo "$browser" | awk '{print $1}')")      # find plain program name
        if [ -x /usr/bin/$br ] ; then
            $browser "$url" >& /dev/null &
            browser_ok=1
            break
        fi
    done
    test $browser_ok -eq 0 && _DIE "no web browser available!"
}

_arch_pkg_changelog "$@"
