#!/bin/bash

md() {
  local prog

  for prog in vscodium codium code-oss code ghostwriter
  do
    if [ -x /usr/bin/$prog ] ; then
        echo "$prog" "$@" >&2
        case $prog in
            ghostwriter) 
                $prog "$@"
                ;;
            *)
                $prog --new-window "$@"
                ;;
        esac
       break
    fi
  done
}

md "$@"
