#!/bin/bash

md() {
  local prog

  for prog in vscodium code-oss code
  do
    if [ -x /usr/bin/$prog ] ; then
       echo "$prog" "$@" >&2
       $prog --new-window "$@"
       break
    fi
  done
}

md "$@"
