#!/bin/bash

case "$(id)" in
    *"(root)"* | *"(wheel)"*)
        # Normal sudo for users in root or wheel group.
        /usr/bin/sudo "$@"
        ;;
    *)
        # Others get a sudo-like command without any support for sudo options.
        pkexec --keep-cwd "$@"
        ;;
esac
