#!/bin/bash
#
# Retuns a URL for an app.
# The URL contains information about the app.
#
# Examples:
#    appinfourl                         # shows a GUI launcher for the supported apps
#    appinfourl virtualbox              # shows the URL where virtualbox info is found
#    firefox $(appinfourl virtualbox)   # shows virtualbox manual
#

DIE() {
    echo "$progname: error: $1"
    exit 1
}

ShowAllItems() {
    local app url
    echo "Supported apps and related URLs"
    while true ; do
        echo "name URL URL2"
        echo "~~~~ ~~~ ~~~~"
        for app in "${Items[@]}" ; do
            local -n urls=$app
            printf "%s" "$app"
            for url in "${urls[@]}" ; do
                printf " %s" "$url"
            done
            printf "\n"
        done
        break
    done | column -t | sed 's|^|    |' | /usr/bin/less -RF
}

ShowAppUrl() {
    local app2="$1"
    local app url
    for app in "${Items[@]}" ; do
        if [ "$app" = "$app2" ] ; then
            local -n urls=$app
            if [ "$local_first" = "yes" ] ; then
                url="${urls[1]}"
                if [ ! -r "$url" ] ; then
                    url="${urls[0]}"
                fi
            else
                url="${urls[0]}"
            fi
            if [ -n "$url" ] ; then
                echo "$url"
            fi
            return
        fi
    done
}

Fetch() {
    local tmpfile="$1"
    local url="$2"
    local result=0

    wget -q -O "$tmpfile" "$url"
    result=$?
    if [ $result -ne 0 ] ; then
        DIE "wget $tmpfile failed, code $result."
    fi
}

UpdateLocalDocs() {
    local app url
    local tmpdir=$(/usr/bin/mktemp -d)
    local tmpfile
    local cmds=""

    [ $quiet = no ] && echo "Updating local docs..." >&2

    /usr/bin/mkdir -p $tmpdir

    for app in "${Items[@]}" ; do
        local -n urls=$app
        if [ -n "${urls[1]}" ] && [[ "${urls[1]}" =~ \.html$ ]] ; then
            [ $quiet = no ] && echo "$app" >&2
            tmpfile="$tmpdir/$(basename "${urls[1]}")"
            Fetch "$tmpfile" "${urls[0]}"
            [ -n "$cmds" ] && cmds+="; "
            cmds+="mkdir -p /usr/share/doc/$app; cp $tmpfile /usr/share/doc/$app/"
        fi
    done
    [ -n "$cmds" ] && $EOS_ROOTER "$cmds"

    /usr/bin/rm -rf $tmpdir
}

Variables() {
    # adjust variables if they are not OK

    local xx

    xx=$(echo "$browser" | /usr/bin/awk '{print $1}')
    if [ -n "$(/usr/bin/which "$xx" 2>/dev/null)" ] ; then
        return
    fi

    for xx in /usr/bin/exo-open /usr/bin/xdg-open ; do
        /usr/bin/which "$xx" >& /dev/null && {
            browser="$xx"
            return
        }
    done
    DIE "no browser found."
}

Options() {
    local opts
    local optnames_long=apps,browser:,help,options,quiet,remote-first,show-apps,update,verbose
    local optnames_short=hqrsuv

    opts="$(/usr/bin/getopt -o=$optnames_short --longoptions $optnames_long --name "$progname" -- "$@")" || {
        Options --help
        exit 1
    }

    eval set -- "$opts"

    while true ; do
        case "$1" in
            --apps)                      # useful for bash completion!
                printf "%s\n" "${Items[@]}"
                exit 0
                ;;
            --browser)
                browser="$2"
                shift
                ;;
            --options)                    # useful for bash completion!
                printf "%s " "$optnames_long"  | /usr/bin/sed -e 's|,| --|g' -e 's|^|--|' -e 's|:||g'
                echo "$optnames_short" | /usr/bin/sed -e 's|\([a-z]\)| -\1|g' -e 's|:||g'
                exit 0
                ;;
            --remote-first | -r)
                local_first=no
                ;;
            --update | -u)
                UpdateLocalDocs
                exit 0
                ;;
            --show-apps | -s)
                ShowAllItems
                exit 0
                ;;
            --quiet | -q)
                quiet=yes
                ;;
            --verbose | -v)
                quiet=no
                ;;

            --help | -h)
                cat <<EOF >&2
Usage: $progname [options] [appname]
Options:
  --apps           Show supported app names. Helps bash completion.
  --show-apps      Show supported apps and respective URLs.
  -s               -"-
  --browser        Set the program that can show URLs. Default: $browser_def.
  --options        Show all options. Helps bash completion.
  --update         Update local docs from the internet.
  -u               -"-
  --remote-first   Show Internet docs instead of local docs.
  -r               -"-
  --quiet          Don't show progress messages, but only error messages.
  -q               -"-
  --verbose        Show all messages (opposite of --quiet). This is the default.
  -v               -"-
  --help           Show this help.
  -h               -"-
Params:
  appname          Name of the application whose info URL shows.
                   Without appname all supported apps and URLs will be shown.

Configuration file $conf2 currently supports
the following variables (note: use 'bash' syntax):
   APPDOC_WEB_BROWSER               # see option --browser
   APPDOC_QUIET                     # see option --quiet

   Example:
     APPDOC_WEB_BROWSER=firefox   # set your preferred browser here
     APPDOC_QUIET=yes             # prevent most messages
EOF
                exit 0
                ;;
            
            --) shift ; break ;;
        esac
        shift
    done

    application="$1"
}

Main() {
    # for EOS_ROOTER:
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || exit 1

    local progname="$(/usr/bin/basename "$0")"
    local conf="$HOME/.config/$progname.conf"
    local conf2="\$HOME/.config/$progname.conf"
    local application=""
    local local_first=yes
    local quiet=no
    local browser_def=xdg-open
    local browser=$browser_def
    local db=appdoc.data
    local databases=(
        "$HOME/.config/$db"
        "/etc/$db"
    )
    local url
    local args=()
    local APPDOC_WEB_BROWSER=""   # potentially from config file
    local APPDOC_QUIET=no
    local config_file_read=no

    for db in "${databases[@]}" ; do
        if [ -r "$db" ] ; then
            source "$db" || DIE "reading database file '$db' failed."
            break
        fi
    done

    # Get options from the config file
    if [ -r "$conf" ] ; then
        source "$conf" || DIE "reading config file '$conf' failed."
        config_file_read=yes
        if [ -n "$APPDOC_WEB_BROWSER" ] ; then
            args+=(--browser="$APPDOC_WEB_BROWSER")
        fi
        if [ -n "$APPDOC_QUIET" ] ; then
            quiet="$APPDOC_QUIET"
        fi
    fi

    # Add command line options
    args+=("$@")

    Options "${args[@]}"
    Variables

    if [ $config_file_read = yes ] ; then
        # delayed info message...
        [ $quiet = no ] && echo "Config file $conf2 read." >&2
    fi

    if [ -n "$application" ] ; then
        url="$(ShowAppUrl "$application")"
        $browser $url 2>/dev/null &
    else
        local cmd=(
            eos_yad --form --title="$progname"
            --text="Click an app button to see related documentation.\n"
            --image=dialog-info --button=yad-quit:11 --align-buttons
        )
        local apps=$(Options --apps)
        for application in $apps ; do
            url="$(ShowAppUrl "$application")"
            cmd+=(--field=" $application!document-open!$application documentation":fbtn "$browser $url")
        done
        local columns=$(echo "$apps" | /usr/bin/wc -l)
        columns=$(echo "sqrt($columns)" | /usr/bin/bc)
        cmd+=(--columns=$columns)
        "${cmd[@]}" 2>/dev/null
    fi
    return 0
}

Main "$@"
