#!/bin/bash

# Show the changelog info on a given app.

DIE() {
    local linenr="$1"
    local msg="$2"
    echo "$progname (line $linenr): error: $msg" >&2
    Usage
    exit 1
}

Usage() {
    cat <<EOF
Usage: $progname [options] appname
Options:
    --dump-apps    Show the supported app names.
EOF
}

Options() {
    local arg
    local app=""
    for arg in "$@" ; do
        case "$arg" in
            --dump-apps)
                echo "${APPS[@]}"
                exit 0
                ;;
            -h | --help)
                Usage
                exit 0
                ;;
            -*) ;;
            *) app="$arg" ;;
        esac
    done
    for arg in "${APPS[@]}" ; do
        if [ "$arg" = "$app" ] ; then
            xdg-open "${CHANGELOG[$app]}"
            exit 0
        fi
    done
    DIE $LINENO "sorry, '$app' not supported."
}

Main()
{
    local progname=${0##*/}
    source /etc/$progname.conf || exit 1
    [ -e /etc/${progname}-local.conf ] && source /etc/${progname}-local.conf

    Options "$@"
}

Main "$@"
