#!/bin/bash

# Show the changelog info on a given app or package.

DIE() {
    local linenr="$1"
    local msg="$2"
    echo "$progname (line $linenr): error: $msg" >&2
    Usage
    exit 1
}

Usage() {
    cat <<EOF
Usage: $progname [options] appname
Options:
    --dump-apps    Show the supported app names.
EOF
}

Options() {
    local arg
    local app=""
    for arg in "$@" ; do
        case "$arg" in
            $DUMP_APPS)
                echo "${apps[@]}"
                exit 0
                ;;
            -h | --help)
                Usage
                exit 0
                ;;
            -*) ;;
            *) app="$arg" ;;
        esac
    done

    local ix=0
    for arg in "${apps[@]}" ; do
        if [ "$arg" = "$app" ] ; then
            xdg-open "${changelog[$ix]}"
            exit 0
        fi
        ((ix++))
    done
    DIE $LINENO "sorry, '$app' not supported. Use option $DUMP_APPS to see supported apps."
}

GetAppsAndUrls() {
    local ix name count=${#CHANGELOG[@]}

    for ((ix=0; ix < count;)) ; do
        apps+=("${CHANGELOG[$ix]}")
        ((ix++))
        changelog+=("${CHANGELOG[$ix]}")
        ((ix++))
    done
}

Main()
{
    local -r DUMP_APPS="--dump-apps"
    local progname=${0##*/}
    local apps=()
    local changelog=()
    local CHANGELOG=()   # from config file

    source /etc/$progname.conf || exit 1
    [ -e /etc/${progname}-local.conf ] && source /etc/${progname}-local.conf
    GetAppsAndUrls

    Options "$@"
}

Main "$@"
