#!/bin/bash

Main()
{
    local commands=(
        "cd /usr/share/app-info/xmls ;"
        "mkdir -p BAK ;"
        "cp community.xml.gz BAK/ ;"
        "gunzip community.xml.gz ;"
        "sed -i community.xml -e 's|[<]em>not[<]/em>|*not*|' ;"
        "gzip community.xml"
    )
    su -c "${commands[*]}"
}

Main "$@"
