#!/bin/bash

# - help build endeavouros and other packages
# - help update sources


echo2()   { echo "$@" >&2 ; }
printf2() { printf "$@" >&2 ; }
RequireApp() { which "$1" &>/dev/null || DIE "this operation needs '$1' installed." ; }

DIE() {
    echo2 "$progname: error: $1"
    WaitToQuit 1
    exit 1
}
DIEF() {
    printf2 "%s: error:\n" "$progname"
    printf2 "%s\n" "$@"
    WaitToQuit 1
    exit 1
}

WaitToQuit() {
    if [ "$WaitToQuit" = "yes" ] ; then
        read -pr "Press ENTER to quit: " >&2
        exit "$1"
    fi
}

tar-name-components() {
    # show components of names as of the output of:
    #     tar -tf "db-file" | grep -v /desc$ | sed 's|/$||'
    sed -E 's/([a-zA-Z0-9@_+][a-zA-Z0-9@._+-]+)-([0-9:]*[^:/\-\ \t]+)-([0-9\.]+)/\1|\2-\3/'
    #          name...........................   epoch..pkgver......   pkgrel..
}

AskFolder() {
    RequireApp fzf
    local -r name=$(printf "%s\n" "$(_pb --reponames)" | fzf)
    [ -n "$name" ] && $progname "$name"
    WaitToQuit
    exit
}

ChangeLog() {
    local pkgname="$1"
    local url=${PKG_CHANGELOGS["$pkgname"]}

    if [ -n "$url" ] ; then
        firefox "$url"
    else
        echo2 "$progname: no changelog for $pkgname."
    fi
}

_pb() {
    local -r RED=$'\e[0;91m'
    local -r GREEN=$'\e[0;92m'
    local -r BLUE=$'\e[0;94m'
    local -r MAGENTA=$'\e[0;95m'
    local -r RESET=$'\e[0m'

    pb_IsSupportedFolderName() {
        local sf
        local folder=""
        case "$1" in
            "" | ".") folder="${PWD}" ;;
            *)        folder="${1}" ;;
        esac
        for sf in $supported_folders ; do
            if [ "${folder##*/}" = "$sf" ] ; then
                repodir=$folder  #"${folder##*/}"
                return 0
            fi
        done
        return 1
    }
    local progname=${0##*/}
    local WaitToQuit=no

    [ -n "$CODEDIR" ] || DIE "variable CODEDIR cannot be empty."

    local MAN="$CODEDIR/MAN" ; [ -d "$MAN" ] || DIE "folder $MAN does not exist."
    local EOS="$CODEDIR/EOS" ; [ -d "$EOS" ] || DIE "folder $EOS does not exist."

    local folder="$PWD"
    local repodir=""
    local repodirs=()
    local op="-n"
    local dir1 dir2 dirs
    local supported_folders
    local pkgnames_para=""
    local changelogfor=""

    supported_folders="MAN EOS $(pacconf --repo-list | grep -P '^endeavouros|^m-|^local-repo' | tr '\n' ' ')"

    while [ -n "$1" ] ; do
        case "$1" in
            -h | --help)
                cat <<EOF >&2

Build packages if needed.

Usage: ${FUNCNAME[0]} [options] [params]

Params:
    repodir
        - "": uses current folder
        - One of: $supported_folders
    --pull
        Show potential pull requests and issues. Options ignored.
    --check-all
        Check all supported folders.
    --assets.conf-check
        Check for changes of file assets.conf.
    --pkgdb <db-filename>
        Show the contents of the given package database (*.db.tar.xz).
    --mirrorlist-arch
        Show a generated mirrorlist from the Arch web page. Useful for testing only.

Options:
    -b                Directly try to build packages.
    --editme          Edit this file.
    -h, --help        This help.
    -n, ""            Check if build is needed, using local packages.
    -nn               Check if build is needed, using remote packages.
    -p, --pkgnames "X"    X is a comma separated list of packages to build.
    --reponames       Show names of supported repos and folders.
    -c, --changelog   Show the changelog of a package, if available.
EOF
                WaitToQuit
                return
                ;;
            --editme)
                for op in "$EDITOR" ide emacs kate "qtcreator -client" xed geany adie mousepad gedit ; do
                    if [ -n "$op" ] && type "${op%% *}" &>/dev/null ; then
                        $op "$0"
                        return
                    fi
                done
                DIE "option '$1': no editor found."
                ;;
            --dump-options)
                op="-p --pkgnames --dryrun --dryrun-local --build --repoup --allow-downgrade"
                op+=" -n -nn -b"
                op+=" --dump-options --dump-options-single --editme --help -h --reponames --pull"
                op+=" --check-all --assets.conf-check --pkgdb --changelog --changelog-modified --mirrorlist-arch"
                echo "$op"
                return
                ;;
            --changelog | -c)
                changelogfor="$2"
                shift
                ;;
            --changelog-modified)
                op="--pkgdiff"
                ;;
            --changelog=* | -c=*)
                changelogfor="${1#*=}"
                ;;
            --wait-to-quit)
                WaitToQuit=yes
                ;;
            -p | --pkgnames)
                pkgnames_para="$2"
                shift
                ;;
            -p=* | --pkgnames=*)
                pkgnames_para="${1#*=}"
                ;;
            --reponames)
                echo "$supported_folders"
                return
                ;;
            --pull)   # | pull)
                pull-requests
                WaitToQuit
                return
                ;;
            --mirrorlist-arch)
                firefox "https://archlinux.org/mirrorlist/?country=all&protocol=https&ip_version=4"
                return
                ;;
            --check-all)
                for folder in $supported_folders \
                              --assets.conf-check --pull     # NOTE: additional commands!
                do
                    printf2 "\n${GREEN}==> %s %s${RESET}\n" "$progname" "$folder"
                    # echo2 "==> $progname $folder"
                    $progname -nn "$folder" || DIE "'$progname $folder' failed."
                done
                WaitToQuit
                return
                ;;
            --assets.conf-check)
                local ret=0
                local len=0
                
                for folder in "$EOS/eos-pkgbuild-setup" "$MAN/b-assets" ; do
                    [ ${#folder} -gt $len ] && len=${#folder}
                done
                for folder in "$EOS/eos-pkgbuild-setup" "$MAN/b-assets" ; do
                    printf2 "%-*s : " "$len" "$folder"
                    pushd "$folder" >/dev/null || DIE "folder '$folder' does not exist."
                    if [ -n "$(git diff)" ] ; then
                        echo2 "Diffs detected"
                        ret=1
                        meld-rcs
                    else
                        echo2 "OK"
                    fi
                    popd >/dev/null || DIE "popd from '$folder' failed"
                done
                WaitToQuit $ret
                return $ret
                ;;
            --pkgdb=* | --pkgdb)
                local pkgdb
                case "$1" in
                    --pkgdb) pkgdb="$2" ; shift ;;
                    *)       pkgdb=${1#*=} ;;
                esac
                [ -e "$pkgdb" ] || DIE "option --pkgdb: file '$pkgdb' cannot be read."
                tar -tf "$pkgdb" | grep -v /desc$ | sed 's|/$||' | tar-name-components | column -t -s"|"
                WaitToQuit
                return
                ;;
            --repoup | -n | -nn | -nl | --dryrun-local | -nr | --dryrun | --pkgdiff | -ad | --allow-downgrade)
                op="$1" ;;
            -b | --build) op="" ;;
            -*) DIE "unsupported option '$1'" ;;
            *)  repodirs+=("$1") ;;
        esac
        shift
    done

    [ ${#repodirs[@]} -eq 0 ] && repodirs=("$PWD")

    for repodir in "${repodirs[@]}" ; do
        printf "\n============================ %s ============================\n" "$repodir"
        _pb2
    done
}

_pb2() {
    if ! pb_IsSupportedFolderName "$repodir" ; then
        # DIEF "repo/folder '$folder' is not supported." "Supported: $supported_folders"
        AskFolder "$repodir"
    fi

    case "$repodir" in
        MAN | EOS | */MAN | */EOS)
            # special for UpdateSources
            pushd "$repodir" >/dev/null || DIE "'pushd $repodir' failed"
            UpdateSources
            popd >/dev/null || DIE "popd from '$repodir' failed"
            WaitToQuit
            return
            ;;
        local-repo)
            #pushd "$repodir" >/dev/null || DIE "'pushd $repodir' failed"
            local-repo-manager
            #popd >/dev/null || DIE "popd from '$repodir' failed"
            #WaitToQuit
            return
            ;;
    esac

    for dir1 in "${CDPATH_ARR[@]}" ; do
        case "$dir1" in
            */_BUILD_)
                dirs=("$dir1"/*)
                for dir2 in "${dirs[@]}" ; do
                    case "$repodir" in
                        "" | .) repodir="$PWD" ;;
                    esac
                    case "$repodir" in
                        /*)
                            if [ "$repodir" -ef "$dir2" ] ; then
                                repodir="$dir2"
                                break 2
                            fi
                            ;;
                        *)
                            case "$dir2" in
                                */"$repodir")
                                    repodir="$dir2"
                                    break 2
                                    ;;
                            esac
                            ;;
                    esac
                done
                ;;
        esac
    done

    if [ -n "$changelogfor" ] ; then
        pushd "$repodir" >/dev/null || DIE "'pushd $repodir' failed"
        # shellcheck disable=SC1091
        source "assets.conf" || DIE "cannot find assets.conf in '$repodir'"
        ChangeLog "$changelogfor"
        popd >/dev/null || DIE "popd from '$repodir' failed"
        exit
    fi

    local cwd="$PWD"
    local exit_code=0

    if [ -n "$repodir" ] ; then
        cd "$repodir" || {
            WaitToQuit
            return 1
        }
        if [ ! -L .git ] ; then
            echo2 "${FUNCNAME[0]}: '$PWD/.git' does not exist or is not a symlink."
            cd "$cwd" || DIE "'cd $cwd' failed"
            WaitToQuit 1
            return 1
        fi
    fi

    if [ -n "$pkgnames_para" ] ; then
        /bin/assets.make "$op" --pkgnames="${pkgnames_para//,/ }"
    else
        /bin/assets.make "$op"
    fi
    exit_code=$?
    cd "$cwd" || DIE "'cd $cwd' failed"
    case $exit_code in
        100 | 0) ;;
        *)
            WaitToQuit $exit_code
            return $exit_code
            ;;
    esac
    WaitToQuit
}

_pb "$@"
