#!/bin/bash

# - help build endeavouros and other packages
# - help update sources

echo2() { echo "$@" >&2 ; }
Which() { which "$1" &>/dev/null ; }

DIE() {
    echo2 "$progname: error: $1"
    WaitToQuit 1
    exit 1
}
DIEF() {
    printf2 "%s: error:\n" "$progname"
    printf2 "%s\n" "$@"
    WaitToQuit 1
    exit 1
}

WaitToQuit() {
    if [ "$WaitToQuit" = "yes" ] ; then
        read -p "Press ENTER to quit: " >&2
        exit $1
    fi
}

tar-name-components() {
    # show components of names as of the output of:
    #     tar -tf "db-file" | grep -v /desc$ | sed 's|/$||'
    sed -E 's/([a-zA-Z0-9@_+][a-zA-Z0-9@._+-]+)-([0-9:]*[^:/\-\ \t]+)-([0-9\.]+)/\1|\2-\3/'
    #          name...........................   epoch..pkgver......   pkgrel..
}

AskFolder() {
    local name

    Which fzf || DIE "this operation needs 'fzf' installed."

    if [ -n "$repodir" ] ; then
        echo2 "Folder '${repodir/$HOME/\~}' is not supported. "
    else
        echo2 "Current folder (${PWD/$HOME/\~}) is not supported."
    fi
    printf2 "Supported folders:\n   $(pc --reponames)\n"
    read -p "[ENTER] continue, [Ctrl-C] quit: " >&2

    name=$(printf "%s\n" $(pc --reponames) | fzf)
    if [ -n "$name" ] ; then
        sleep 1
        pc $name
    fi
    WaitToQuit
    exit
}

_pc() {
    pc_IsSupportedFolderName() {
        local sf
        local folder=""
        case "$1" in
            "" | ".") folder="${PWD}" ;;
            *)        folder="${1}" ;;
        esac
        for sf in $supported_folders ; do
            if [ "${folder##*/}" = "$sf" ] ; then
                repodir=$folder  #"${folder##*/}"
                return 0
            fi
        done
        return 1
    }
    local progname=${0##*/}
    local WaitToQuit=no

    [ -n "$CODEDIR" ] || DIE "variable CODEDIR cannot be empty."

    local MAN="$CODEDIR/MAN" ; [ -d "$MAN" ] || DIE "folder $MAN does not exist."
    local EOS="$CODEDIR/EOS" ; [ -d "$EOS" ] || DIE "folder $EOS does not exist."

    local folder="$PWD"
    local repodir=""
    local repodirs=()
    local op=""
    local dir1 dir2 dirs
    local supported_folders="$(pacconf --repo-list | grep -P '^endeavouros|^m-' | tr '\n' ' ') MAN EOS"
    local pkgnames_para=""

    while [ -n "$1" ] ; do
        case "$1" in
            -h | --help)
                cat <<EOF >&2

Build packages if needed.

Usage: $FUNCNAME [options] [params]

Params:
    repodir
        - "": uses current folder
        - One of: $supported_folders
    --pull
        Show potential pull requests and issues. Options ignored.
    --check-all
        Check all supported folders.
    --check-assets-conf
        Check for changes of file assets.conf.
    --pkgdb <db-filename>
        Show the contents of the given package database (*.db.tar.xz).

Options:
    -b                Directly try to build packages.
    --editme          Edit this file.
    -h, --help        This help.
    -n, ""            Check if build is needed, using local packages.
    -nn               Check if build is needed, using remote packages.
    --pkgnames "X"    X is a space separated list of packages to build.
    --reponames       Show names of supported repos and folders.
EOF
                WaitToQuit
                return
                ;;
            --editme)
                for op in kate $EDITOR emacs kate qute xed geany adie mousepad gedit ; do
                    if type $op &>/dev/null ; then
                        $op "$0"
                        return
                    fi
                done
                DIE "option '$1': no editor found."
                ;;
            --dump-options)
                op="--pkgnames= --dryrun --dryrun-local --build --repoup --allow-downgrade"
                op+=" -n -nn -b"
                echo $op
                return
                ;;
            --dump-options-single)
                # "single" options will ignore other parameters!
                op="--dump-options --dump-options-single --editme --help -h --reponames --pull"
                op+=" --check-all --check-assets-conf --pkgdb="
                echo $op
                return
                ;;
            --wait-to-quit)
                WaitToQuit=yes
                ;;
            --pkgnames)
                pkgnames_para="$2" ; shift
                ;;
            --pkgnames=*)
                pkgnames_para="${1#*=}"
                ;;
            --reponames)
                echo "$supported_folders"
                return
                ;;
            --pull | pull)
                pull-requests
                WaitToQuit
                return
                ;;
            --check-all)
                for folder in $supported_folders pull
                do
                    echo2 "==> pc $folder"
                    pc $folder || DIE "'pc $folder' failed."
                done
                WaitToQuit
                return
                ;;
            --check-assets-conf)
                local ret=0
                for folder in "$EOS/eos-pkgbuild-setup" "$MAN/b-assets"
                do
                    echo "$folder" >&2
                    pushd $folder >/dev/null || DIE "folder '$folder' does not exist."
                    if [ -n "$(git diff)" ] ; then
                        ret=1
                        meld-rcs
                    fi
                    popd >/dev/null
                done
                case $ret in
                    0) echo2 "No changes in assets.conf(s)." ;;
                    1) echo2 "Changes detected in assets.conf(s)." ;;
                esac
                WaitToQuit $ret
                return $ret
                ;;
            --pkgdb=* | --pkgdb)
                local pkgdb
                case "$1" in
                    --pkgdb) pkgdb="$2" ; shift ;;
                    *)       pkgdb=${1#*=} ;;
                esac
                [ -e "$pkgdb" ] || DIE "option --pkgdb: file '$pkgdb' cannot be read."
                tar -tf "$pkgdb" | grep -v /desc$ | sed 's|/$||' | tar-name-components | column -t -s"|"
                WaitToQuit
                return
                ;;
            -*) op="$1" ;;
            *)  repodirs+=("$1") ;;
        esac
        shift
    done

    [ ${#repodirs[@]} -eq 0 ] && repodirs=("$PWD")

    for repodir in "${repodirs[@]}" ; do
        _pc2
    done
}

_pc2() {
    if ! pc_IsSupportedFolderName "$repodir" ; then
        # DIEF "repo/folder '$folder' is not supported." "Supported: $supported_folders"
        AskFolder "$repodir"
    fi

    case "$repodir" in
        MAN | EOS | */MAN | */EOS)
            # special for UpdateSources
            pushd "$repodir" >/dev/null
            UpdateSources
            popd >/dev/null
            WaitToQuit
            return
            ;;
    esac

    for dir1 in "${CDPATH_ARR[@]}" ; do
        case "$dir1" in
            */_BUILD_)
                dirs=("$dir1"/*)
                for dir2 in "${dirs[@]}" ; do
                    case "$repodir" in
                        "" | .) repodir="$PWD" ;;
                    esac
                    case "$repodir" in
                        /*)
                            if [ "$repodir" -ef "$dir2" ] ; then
                                repodir="$dir2"
                                break 2
                            fi
                            ;;
                        *)
                            case "$dir2" in
                                */"$repodir")
                                    repodir="$dir2"
                                    break 2
                                    ;;
                            esac
                            ;;
                    esac
                done
                ;;
        esac
    done
    case "$op" in
        "") op="-n" ;;                # ""  = check local
        -n | -nn) ;;                  # -n  = check local
        # -nn = check remote
        -b) op="" ;;                  # -b  = build
        *)
            echo2 "$FUNCNAME: unsupported option '$op'"
            $FUNCNAME -h
            WaitToQuit 1
            return 1
            ;;
    esac

    local cwd="$PWD"
    local exit_code=0

    if [ -n "$repodir" ] ; then
        cd "$repodir" || {
            WaitToQuit
            return 1
        }
        if [ ! -L .git ] ; then
            echo2 "$FUNCNAME: '$PWD/.git' does not exist or is not a symlink."
            cd "$cwd"
            WaitToQuit 1
            return 1
        fi
    fi

    # echo2 "params = $op $pkgnames_para"

    if [ -n "$pkgnames_para" ] ; then
        /bin/assets.make $op --pkgnames="$pkgnames_para"
    else
        /bin/assets.make $op
    fi
    exit_code=$?
    cd "$cwd"
    case $exit_code in
        100 | 0) ;;
        *)
            WaitToQuit $exit_code
            return $exit_code
            ;;
    esac
    WaitToQuit
}

_pc "$@"
