#!/bin/bash

# Check if package rebuilds are needed.

DIE() {
    local progname="$(basename "$0")"
    echo "$progname: error: $1" >&2
    Options -h
    exit 1
}

Options() {
    local progname="$(/usr/bin/basename "$0")"
    local opts

    opts="$(/usr/bin/getopt -o=h --longoptions help,build,dryrun-local,dryrun,allow-downgrade,repoup --name "$progname" -- "$@")" || {
        Options -h
        return 1
    }

    eval set -- "$opts"

    while true ; do
        case "$1" in
            --dryrun-local | --dryrun | --allow-downgrade | --repoup)
                opt="$1"
                ;;
            --build)
                opt=""
                ;;

            -h | --help)
                cat <<EOF >&2

Usage: $progname [operation] [options] [folder]

Operations:
  --dryrun-local       Dryrun, don't download assets from remote (minimal dryrun).
                       Without a given operation this is the default.
  --dryrun             Dryrun, download assets from remote first (full dryrun).
  --repoup             Update only the database files (advanced).
  --build              Build and release updated packages (advanced).

Options:
  --allow-downgrade    New package is allowed to get a smaller version number (advanced).
                       By default updated packages must have a bigger version number.
Params:
  folder               A basename of the folder path where assets will be built.
                       Default: $default_folder

EOF
                exit 0
                ;;
            
            --) shift ; break ;;
        esac
        shift
    done

    [ -n "$1" ] && folder="$1"

    case "$folder" in
        m-aur | m-m | m-more2 | mirrors.mirror1 | repo-testing.x86_64 | local-repo) ;;
        *) DIE "folder '$folder' is not supported." ;;
    esac
        
}

pkgcheck() {
    local -r default_folder="mirrors.mirror1"
    local -r default_opt="--dryrun-local"

    local folder="$default_folder"
    local opt="$default_opt"

    Options "$@" || return $?

    source $HOME/.config/cd.conf || return $?
    source /etc/skel/cd.bash || return $?

    pushd ~/ >/dev/null
    pushd $folder >/dev/null
    case "$folder" in
        local-repo) ./local-repo-manager ;;
        *) assets.make $opt ;;
    esac
    popd >/dev/null
    popd >/dev/null
}

pkgcheck "$@"
