#!/bin/bash
#
# Show number of pull requests for PKGBUILDS.
#

echo2() { echo "$@" >&2 ; }
printf2() { printf "$@" >&2 ; }

DIE() {
    echo2 "$progname: error: $1"
    exit 1
}

Main2()
{
    local url="$1"
    local url2="$url/issues"
    local main_count
    local comments
    local strings=(
        "Pull requests"
        "Issues"
    )
    local data
    local str
    local maxstrlen=0
    local maxurllen=0
    test -n "$url" || DIE "no URL!"

    for str in "${strings[@]}" ; do
        if [ $maxstrlen -lt ${#str} ] ; then
            maxstrlen=${#str}
        fi
    done

    for str in "${urls[@]}" ; do
        if [ $maxurllen -lt ${#str} ] ; then
            maxurllen=${#str}
        fi
    done

    data="$(curl -s $url)"
    [ -n "$data" ] || DIE "data not available!"

    for str in "${strings[@]}" ; do

        printf2 "%-*s for %-*s : " "$maxstrlen" "$str" "$maxurllen" "$url"

        main_count="$(echo "$data" | grep -A1 "$str</span>" | tail -n 1 | sed -E 's|.*>([0-9]+)</span>$|\1|')"
        comments=0

        if true ; then
            [ "$main_count" -gt 0 ] && echo2 "$main_count" || echo2 "-"
        else
            # not working...
            case "$main_count" in
                [1-9] | [1-9][0-9] | [1-9][0-9][0-9] | [1-9][0-9][0-9][0-9]*)
		    comments=$(curl -s $url2 | grep -E '"[0-9]+ comment' | sed -E 's|.*/issues/([0-9]+)".* aria-label="([0-9]+) comment.*|issue \1: \2 comments|')
                    ;;
                *)
                    main_count=none
                    ;;
            esac
            case "$main_count" in
	        "" | none | 0)
                    printf2 "$main_count " ;;
                *)
                    printf2 "$main_count, " ;;
            esac
            if [ "$str" = "Issues" ] ; then
                [ -n "$comments" ] && printf2 "%s" "$comments"
            fi
            printf2 "\n"
        fi
    done
}

Main() {
    local progname="$(basename "$0")"
    local urls=(
        https://github.com/endeavouros-team/PKGBUILDS
        https://github.com/endeavouros-team/eos-bash-shared
        https://github.com/endeavouros-team/eos-pkgbuild-setup
        https://github.com/endeavouros-team/welcome
        https://github.com/endeavouros-team/Important-news
        https://github.com/endeavouros-team/ISO-hotfixes
        https://github.com/endeavouros-team/EndeavourOS-ISO
        # https://github.com/endeavouros-team/repo

        # https://github.com/endeavouros-team/User-contributions
        # https://github.com/rogalmic/vscode-bash-debug

        https://github.com/manuel-192/m-m
        https://github.com/manuel-192/m-aur2
        https://github.com/manuel-192/m-more2
    )
    local url
    for url in "${urls[@]}" "$@" ; do
        Main2 "$url"
    done
}

Main "$@"
