#!/bin/bash

Result() { echo -e "$1" ; }

Main3()
{
    local url="$1"
    local pagedata retval
    local item=$(echo "$url" | sed 's|https://github\.com/||')

    printf "%-45s: " "$item"

    pagedata=$(curl --fail -Lsm 10 -o- "$url")
    retval=$?
    [ $retval -ne 0 ] && DIE "curl '$url' failed"
    local issue_numbers=$(echo "$pagedata" | grep -E '^<div id="issue_[0-9]+' | sed -E 's|^<div id="issue_([0-9]+)".*|\1|')
    local issue_text
    local nr

    if [ -z "$issue_numbers" ] ; then
        Result "-"
        return
    fi

    for nr in $issue_numbers ; do
        issue_text=$(echo "$pagedata" | sed -n "/^<div id=\"issue_$nr\"/,/^<\/div>$/p")
        comments="$(echo "$issue_text" | grep -E 'Link--muted.*"[0-9]+ comment' | sed -E 's|.*aria-label="([0-9]+).*|\1|')"
        case "$comments" in
            "") Result "#$nr: no comments yet" ;;
            *)  Result "#$nr: $comments comments" ;;
        esac
    done
}

Main2() {
    local urlbase="$1"
    local last

    for last in issues pulls ; do
        Main3 "$urlbase/$last"
    done
}

Main() {
    local urls=(
        https://github.com/endeavouros-team/PKGBUILDS
        https://github.com/endeavouros-team/eos-bash-shared
        https://github.com/endeavouros-team/eos-pkgbuild-setup
        https://github.com/endeavouros-team/welcome
        https://github.com/endeavouros-team/Important-news
        https://github.com/endeavouros-team/ISO-hotfixes
        https://github.com/endeavouros-team/EndeavourOS-ISO
        # https://github.com/endeavouros-team/repo

        # https://github.com/endeavouros-team/User-contributions
        # https://github.com/rogalmic/vscode-bash-debug

        https://github.com/manuel-192/m-m
        https://github.com/manuel-192/m-aur2
        https://github.com/manuel-192/m-more2
    )
    local url
    for url in "${urls[@]}" "$@" ; do
        Main2 "$url"
    done
}

Main "$@"
