#!/bin/bash

source /etc/eos-color.conf

echo2() { echo -e "$@" >&2; }
DIE()   { echo2 "$progname: error: $1"; exit 1; }

MakeDateRedInRecentEntry() {
    # Make the date of a recent entry RED.
    local updated_at_sec
    updated_at_sec=$(date --date="$updated_at" "+%s")
    if [ $((updated_at_sec + seconds_in_month)) -gt "$seconds_now" ] ; then
        updated_at="${RED}$updated_at${RESET}"
    fi
}

Parse() {
    local type out count ix kind title
    local updated_at
    local before_title=33
    local -r columns=$(tput cols)
    local -r splitcolumn=$((columns - before_title))
    local -r seconds_in_month=$((31 * 24 * 3600))
    local -r seconds_now=$(date +%s)

    for type in issue pr ; do
        out=$(gh $type list --json updatedAt,title)
        count=$(echo "$out" | jq -c .[].updatedAt | wc -l)
        if [ "$count" -gt 0 ] ; then
            case "$type" in
                issue) kind="[Issue]" ;; 
                pr)    kind="[Pull]" ;;
            esac
            for ((ix=0; ix < count; ix++)) ; do
                updated_at="$(echo -n "$out" | jq .[$ix].updatedAt | tr -d '"')"
                MakeDateRedInRecentEntry
                title="$(     echo -n "$out" | jq .[$ix].title     | tr -d '"')"

                # handle splitting of long lines
                if [ "${#title}" -gt $splitcolumn ] ; then
                    printf "    %-7s %s %s\n" "$kind" "$updated_at" "${title::$splitcolumn}"
                    printf "%*s%s\n" "$before_title" " " "${title:$splitcolumn}"
                else
                    printf "    %-7s %s %s\n" "$kind" "$updated_at" "${title}"
                fi
            done
        fi
    done
}

MsgHandle() {
    local url="$1"
    local dir=${url##*/}
    local nl=no

    # Maybe another implementation using:
    #   gh repo view "user"/"repo"  --json issues,pullRequests --jq .issues,.pullRequests | less

    cd "$dir" >/dev/null || DIE "'cd $dir' failed"
    echo "- $dir"
    Parse
    [ $nl = yes ] && echo ""
}

Main2() {
    local url
    for url in "$@" ; do
        MsgHandle "$url"
    done
}

Main1() {
    local who="$1"
    shift

    # shellcheck disable=2154
    case "$who" in
        e)  Main2 "${urls_e[@]}" "$@" ;;    # from $configfile
        m)  Main2 "${urls_m[@]}" "$@" ;;    # from $configfile
        b)  Main1 e "$@"; Main1 m "$@" ;;
    esac
}

Main() {
    local -r progname=${0##*/}
    local -r targetdir=$(mktemp -d)
    local interesting_urls=()
    local show_interesting_urls=yes
    local url
    local app=""
    local who=b
    local -r configfile="$HOME/.config/$progname.conf"

    # shellcheck disable=1090
    source "$configfile"

    while [ "$1" ] ; do
        case "$1" in
            -h | --help)
                cat <<EOF
Usage: $progname [options]
Options:
    -h, --help      This help.
    -s, --show      Show interesting URLs. Default.
    --no-show       Don't show interesting URLs.
EOF
                ;;
            -s | --show)  show_interesting_urls=yes ;;
            --no-show)    show_interesting_urls=no ;;
            -e | -m | -b) who=${1:1} ;;                   # -e=endeavouros -m=other -b=both
        esac
        shift
    done

    Main1 "$who" "$@"

    if [ $show_interesting_urls = yes ] && [ ${#interesting_urls[@]} -gt 0 ] ; then
        FirstAppOf app exo-open kde-open xdg-open
        case "$app" in
            "")       DIE "no mime app found!" ;;
            exo-open) $app "${interesting_urls[@]}"
                      ;;
            *)        for url in "${interesting_urls[@]}" ; do
                          $app "$url"
                          sleep 0.5
                      done
                      ;;
        esac
    fi

    rm -rf "$targetdir"
}

FirstAppOf() {
    local -n _app="$1"
    shift
    for _app in "$@" ; do
        [ -x "/bin/$_app" ] && return
    done
    _app=""
}

Main "$@"
