#!/bin/bash

# Convert curl return code to human friendly text.
# See 'man curl' for more info.

DIE() {
    echo "Error: $1" >&2
    exit 1
}

Generate() {
    local tmp=$(mktemp)
    cat <<EOF > $tmp
#!/bin/bash
_generated_func_() {
    local curlRetCode="\$1"
    local msg
    case "\$curlRetCode" in
$(man curl | sed -n '/^EXIT CODES$/,/^AUTHORS \/ CONTRIBUTORS$/'p | grep "^ [ ]*[0-9]" | sed 's|[ ]*\([0-9]*\)[ ]*\(.*\)$|        \1) msg="\2" ;;|')
        0) msg="OK" ;;
        *) msg="[CURL doc error]: unsupported error code '\$curlRetCode'. See 'man curl'." ;;
    esac
    echo "\$msg"
}
_generated_func_ "\$1"
EOF
    chmod +x $tmp
    echo "Creating curl code converter into $converter:" >&2
    sudo mv $tmp $converter
}

CurlReturnCodeToString() {
    local curlRetCode=""
    local converter=/usr/local/bin/curl-code-to-string-converter

    while [ -n "$1" ] ; do
        case "$1" in
            --create | -c)  Generate ; return ;;
            --remove | -r)  echo "Removing $converter:" >&2 ; sudo rm -f $converter ; return ;;
            -*)             DIE "unsupported option '$1'" ;;
            *)              curlRetCode="$1" ; shift ;;
        esac
    done

    [ -x $converter ] || Generate
    [ -x $converter ] || DIE "curl code to text converter '$converter' not found."

    $converter "$curlRetCode"
}

CurlReturnCodeToString "$@"
