#!/bin/bash

# Convert curl return code to human friendly text.
# See 'man curl' for more info.

DIE() {
    echo "Error: $1" >&2
    exit 1
}

Generate() {
    local tmp=$(mktemp)
    cat <<EOF > $tmp
#!/bin/bash
_generated_func_() {
    local curlRetCode="\$1"
    local msg
    case "\$curlRetCode" in
$(man curl | sed -n '/^EXIT CODES$/,/^AUTHORS \/ CONTRIBUTORS$/'p | grep "^ [ ]*[0-9]" | sed 's|[ ]*\([0-9]*\)[ ]*\(.*\)$|        \1) msg="\2" ;;|')
        0) msg="OK" ;;
        *) msg="[CURL doc error]: unsupported error code '\$curlRetCode'. See 'man curl'." ;;
    esac
    echo "\$curlRetCode: \$msg"
}
_generated_func_ "\$1"
EOF
    chmod +x $tmp
    rm -f "$converter"
    mv $tmp "$converter" || DIE "Creating '$converter' failed."
}

CurlReturnCodeToString() {
    local curlRetCode=""
    local cdir="$HOME/.config/curl-error-string"
    local converter="$cdir/curl-code-to-string-converter"
    local timenow_sec=$(date +%s)
    local timefile_sec=0
    local generate_interval_seconds=$((3600*24*7))   # generate curl error code list weekly

    mkdir -p "$cdir"

    [ -r "$converter" ] && timefile_sec=$(stat -c %Y "$converter")

    while [ -n "$1" ] ; do
        case "$1" in
            --create | -c)  Generate ; return ;;
            --remove | -r)  echo "Removing $converter" >&2 ; rm -f "$converter" ; return ;;
            -*)             DIE "unsupported option '$1'" ;;
            *)              curlRetCode="$1" ; shift ;;
        esac
    done

    # ((timenow_sec += generate_interval_seconds))  # testing generation!

    [ $timenow_sec -gt $((timefile_sec + generate_interval_seconds)) ] && Generate
    [ -x "$converter" ] || DIE "curl code to text converter '$converter' not found or not executable."

    "$converter" "$curlRetCode"
}

CurlReturnCodeToString "$@"
