#!/bin/bash
#
# Show info about pacman history.
#

DIE() { echo "Error: $@" >&2 ; exit 1 ; }

Usage() {
    local progname="$(basename $0)"
    cat <<EOF >&2
$progname: Show info about pacman history.

Usage: $progname operation [package]
    operation      One of: up(grade) do(wngrade) in(stall) un(install) re(install).
    package        Zero or one package name. No package means show all packages under "op".

EOF
}

Main()
{
    local op
    local pkg="$2"
    local out

    case "$1" in
        up*) op=upgraded ;;
        do*) op=downgraded ;;
        in*) op=installed ;;
        un*) op=removed ;;
        re*) op=reinstalled ;;
        *) Usage ; return 1 ;;
    esac

    test -n "$pkg" && {
        pacman -Si "$pkg" >& /dev/null || DIE "package '$pkg' does not exist."
    }

    out="$(grep -w "\[ALPM\] $op" /var/log/pacman.log)"
    test -n "$pkg" && out="$(echo "$out" | grep " $pkg ")"
    test -n "$out" && {
        echo "$out" | tac | less
    } || {
        echo "Requested info is not available."
        echo "Probable reasons:"
        echo "  - package was never installed"
        echo "  - package was installed while installing the system"
    }
}

Main "$@"
