#!/bin/bash
#
# Show info about pacman history.
#

DIE() {
    echo "Error: $@" >&2
    Usage
    exit 1
}

Usage() {
    local progname="$(basename $0)"
    cat <<EOF >&2

$progname: shows history information about package operations.

Usage: $progname operation [package]

    operation      One of: upgraded downgraded installed removed reinstalled.
                   Tip: press the Tab key to complete the word!

    package        Package name (optional). If no package name is given,
                   show all packages using the given operation.

Note: bash command completion is available.

Examples:
    ph upgraded firefox
    ph installed

EOF
}

Main()
{
    local op="$1"
    local pkg="$2"
    local output

    case "$op" in
        upgraded | downgraded | installed | removed | reinstalled) ;;
        *) DIE "unsupported operation '$op'" ;;
    esac

    test -n "$pkg" && {
        pacman -Si "$pkg" >& /dev/null || DIE "package '$pkg' does not exist."
    }

    output="$(grep -w "\[ALPM\] $op" /var/log/pacman.log)"
    test -n "$pkg" && output="$(echo "$output" | grep " $pkg ")"
    test -n "$output" && {
        echo "$output" | tac | less
    } || {
        echo "Requested info is not available."
        echo "Probable reasons:"
        echo "  - '$pkg' was never installed"
        echo "  - '$pkg' was installed while installing the system"
    }
}

Main "$@"
